-- Physics/geometry build: no generator stack (avoids GeneratorsLieClosureData stack overflow).
-- Prefer the curated `HQIVMeaningfulPhysics` target (same import graph) for a clearly named daily build.
-- Use: lake build HQIVPhysics
import Hqiv.Geometry.OctonionicLightCone
import Hqiv.Geometry.SphericalHarmonicsBridge
import Hqiv.Geometry.S7MetahorizonCasimir
import Hqiv.Geometry.AuxiliaryField
import Hqiv.Geometry.HQVMetric
import Hqiv.Geometry.HQVMetricAnalytic
import Hqiv.Geometry.HQVMPerturbations
import Hqiv.Geometry.HQVMCLASSBridge
import Hqiv.Geometry.HQVMDiscreteLaplacian
import Hqiv.Geometry.HQVMDiscretePoisson
import Hqiv.Geometry.HQVMGlobalLocalDictionary
import Hqiv.Geometry.HQVMConsistency
import Hqiv.Geometry.Now
import Hqiv.Conservations
import Hqiv.Physics.Baryogenesis
import Hqiv.Physics.BigBangNucleosynthesis
import Hqiv.Physics.GlobalDetuning
import Hqiv.Physics.LeptonResonanceGlobalDetuning
import Hqiv.Physics.AgeNormalizedHeavyMass
import Hqiv.Physics.ModalFrequencyHorizon
import Hqiv.Physics.QuarkLadderGlobalDetuning
import Hqiv.Physics.HarmonicLadderGlobalDetuning
import Hqiv.Physics.ModifiedMaxwell
import Hqiv.Physics.SchematicPlasmaCurrent
import Hqiv.Physics.GRFromMaxwell
import Hqiv.Physics.HQIVGravityReadoutScalars
import Hqiv.Physics.HQIVFluidClosureScaffold
import Hqiv.Physics.OrbitalFlybyScaffold
import Hqiv.Physics.OrbitalTrajectoryJ2Scaffold
import Hqiv.Physics.SO8PlaquetteHolonomy
import Hqiv.Physics.NonAbelianHolonomyMeasureScaffold
import Hqiv.Physics.DiscreteActionPoincareScaffold
import Hqiv.Physics.DiscreteActionStrongPoincareBridge
import Hqiv.Physics.CoronalLongitudinalStress
import Hqiv.Physics.HQIVTurbulenceSimulatorScaffold
import Hqiv.Physics.ToyDiscreteHeat
import Hqiv.Physics.ThermodynamicLawsFromLadder
import Hqiv.Physics.LightConeFundamentalsPillars
import Hqiv.Physics.HQIVPerturbationScaffold
import Hqiv.Physics.DoublePreferredAxis
import Hqiv.Physics.DoublePreferredAxisAlpha
import Hqiv.Physics.ContinuousXiCoupling
import Hqiv.Physics.ContinuousXiPath
import Hqiv.Physics.ContinuousXiMixingGeometry
import Hqiv.Physics.Forces
import Hqiv.Physics.PromotedOMaxwell
import Hqiv.Physics.BoundStates
import Hqiv.Physics.DerivedGaugeAndLeptonSector
import Hqiv.Physics.InformationalEnergyMass
import Hqiv.Physics.HadronMassReadout
import Hqiv.Physics.HepDecayReadout
import Hqiv.Physics.NaturalUnitMeVTheory
import Hqiv.Physics.ScaleWitness
import Hqiv.Physics.DiscretePlaquetteHolonomy
import Hqiv.Physics.ActionHolonomyGlue
import Hqiv.Physics.ReadoutGaugeSeed
import Hqiv.Physics.NuclearAndAtomicSpectra
import Hqiv.Physics.HQIVNuclei
import Hqiv.Physics.NeutronBindingStabilityScaffold
import Hqiv.Physics.CasimirForceFromAction
import Hqiv.Physics.HQIVAtoms
import Hqiv.Physics.HQIVMolecules
import Hqiv.Physics.HQIVAssembly
import Hqiv.Physics.HQIVCollectiveModes
import Hqiv.Physics.ForceCarrierWhip
import Hqiv.QuantumMechanics.Schrodinger
import Hqiv.QuantumMechanics.FiniteManyBodyCore
import Hqiv.QuantumMechanics.HubbardDimerFinite
import Hqiv.QuantumMechanics.HubbardDimerWitnessTable
import Hqiv.QuantumMechanics.HubbardDimerGapBridge
import Hqiv.QuantumMechanics.HubbardDimerHalfFilledObservables
import Hqiv.QuantumMechanics.UncertaintyPrinciple
import Hqiv.QuantumOptics.HorizonQED
