-- Physics-only import surface: light cone through HQVM, SM/GR + resonance stack, and selected QM/QED.
-- Deliberately excludes the bulk `HQIVLEAN` chain (TSP, SAT, factor search, CNF, standalone RH/θ zeta
-- scaffolds, protein/QC oracles, etc.); those live only under `HQIVLEAN` and other full-repo targets.
-- Use: `lake build HQIVMeaningfulPhysics` (same import graph as `HQIVPhysics.lean`, separate Lake target)
import Hqiv.Geometry.OctonionicLightCone
import Hqiv.Geometry.SphericalHarmonicsBridge
import Hqiv.Geometry.S7MetahorizonCasimir
import Hqiv.Geometry.AuxiliaryField
import Hqiv.Geometry.HQVMetric
import Hqiv.Geometry.HQVMetricAnalytic
import Hqiv.Geometry.HQVMPerturbations
import Hqiv.Geometry.HQVMCLASSBridge
import Hqiv.Geometry.HQVMDiscreteLaplacian
import Hqiv.Geometry.HQVMDiscretePoisson
import Hqiv.Geometry.HQVMGlobalLocalDictionary
import Hqiv.Geometry.HQVMConsistency
import Hqiv.Geometry.Now
import Hqiv.Conservations
import Hqiv.Physics.Baryogenesis
import Hqiv.Physics.GlobalDetuning
import Hqiv.Physics.LeptonResonanceGlobalDetuning
import Hqiv.Physics.ModalFrequencyHorizon
import Hqiv.Physics.QuarkLadderGlobalDetuning
import Hqiv.Physics.HarmonicLadderGlobalDetuning
import Hqiv.Physics.ModifiedMaxwell
import Hqiv.Physics.SchematicPlasmaCurrent
import Hqiv.Physics.GRFromMaxwell
import Hqiv.Physics.HQIVGravityReadoutScalars
import Hqiv.Physics.HQIVFluidClosureScaffold
import Hqiv.Physics.HQIVTurbulenceSimulatorScaffold
import Hqiv.Physics.ToyDiscreteHeat
import Hqiv.Physics.ThermodynamicLawsFromLadder
import Hqiv.Physics.LightConeFundamentalsPillars
import Hqiv.Physics.HQIVPerturbationScaffold
import Hqiv.Physics.ContinuousXiCoupling
import Hqiv.Physics.ContinuousXiPath
import Hqiv.Physics.ContinuousXiMixingGeometry
import Hqiv.Physics.Forces
import Hqiv.Physics.PromotedOMaxwell
import Hqiv.Physics.BoundStates
import Hqiv.Physics.DerivedGaugeAndLeptonSector
import Hqiv.Physics.NuclearAndAtomicSpectra
import Hqiv.Physics.HQIVNuclei
import Hqiv.Physics.NeutronBindingStabilityScaffold
import Hqiv.Physics.CasimirForceFromAction
import Hqiv.Physics.HQIVAtoms
import Hqiv.Physics.HQIVMolecules
import Hqiv.Physics.HQIVAssembly
import Hqiv.Physics.HQIVCollectiveModes
import Hqiv.Physics.ForceCarrierWhip
import Hqiv.QuantumMechanics.Schrodinger
import Hqiv.QuantumMechanics.FiniteManyBodyCore
import Hqiv.QuantumMechanics.HubbardDimerFinite
import Hqiv.QuantumMechanics.HubbardDimerWitnessTable
import Hqiv.QuantumMechanics.HubbardDimerGapBridge
import Hqiv.QuantumMechanics.HubbardDimerHalfFilledObservables
import Hqiv.QuantumMechanics.UncertaintyPrinciple
import Hqiv.QuantumOptics.HorizonQED
