/-
Auto-generated by `scripts/gen_strong_color_su3_lie_chart_law.py`.
Regenerate: `python3 scripts/gen_strong_color_su3_lie_chart_law.py`
-/

import Hqiv.Physics.StrongColorSu3LieCertificate
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.Tactic.Ring
import Mathlib.Tactic.FinCases

/-!
# Strong color: global `su(3)` chart Lie law (certificate layer)

Proves `∀ a b : Fin 8, [T^a,T^b] = I • ∑_c f^{abc} T^c` for `T^a = λ^a/2` on the `3×3` chart.

Imports the optional `@[simp]` table `StrongColorSu3fStructureSimp` (via `StrongColorSu3LieCertificate`);
build with `lake build HQIVStrongColorSu3Certificate`.
-/

open scoped BigOperators
open Complex Finset Matrix
open Hqiv.Algebra Hqiv.Physics

namespace Hqiv.Physics

noncomputable section

set_option maxHeartbeats 8000000

/-- Off-diagonal case (0,1). -/
lemma colorLieChartBracket_0_1 :
    lieBracketMat₃ (colorHalfGellMannFull (0 : Fin 8)) (colorHalfGellMannFull (1 : Fin 8)) =
      I • ∑ c : Fin 8, (colorSu3fStructure (0 : Fin 8) (1 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;>
    (simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    <;> try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    <;> simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    <;> ring_nf
    <;> ring)

end -- noncomputable section

end Hqiv.Physics
