/-
Auto-generated by `scripts/gen_strong_color_su3_lie_chart_law.py`.
Regenerate: `python3 scripts/gen_strong_color_su3_lie_chart_law.py` [--spine]
-/

import HqivSpine.Algebra.StrongColorSu3LieCertificate
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.FinCases

/-!
# StrongColorSu3: global `su(3)` chart Lie law

Proves `∀ a b : Fin 8, [T^a,T^b] = Complex.I • ∑_c f^{abc} T^c` for `T^a = λ^a/2` on the `3×3` chart.
included in `lake build HQIVCleanSpine`.
-/

open scoped BigOperators
open Complex Finset Matrix


namespace HqivSpine.Algebra.StrongColor

noncomputable section

set_option maxHeartbeats 8000000

theorem su3fStructure_self_eq_zero (a c : Fin 8) : su3fStructure a a c = (0 : ℝ) := by
  dsimp [su3fStructure]
  simp

theorem halfGellMannFull_f_sum_self (a : Fin 8) :
    (∑ c : Fin 8, (su3fStructure a a c : ℂ) • halfGellMannFull c) = 0 := by
  refine Finset.sum_eq_zero ?_
  intro c _
  rw [su3fStructure_self_eq_zero]
  simp

/-- Diagonal case (0,0). -/
lemma su3LieChartBracket_0_0 :
    lieBracketMat3 (halfGellMannFull (0 : Fin 8)) (halfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (0 : Fin 8) (0 : Fin 8) c : ℂ) • halfGellMannFull c := by
  rw [halfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat3, smul_zero]

/-- Off-diagonal case (0,1). -/
lemma su3LieChartBracket_0_1 :
    lieBracketMat3 (halfGellMannFull (0 : Fin 8)) (halfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (0 : Fin 8) (1 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,2). -/
lemma su3LieChartBracket_0_2 :
    lieBracketMat3 (halfGellMannFull (0 : Fin 8)) (halfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (0 : Fin 8) (2 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,3). -/
lemma su3LieChartBracket_0_3 :
    lieBracketMat3 (halfGellMannFull (0 : Fin 8)) (halfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (0 : Fin 8) (3 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,4). -/
lemma su3LieChartBracket_0_4 :
    lieBracketMat3 (halfGellMannFull (0 : Fin 8)) (halfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (0 : Fin 8) (4 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,5). -/
lemma su3LieChartBracket_0_5 :
    lieBracketMat3 (halfGellMannFull (0 : Fin 8)) (halfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (0 : Fin 8) (5 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,6). -/
lemma su3LieChartBracket_0_6 :
    lieBracketMat3 (halfGellMannFull (0 : Fin 8)) (halfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (0 : Fin 8) (6 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,7). -/
lemma su3LieChartBracket_0_7 :
    lieBracketMat3 (halfGellMannFull (0 : Fin 8)) (halfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (0 : Fin 8) (7 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,0). -/
lemma su3LieChartBracket_1_0 :
    lieBracketMat3 (halfGellMannFull (1 : Fin 8)) (halfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (1 : Fin 8) (0 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (1,1). -/
lemma su3LieChartBracket_1_1 :
    lieBracketMat3 (halfGellMannFull (1 : Fin 8)) (halfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (1 : Fin 8) (1 : Fin 8) c : ℂ) • halfGellMannFull c := by
  rw [halfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat3, smul_zero]

/-- Off-diagonal case (1,2). -/
lemma su3LieChartBracket_1_2 :
    lieBracketMat3 (halfGellMannFull (1 : Fin 8)) (halfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (1 : Fin 8) (2 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,3). -/
lemma su3LieChartBracket_1_3 :
    lieBracketMat3 (halfGellMannFull (1 : Fin 8)) (halfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (1 : Fin 8) (3 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,4). -/
lemma su3LieChartBracket_1_4 :
    lieBracketMat3 (halfGellMannFull (1 : Fin 8)) (halfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (1 : Fin 8) (4 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,5). -/
lemma su3LieChartBracket_1_5 :
    lieBracketMat3 (halfGellMannFull (1 : Fin 8)) (halfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (1 : Fin 8) (5 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,6). -/
lemma su3LieChartBracket_1_6 :
    lieBracketMat3 (halfGellMannFull (1 : Fin 8)) (halfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (1 : Fin 8) (6 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,7). -/
lemma su3LieChartBracket_1_7 :
    lieBracketMat3 (halfGellMannFull (1 : Fin 8)) (halfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (1 : Fin 8) (7 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,0). -/
lemma su3LieChartBracket_2_0 :
    lieBracketMat3 (halfGellMannFull (2 : Fin 8)) (halfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (2 : Fin 8) (0 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,1). -/
lemma su3LieChartBracket_2_1 :
    lieBracketMat3 (halfGellMannFull (2 : Fin 8)) (halfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (2 : Fin 8) (1 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (2,2). -/
lemma su3LieChartBracket_2_2 :
    lieBracketMat3 (halfGellMannFull (2 : Fin 8)) (halfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (2 : Fin 8) (2 : Fin 8) c : ℂ) • halfGellMannFull c := by
  rw [halfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat3, smul_zero]

/-- Off-diagonal case (2,3). -/
lemma su3LieChartBracket_2_3 :
    lieBracketMat3 (halfGellMannFull (2 : Fin 8)) (halfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (2 : Fin 8) (3 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,4). -/
lemma su3LieChartBracket_2_4 :
    lieBracketMat3 (halfGellMannFull (2 : Fin 8)) (halfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (2 : Fin 8) (4 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,5). -/
lemma su3LieChartBracket_2_5 :
    lieBracketMat3 (halfGellMannFull (2 : Fin 8)) (halfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (2 : Fin 8) (5 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,6). -/
lemma su3LieChartBracket_2_6 :
    lieBracketMat3 (halfGellMannFull (2 : Fin 8)) (halfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (2 : Fin 8) (6 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,7). -/
lemma su3LieChartBracket_2_7 :
    lieBracketMat3 (halfGellMannFull (2 : Fin 8)) (halfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (2 : Fin 8) (7 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,0). -/
lemma su3LieChartBracket_3_0 :
    lieBracketMat3 (halfGellMannFull (3 : Fin 8)) (halfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (3 : Fin 8) (0 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,1). -/
lemma su3LieChartBracket_3_1 :
    lieBracketMat3 (halfGellMannFull (3 : Fin 8)) (halfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (3 : Fin 8) (1 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,2). -/
lemma su3LieChartBracket_3_2 :
    lieBracketMat3 (halfGellMannFull (3 : Fin 8)) (halfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (3 : Fin 8) (2 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (3,3). -/
lemma su3LieChartBracket_3_3 :
    lieBracketMat3 (halfGellMannFull (3 : Fin 8)) (halfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (3 : Fin 8) (3 : Fin 8) c : ℂ) • halfGellMannFull c := by
  rw [halfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat3, smul_zero]

/-- Off-diagonal case (3,4). -/
lemma su3LieChartBracket_3_4 :
    lieBracketMat3 (halfGellMannFull (3 : Fin 8)) (halfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (3 : Fin 8) (4 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,5). -/
lemma su3LieChartBracket_3_5 :
    lieBracketMat3 (halfGellMannFull (3 : Fin 8)) (halfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (3 : Fin 8) (5 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,6). -/
lemma su3LieChartBracket_3_6 :
    lieBracketMat3 (halfGellMannFull (3 : Fin 8)) (halfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (3 : Fin 8) (6 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,7). -/
lemma su3LieChartBracket_3_7 :
    lieBracketMat3 (halfGellMannFull (3 : Fin 8)) (halfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (3 : Fin 8) (7 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,0). -/
lemma su3LieChartBracket_4_0 :
    lieBracketMat3 (halfGellMannFull (4 : Fin 8)) (halfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (4 : Fin 8) (0 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,1). -/
lemma su3LieChartBracket_4_1 :
    lieBracketMat3 (halfGellMannFull (4 : Fin 8)) (halfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (4 : Fin 8) (1 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,2). -/
lemma su3LieChartBracket_4_2 :
    lieBracketMat3 (halfGellMannFull (4 : Fin 8)) (halfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (4 : Fin 8) (2 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,3). -/
lemma su3LieChartBracket_4_3 :
    lieBracketMat3 (halfGellMannFull (4 : Fin 8)) (halfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (4 : Fin 8) (3 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (4,4). -/
lemma su3LieChartBracket_4_4 :
    lieBracketMat3 (halfGellMannFull (4 : Fin 8)) (halfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (4 : Fin 8) (4 : Fin 8) c : ℂ) • halfGellMannFull c := by
  rw [halfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat3, smul_zero]

/-- Off-diagonal case (4,5). -/
lemma su3LieChartBracket_4_5 :
    lieBracketMat3 (halfGellMannFull (4 : Fin 8)) (halfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (4 : Fin 8) (5 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,6). -/
lemma su3LieChartBracket_4_6 :
    lieBracketMat3 (halfGellMannFull (4 : Fin 8)) (halfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (4 : Fin 8) (6 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,7). -/
lemma su3LieChartBracket_4_7 :
    lieBracketMat3 (halfGellMannFull (4 : Fin 8)) (halfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (4 : Fin 8) (7 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,0). -/
lemma su3LieChartBracket_5_0 :
    lieBracketMat3 (halfGellMannFull (5 : Fin 8)) (halfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (5 : Fin 8) (0 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,1). -/
lemma su3LieChartBracket_5_1 :
    lieBracketMat3 (halfGellMannFull (5 : Fin 8)) (halfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (5 : Fin 8) (1 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,2). -/
lemma su3LieChartBracket_5_2 :
    lieBracketMat3 (halfGellMannFull (5 : Fin 8)) (halfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (5 : Fin 8) (2 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,3). -/
lemma su3LieChartBracket_5_3 :
    lieBracketMat3 (halfGellMannFull (5 : Fin 8)) (halfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (5 : Fin 8) (3 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,4). -/
lemma su3LieChartBracket_5_4 :
    lieBracketMat3 (halfGellMannFull (5 : Fin 8)) (halfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (5 : Fin 8) (4 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (5,5). -/
lemma su3LieChartBracket_5_5 :
    lieBracketMat3 (halfGellMannFull (5 : Fin 8)) (halfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (5 : Fin 8) (5 : Fin 8) c : ℂ) • halfGellMannFull c := by
  rw [halfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat3, smul_zero]

/-- Off-diagonal case (5,6). -/
lemma su3LieChartBracket_5_6 :
    lieBracketMat3 (halfGellMannFull (5 : Fin 8)) (halfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (5 : Fin 8) (6 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,7). -/
lemma su3LieChartBracket_5_7 :
    lieBracketMat3 (halfGellMannFull (5 : Fin 8)) (halfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (5 : Fin 8) (7 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,0). -/
lemma su3LieChartBracket_6_0 :
    lieBracketMat3 (halfGellMannFull (6 : Fin 8)) (halfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (6 : Fin 8) (0 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,1). -/
lemma su3LieChartBracket_6_1 :
    lieBracketMat3 (halfGellMannFull (6 : Fin 8)) (halfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (6 : Fin 8) (1 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,2). -/
lemma su3LieChartBracket_6_2 :
    lieBracketMat3 (halfGellMannFull (6 : Fin 8)) (halfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (6 : Fin 8) (2 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,3). -/
lemma su3LieChartBracket_6_3 :
    lieBracketMat3 (halfGellMannFull (6 : Fin 8)) (halfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (6 : Fin 8) (3 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,4). -/
lemma su3LieChartBracket_6_4 :
    lieBracketMat3 (halfGellMannFull (6 : Fin 8)) (halfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (6 : Fin 8) (4 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,5). -/
lemma su3LieChartBracket_6_5 :
    lieBracketMat3 (halfGellMannFull (6 : Fin 8)) (halfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (6 : Fin 8) (5 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (6,6). -/
lemma su3LieChartBracket_6_6 :
    lieBracketMat3 (halfGellMannFull (6 : Fin 8)) (halfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (6 : Fin 8) (6 : Fin 8) c : ℂ) • halfGellMannFull c := by
  rw [halfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat3, smul_zero]

/-- Off-diagonal case (6,7). -/
lemma su3LieChartBracket_6_7 :
    lieBracketMat3 (halfGellMannFull (6 : Fin 8)) (halfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (6 : Fin 8) (7 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,0). -/
lemma su3LieChartBracket_7_0 :
    lieBracketMat3 (halfGellMannFull (7 : Fin 8)) (halfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (7 : Fin 8) (0 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,1). -/
lemma su3LieChartBracket_7_1 :
    lieBracketMat3 (halfGellMannFull (7 : Fin 8)) (halfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (7 : Fin 8) (1 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,2). -/
lemma su3LieChartBracket_7_2 :
    lieBracketMat3 (halfGellMannFull (7 : Fin 8)) (halfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (7 : Fin 8) (2 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,3). -/
lemma su3LieChartBracket_7_3 :
    lieBracketMat3 (halfGellMannFull (7 : Fin 8)) (halfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (7 : Fin 8) (3 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,4). -/
lemma su3LieChartBracket_7_4 :
    lieBracketMat3 (halfGellMannFull (7 : Fin 8)) (halfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (7 : Fin 8) (4 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,5). -/
lemma su3LieChartBracket_7_5 :
    lieBracketMat3 (halfGellMannFull (7 : Fin 8)) (halfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (7 : Fin 8) (5 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,6). -/
lemma su3LieChartBracket_7_6 :
    lieBracketMat3 (halfGellMannFull (7 : Fin 8)) (halfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (7 : Fin 8) (6 : Fin 8) c : ℂ) • halfGellMannFull c := by
  unfold lieBracketMat3
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      halfGellMannFull, gellMannFull, gellMann1, gellMann2, gellMann3, gellMann4, gellMann5, gellMann6, gellMann7, gellMann8]
    try simp [su3fStructure, su3PermSign, min3, mid3, max3, su3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (7,7). -/
lemma su3LieChartBracket_7_7 :
    lieBracketMat3 (halfGellMannFull (7 : Fin 8)) (halfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (su3fStructure (7 : Fin 8) (7 : Fin 8) c : ℂ) • halfGellMannFull c := by
  rw [halfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat3, smul_zero]


/-- Global chart Lie law for half–Gell–Mann generators (all 64 ordered pairs). -/
theorem halfGellMannFull_lieBracket_eq_I_smul_f_sum (a b : Fin 8) :
    lieBracketMat3 (halfGellMannFull a) (halfGellMannFull b) =
      Complex.I • ∑ c : Fin 8, (su3fStructure a b c : ℂ) • halfGellMannFull c := by
  fin_cases a <;> fin_cases b
  · exact su3LieChartBracket_0_0
  · exact su3LieChartBracket_0_1
  · exact su3LieChartBracket_0_2
  · exact su3LieChartBracket_0_3
  · exact su3LieChartBracket_0_4
  · exact su3LieChartBracket_0_5
  · exact su3LieChartBracket_0_6
  · exact su3LieChartBracket_0_7
  · exact su3LieChartBracket_1_0
  · exact su3LieChartBracket_1_1
  · exact su3LieChartBracket_1_2
  · exact su3LieChartBracket_1_3
  · exact su3LieChartBracket_1_4
  · exact su3LieChartBracket_1_5
  · exact su3LieChartBracket_1_6
  · exact su3LieChartBracket_1_7
  · exact su3LieChartBracket_2_0
  · exact su3LieChartBracket_2_1
  · exact su3LieChartBracket_2_2
  · exact su3LieChartBracket_2_3
  · exact su3LieChartBracket_2_4
  · exact su3LieChartBracket_2_5
  · exact su3LieChartBracket_2_6
  · exact su3LieChartBracket_2_7
  · exact su3LieChartBracket_3_0
  · exact su3LieChartBracket_3_1
  · exact su3LieChartBracket_3_2
  · exact su3LieChartBracket_3_3
  · exact su3LieChartBracket_3_4
  · exact su3LieChartBracket_3_5
  · exact su3LieChartBracket_3_6
  · exact su3LieChartBracket_3_7
  · exact su3LieChartBracket_4_0
  · exact su3LieChartBracket_4_1
  · exact su3LieChartBracket_4_2
  · exact su3LieChartBracket_4_3
  · exact su3LieChartBracket_4_4
  · exact su3LieChartBracket_4_5
  · exact su3LieChartBracket_4_6
  · exact su3LieChartBracket_4_7
  · exact su3LieChartBracket_5_0
  · exact su3LieChartBracket_5_1
  · exact su3LieChartBracket_5_2
  · exact su3LieChartBracket_5_3
  · exact su3LieChartBracket_5_4
  · exact su3LieChartBracket_5_5
  · exact su3LieChartBracket_5_6
  · exact su3LieChartBracket_5_7
  · exact su3LieChartBracket_6_0
  · exact su3LieChartBracket_6_1
  · exact su3LieChartBracket_6_2
  · exact su3LieChartBracket_6_3
  · exact su3LieChartBracket_6_4
  · exact su3LieChartBracket_6_5
  · exact su3LieChartBracket_6_6
  · exact su3LieChartBracket_6_7
  · exact su3LieChartBracket_7_0
  · exact su3LieChartBracket_7_1
  · exact su3LieChartBracket_7_2
  · exact su3LieChartBracket_7_3
  · exact su3LieChartBracket_7_4
  · exact su3LieChartBracket_7_5
  · exact su3LieChartBracket_7_6
  · exact su3LieChartBracket_7_7
end -- noncomputable section

end HqivSpine.Algebra.StrongColor
