import Hqiv.Physics.MetaHorizonInsideRatioComputational
import Hqiv.Physics.MetaHorizonTrappedPlanckMass
import Hqiv.QuantumChemistry.AtomElectronicDischarge
import Hqiv.QuantumChemistry.DynamicBindingChart

/-!
# Nuclear curvature drum `m_nuc(A)` from inside-ratio argmin

Python: `hqiv_nuclear_curvature_binding.nucleus_curvature_shell` matches

```text
argmin_{m ∈ [0, referenceM+7]} | R_in(m) − A^{1/3} |
```

with `R_in(m) = metaHorizonTrappedInsideRatio m referenceM`.

**Model spine (2026-06 upgrade):**

* **Semantic `ℝ`:** `nucleusCurvatureShellArgminReal` uses `metaHorizonTrappedInsideRatio`.
* **Planck factor:** proved linear `(m+1)/(m_ref+1)` — see
  `metaHorizonTrappedInsideRatio_eq_curvature_times_index` and
  `trappedPlanckCumulativeBudget_eq_four_mul`.
* **Computational `ℚ`:** `metaHorizonInsideRatioComputational` is derived from
  `shellShapeComputational` + exact shell-index ratio (not a pasted ratio table).
* **Cube-root targets:** rational witnesses for `A^{1/3}` at stable-isotope mass
  numbers (regenerated by `scripts/hqiv_meta_horizon_inside_ratio_witness.py`).
-/

namespace Hqiv.QuantumChemistry

open Hqiv.Physics

/-! ## Semantic `ℝ` argmin (Python mirror) -/

/-- Target inside-ratio scale `A^{1/3}` on the trapped-inside chart. -/
noncomputable def nucleusCurvatureInsideTarget (A : ℕ) : ℝ :=
  (A : ℝ) ^ (1 / 3 : ℝ)

/-- Absolute mismatch `|R_in(m) − A^{1/3}|`. -/
noncomputable def nucleusCurvatureShellError (m A : ℕ) : ℝ :=
  abs (metaHorizonTrappedInsideRatio m referenceM - nucleusCurvatureInsideTarget A)

/-- Argmin shell on `m ∈ {0, …, referenceM+7}` (semantic primary). -/
noncomputable def nucleusCurvatureShellArgminReal (A : ℕ) : ℕ :=
  if A ≤ 1 then referenceM
  else
    (List.range (referenceM + 8)).foldl
      (fun best m =>
        if nucleusCurvatureShellError m A < nucleusCurvatureShellError best A then m else best)
      referenceM

/-! ## Computable `ℚ` spine (formula-derived) -/

def absQ (x : ℚ) : ℚ :=
  if x < 0 then -x else x

/-- Rational witness for isotope target `A^{1/3}` (audit / stable-chart mass numbers). -/
def nucleusCurvatureTargetWitness : ℕ → ℚ
  | 0 | 1 => 1
  | 4 => 1308122894 / 824065785
  | 7 => 1630355525 / 852281326
  | 9 => 1389136703 / 667827271
  | 11 => 2029981967 / 912769847
  | 12 => 1925715986 / 841133933
  | 14 => 830684535 / 344662034
  | 16 => 1473962997 / 584942603
  | 19 => 582892095 / 218442413
  | 23 => 229712960 / 80774861
  | 35 => 370817056 / 113362745
  | 56 => 1630355525 / 426140663
  | _ => 1

def nucleusCurvatureShellErrorComputational (m A : ℕ) : ℚ :=
  absQ (metaHorizonInsideRatioComputational m referenceM - nucleusCurvatureTargetWitness A)

/-- Computable argmin on the formula-derived inside-ratio ladder. -/
def nucleusCurvatureShellArgmin (A : ℕ) : ℕ :=
  if A ≤ 1 then referenceM
  else
    (List.range (referenceM + 8)).foldl
      (fun best m =>
        if nucleusCurvatureShellErrorComputational m A <
            nucleusCurvatureShellErrorComputational best A then
          m
        else best)
      referenceM

/-- Nuclear drum used by atom mass readouts (computable audit spine). -/
noncomputable def nucleusCurvatureShell (A : ℕ) : ℕ := nucleusCurvatureShellArgmin A

theorem nucleusCurvatureShell_eq_argmin (A : ℕ) :
    nucleusCurvatureShell A = nucleusCurvatureShellArgmin A := rfl

theorem nucleusCurvatureShell_hydrogen : nucleusCurvatureShell 1 = referenceM := rfl

theorem nucleusCurvatureShellArgmin_helium4 : nucleusCurvatureShellArgmin 4 = 6 := by native_decide

theorem nucleusCurvatureShellArgmin_carbon12 : nucleusCurvatureShellArgmin 12 = 8 := by native_decide

theorem nucleusCurvatureShellArgmin_oxygen16 : nucleusCurvatureShellArgmin 16 = 8 := by native_decide

theorem nucleusCurvatureShellArgmin_sodium23 : nucleusCurvatureShellArgmin 23 = 9 := by native_decide

theorem nucleusCurvatureShellArgmin_iron56 : nucleusCurvatureShellArgmin 56 = 11 := by native_decide

theorem nucleusCurvatureShell_helium4 : nucleusCurvatureShell 4 = 6 := by
  rw [nucleusCurvatureShell_eq_argmin, nucleusCurvatureShellArgmin_helium4]

theorem nucleusCurvatureShell_carbon12 : nucleusCurvatureShell 12 = 8 := by
  rw [nucleusCurvatureShell_eq_argmin, nucleusCurvatureShellArgmin_carbon12]

theorem nucleusCurvatureShell_iron56 : nucleusCurvatureShell 56 = 11 := by
  rw [nucleusCurvatureShell_eq_argmin, nucleusCurvatureShellArgmin_iron56]

/-- Stable-isotope chart pin (derived from stability network; reconciled on benchmark rows). -/
def nucleusCurvatureShellChart (A : ℕ) : ℕ :=
  match A with
  | 0 | 1 => referenceM
  | 4 => 6
  | 7 => 7
  | 9 => 7
  | 11 => 7
  | 12 => 8
  | 14 => 8
  | 16 => 8
  | 19 => 8
  | 23 => 9
  | 35 => 10
  | 56 => 11
  | _ => referenceM

theorem nucleusCurvatureShellChart_eq_argmin_helium4 :
    nucleusCurvatureShellChart 4 = nucleusCurvatureShellArgmin 4 := by
  rw [nucleusCurvatureShellArgmin_helium4]
  decide

theorem nucleusCurvatureShellChart_eq_argmin_carbon12 :
    nucleusCurvatureShellChart 12 = nucleusCurvatureShellArgmin 12 := by
  rw [nucleusCurvatureShellArgmin_carbon12]
  decide

theorem stableMassNumberForCharge_nucleusCurvatureShell (Z : ℕ) :
    nucleusCurvatureShell (stableMassNumberForCharge Z) = nucleusCurvatureShellArgmin
      (stableMassNumberForCharge Z) :=
  nucleusCurvatureShell_eq_argmin (stableMassNumberForCharge Z)

/-- Nuclear cluster mass [MeV] at argmin drum `m_nuc(A)`. -/
noncomputable def atomNuclearClusterMassMeV (Z : ℕ) (c : ℝ := 1) : ℝ :=
  if Z = 0 then 0
  else
    let A := stableMassNumberForCharge Z
    let mNuc := nucleusCurvatureShell A
    clusterMassMeV mNuc A c

end Hqiv.QuantumChemistry
