import Hqiv.QuantumChemistry.FiniteSiteQuantumChemistry
import Hqiv.QuantumMechanics.Schrodinger

/-!
# Atomic outputs and excitation states (generic scaffold)

General Lean scaffold for atomic outputs at arbitrary atomic number `Z`, electron
count `e`, and excitation profile on shell indices.

This module stays purely on first-principles ladder quantities:

- site-energy outputs (`latticeFullModeEnergy`),
- mode-budget outputs (`accessibleModeBudgetUpToShell`),
- time-angle lifted budget outputs (`accessibleModeBudgetUpToPhiTime`).
-/

namespace Hqiv.QuantumChemistry

open scoped BigOperators
open Finset
open Hqiv

/-- Generic atom shell assignment (`e` electrons) with atomic-number metadata `Z`. -/
structure AtomicShellSpec where
  Z : ℕ
  e : ℕ
  shell : Fin e → ℕ

/-- Convert a generic atomic shell assignment to the canonical finite-site chemistry spec. -/
def AtomicShellSpec.toFiniteSite (a : AtomicShellSpec) : FiniteSiteChemistrySpec a.e where
  shell := a.shell

/-- Excitation profile: shell increments per electron index. -/
abbrev ExcitationProfile (e : ℕ) := Fin e → ℕ

/-- Excited atom generated by adding shell increments electron-wise. -/
def AtomicShellSpec.excited (a : AtomicShellSpec) (δ : ExcitationProfile a.e) : AtomicShellSpec where
  Z := a.Z
  e := a.e
  shell := fun i => a.shell i + δ i

/-- Single-electron excitation profile (+1 on selected index, 0 elsewhere). -/
def singleExcitationProfile {e : ℕ} (i₀ : Fin e) : ExcitationProfile e :=
  fun i => if i = i₀ then 1 else 0

/-- Atomic site-energy output (ground or excited, depending on shell map). -/
noncomputable def atomSiteEnergyOutput (a : AtomicShellSpec) : ℝ :=
  siteEnergyTrace a.toFiniteSite

/-- Atomic mode-budget output on shell indices. -/
noncomputable def atomModeBudgetOutput (a : AtomicShellSpec) : ℝ :=
  siteModeBudgetTrace a.toFiniteSite

/-- Atomic mode-budget output on lifted time-angle shell indices. -/
noncomputable def atomModeBudgetOutputFromPhiTime (a : AtomicShellSpec) (t : ℝ) : ℝ :=
  siteModeBudgetTraceFromPhiTime a.toFiniteSite t

theorem atomSiteEnergyOutput_nonneg (a : AtomicShellSpec) :
    0 ≤ atomSiteEnergyOutput a :=
  siteEnergyTrace_nonneg a.toFiniteSite

theorem atomModeBudgetOutput_nonneg (a : AtomicShellSpec) :
    0 ≤ atomModeBudgetOutput a :=
  siteModeBudgetTrace_nonneg a.toFiniteSite

theorem atomModeBudgetOutputFromPhiTime_unit_eq (a : AtomicShellSpec) :
    atomModeBudgetOutputFromPhiTime a 1 = atomModeBudgetOutput a :=
  siteModeBudgetTraceFromPhiTime_unit_eq_siteModeBudgetTrace a.toFiniteSite

theorem atomSiteEnergyOutput_eq_sum (a : AtomicShellSpec) :
    atomSiteEnergyOutput a = ∑ i : Fin a.e, Hqiv.ProteinResearch.latticeFullModeEnergy (a.shell i) := by
  simpa [atomSiteEnergyOutput, siteEnergyTrace, AtomicShellSpec.toFiniteSite] using
    Hqiv.ProteinResearch.trace_atomSiteEnergyMatrix a.shell

theorem atomModeBudgetOutput_eq_sum (a : AtomicShellSpec) :
    atomModeBudgetOutput a = ∑ i : Fin a.e, Hqiv.Physics.accessibleModeBudgetUpToShell (a.shell i) := by
  rfl

/-- Excitation delta on site-energy channel as an exact finite sum difference. -/
noncomputable def excitationSiteEnergyDelta (a : AtomicShellSpec) (δ : ExcitationProfile a.e) : ℝ :=
  atomSiteEnergyOutput (a.excited δ) - atomSiteEnergyOutput a

theorem excitationSiteEnergyDelta_eq_sum (a : AtomicShellSpec) (δ : ExcitationProfile a.e) :
    excitationSiteEnergyDelta a δ =
      ∑ i : Fin a.e,
        (Hqiv.ProteinResearch.latticeFullModeEnergy (a.shell i + δ i) -
          Hqiv.ProteinResearch.latticeFullModeEnergy (a.shell i)) := by
  unfold excitationSiteEnergyDelta
  rw [atomSiteEnergyOutput_eq_sum, atomSiteEnergyOutput_eq_sum]
  simp [AtomicShellSpec.excited, sub_eq_add_neg, Finset.sum_add_distrib]

/-- Excitation delta on mode-budget channel as an exact finite sum difference. -/
noncomputable def excitationModeBudgetDelta (a : AtomicShellSpec) (δ : ExcitationProfile a.e) : ℝ :=
  atomModeBudgetOutput (a.excited δ) - atomModeBudgetOutput a

theorem excitationModeBudgetDelta_eq_sum (a : AtomicShellSpec) (δ : ExcitationProfile a.e) :
    excitationModeBudgetDelta a δ =
      ∑ i : Fin a.e,
        (Hqiv.Physics.accessibleModeBudgetUpToShell (a.shell i + δ i) -
          Hqiv.Physics.accessibleModeBudgetUpToShell (a.shell i)) := by
  unfold excitationModeBudgetDelta
  rw [atomModeBudgetOutput_eq_sum, atomModeBudgetOutput_eq_sum]
  simp [AtomicShellSpec.excited, sub_eq_add_neg, Finset.sum_add_distrib]

/-- Single-electron excitation state. -/
def AtomicShellSpec.singleExcited (a : AtomicShellSpec) (i₀ : Fin a.e) : AtomicShellSpec :=
  a.excited (singleExcitationProfile i₀)

theorem singleExcited_shell_eq (a : AtomicShellSpec) (i₀ i : Fin a.e) :
    (a.singleExcited i₀).shell i = a.shell i + (if i = i₀ then 1 else 0) := by
  rfl

/-- Electron configuration for an `e`-electron atom. -/
abbrev ElectronConfiguration (e : ℕ) := Fin e → Position

/-- Product orbital wavefunction from shell-resolved hydrogenic orbitals.
This is the canonical separable scaffold before antisymmetrization/correlation layers. -/
noncomputable def atomProductWavefunction (a : AtomicShellSpec) (μ : ℝ) :
    ElectronConfiguration a.e → ℂ :=
  fun X => ∏ i : Fin a.e, hydrogenGroundStateOfShell (a.shell i) a.Z μ (X i)

/-- Product orbital for an excited atom specified by shell increments `δ`. -/
noncomputable def atomProductWavefunctionExcited (a : AtomicShellSpec) (δ : ExcitationProfile a.e) (μ : ℝ) :
    ElectronConfiguration a.e → ℂ :=
  atomProductWavefunction (a.excited δ) μ

theorem atomProductWavefunctionExcited_def (a : AtomicShellSpec) (δ : ExcitationProfile a.e) (μ : ℝ) :
    atomProductWavefunctionExcited a δ μ = atomProductWavefunction (a.excited δ) μ :=
  rfl

theorem atomProductWavefunctionExcited_single_def (a : AtomicShellSpec) (i₀ : Fin a.e) (μ : ℝ) :
    atomProductWavefunction (a.singleExcited i₀) μ =
      atomProductWavefunctionExcited a (singleExcitationProfile i₀) μ := by
  rfl

/-- Pointwise formula for the product-wavefunction under an arbitrary excitation profile. -/
theorem atomProductWavefunctionExcited_pointwise (a : AtomicShellSpec) (δ : ExcitationProfile a.e)
    (μ : ℝ) (X : ElectronConfiguration a.e) :
    atomProductWavefunctionExcited a δ μ X =
      ∏ i : Fin a.e, hydrogenGroundStateOfShell (a.shell i + δ i) a.Z μ (X i) := by
  unfold atomProductWavefunctionExcited atomProductWavefunction AtomicShellSpec.excited
  simp

end Hqiv.QuantumChemistry
