import Hqiv.Algebra.CliffordCl06SixDimension
import Hqiv.Algebra.CliffordMinimalIdeal

/-!
# Left ideals and idempotents in abstract `Cl(0,6)` (`CliffordCl06Six`)

`CliffordCl06Six` is a **64**-dimensional real algebra (`Hqiv.Algebra.cliffordCl06Six_finrank`).  This
file records the basic **ring-theoretic** packaging used in Furey-style discussions:

* **Left ideals** as `Submodule CliffordCl06Six CliffordCl06Six` (scalar action `r • x = r * x`).
* The **principal** left ideal generated by `1` is the whole algebra (`leftIdealGenerated_one_eq_top`).
* **Existence** of a nontrivial idempotent (`1`).
* **Unital ideals:** `cliffordCl06Six_leftIdeal_eq_top_of_one_mem` — any left ideal containing `1` is `⊤`.
* **Minimal `⊤` (conditional):** `cliffordCl06Six_top_isMinimalLeftIdeal` — if `CliffordCl06Six` is a simple
  left module over itself, then `⊤` is `IsMinimalLeftIdeal` (same pattern as `Cl(1) ≅ ℂ`).

What is **not** proved here (and remains representation-theoretic) is a Mathlib certificate that
`CliffordCl06Six` is abstractly isomorphic to `Mat₈(ℝ)` and hence that nonzero primitive idempotents
generate **8**-dimensional minimal left ideals — that step is exactly where a faithful `8`-dimensional
real spinor representation must enter (compare `Hqiv.Algebra.OctonionSpinorCarrier`, the bridge
file `Hqiv.Algebra.CliffordCl06SixSpinorBridge`, and the **conditional** surjectivity layer
`Hqiv.Algebra.CliffordCl06SixStandardSpinorMatLiftSurjective`).
-/

namespace Hqiv.Algebra

open Submodule

abbrev CliffordLeftIdeal := Submodule CliffordCl06Six CliffordCl06Six

/-- Left ideal generated by `e : CliffordCl06Six` (all left multiples `a * e`). -/
noncomputable def cliffordCl06SixLeftIdealGenerated (e : CliffordCl06Six) : CliffordLeftIdeal :=
  span CliffordCl06Six (Set.range fun a : CliffordCl06Six => a * e)

theorem mem_cliffordCl06SixLeftIdealGenerated {e x : CliffordCl06Six} :
    x ∈ cliffordCl06SixLeftIdealGenerated e ↔
      x ∈ span CliffordCl06Six (Set.range fun a : CliffordCl06Six => a * e) :=
  Iff.rfl

theorem cliffordCl06SixLeftIdealGenerated_one_eq_top :
    cliffordCl06SixLeftIdealGenerated (1 : CliffordCl06Six) = ⊤ := by
  refine eq_top_iff.mpr fun x _ => ?_
  simp only [cliffordCl06SixLeftIdealGenerated]
  exact Submodule.subset_span (show x ∈ Set.range (· * (1 : CliffordCl06Six)) from ⟨x, mul_one x⟩)

theorem exists_nonzero_idempotent_cliffordCl06Six :
    ∃ e : CliffordCl06Six, e * e = e ∧ e ≠ 0 :=
  ⟨1, mul_one _, one_ne_zero⟩

theorem cliffordCl06SixLeftIdealGenerated_le_top (e : CliffordCl06Six) :
    cliffordCl06SixLeftIdealGenerated e ≤ ⊤ :=
  le_top

/-- Any left ideal containing `1` is the whole algebra (`r • 1 = r` for `r : CliffordCl06Six`). -/
theorem cliffordCl06Six_leftIdeal_eq_top_of_one_mem {I : CliffordLeftIdeal}
    (h : (1 : CliffordCl06Six) ∈ I) : I = ⊤ := by
  rw [Submodule.eq_top_iff']
  intro x
  simpa only [smul_eq_mul, mul_one] using Submodule.smul_mem I x h

/-- If `CliffordCl06Six` is simple as a left module over itself, then `⊤` is a minimal nonzero
left ideal (same pattern as `cliffordOneDim_top_isMinimalLeftIdeal` for the division ring `Cl(1)`).
-/
theorem cliffordCl06Six_top_isMinimalLeftIdeal
    [IsSimpleModule CliffordCl06Six CliffordCl06Six] [Nontrivial CliffordCl06Six] :
    IsMinimalLeftIdeal (⊤ : CliffordLeftIdeal) :=
  IsMinimalLeftIdeal.top_of_isSimpleModule (R := CliffordCl06Six)

end Hqiv.Algebra
