import Mathlib.Algebra.Lie.SkewAdjoint
import Mathlib.Data.Fintype.BigOperators
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import Hqiv.Algebra.G2Embedding
import Hqiv.Algebra.PhaseLiftDelta

open Matrix

namespace Hqiv.Algebra

abbrev GaugeMatrix := Matrix (Fin 8) (Fin 8) ℝ

set_option maxHeartbeats 800000000

/-- Upper-triangle index in lexicographic order `(0,1), (0,2), ... , (6,7)`. -/
def upperTriangleIdx (p : Fin 28) : Fin 8 × Fin 8 :=
  if p.val = 0 then ((0 : Fin 8), (1 : Fin 8))
  else if p.val = 1 then ((0 : Fin 8), (2 : Fin 8))
  else if p.val = 2 then ((0 : Fin 8), (3 : Fin 8))
  else if p.val = 3 then ((0 : Fin 8), (4 : Fin 8))
  else if p.val = 4 then ((0 : Fin 8), (5 : Fin 8))
  else if p.val = 5 then ((0 : Fin 8), (6 : Fin 8))
  else if p.val = 6 then ((0 : Fin 8), (7 : Fin 8))
  else if p.val = 7 then ((1 : Fin 8), (2 : Fin 8))
  else if p.val = 8 then ((1 : Fin 8), (3 : Fin 8))
  else if p.val = 9 then ((1 : Fin 8), (4 : Fin 8))
  else if p.val = 10 then ((1 : Fin 8), (5 : Fin 8))
  else if p.val = 11 then ((1 : Fin 8), (6 : Fin 8))
  else if p.val = 12 then ((1 : Fin 8), (7 : Fin 8))
  else if p.val = 13 then ((2 : Fin 8), (3 : Fin 8))
  else if p.val = 14 then ((2 : Fin 8), (4 : Fin 8))
  else if p.val = 15 then ((2 : Fin 8), (5 : Fin 8))
  else if p.val = 16 then ((2 : Fin 8), (6 : Fin 8))
  else if p.val = 17 then ((2 : Fin 8), (7 : Fin 8))
  else if p.val = 18 then ((3 : Fin 8), (4 : Fin 8))
  else if p.val = 19 then ((3 : Fin 8), (5 : Fin 8))
  else if p.val = 20 then ((3 : Fin 8), (6 : Fin 8))
  else if p.val = 21 then ((3 : Fin 8), (7 : Fin 8))
  else if p.val = 22 then ((4 : Fin 8), (5 : Fin 8))
  else if p.val = 23 then ((4 : Fin 8), (6 : Fin 8))
  else if p.val = 24 then ((4 : Fin 8), (7 : Fin 8))
  else if p.val = 25 then ((5 : Fin 8), (6 : Fin 8))
  else if p.val = 26 then ((5 : Fin 8), (7 : Fin 8))
  else ((6 : Fin 8), (7 : Fin 8))

/-- Extract the upper-triangle coordinate matching `upperTriangleIdx`. -/
def coordVec (M : GaugeMatrix) (p : Fin 28) : ℝ :=
  M (upperTriangleIdx p).1 (upperTriangleIdx p).2

/-- The explicit G₂ seed set inside the 8×8 matrix carrier. -/
def G2Generators : Set GaugeMatrix :=
  Set.range g2Generator

/-- The physical HQIV generating set: the 14 G₂ derivation generators together with `Δ`. -/
def G2UnionDelta : Set GaugeMatrix :=
  G2Generators ∪ {Hqiv.phaseLiftDelta}

/-- The standard Euclidean `so(8)` model inside 8×8 matrices. -/
def so8LieSubalgebra : LieSubalgebra ℝ GaugeMatrix :=
  skewAdjointMatricesLieSubalgebra (1 : GaugeMatrix)

lemma mem_so8LieSubalgebra_iff (M : GaugeMatrix) :
    M ∈ so8LieSubalgebra ↔ Mᵀ = -M := by
  rw [so8LieSubalgebra, mem_skewAdjointMatricesLieSubalgebra, mem_skewAdjointMatricesSubmodule]
  simp [Matrix.IsSkewAdjoint, Matrix.IsAdjointPair]

theorem g2Generator_mem_so8LieSubalgebra (k : Fin 14) :
    g2Generator k ∈ so8LieSubalgebra := by
  rw [mem_so8LieSubalgebra_iff]
  exact eq_neg_iff_add_eq_zero.mpr (by simpa [add_comm] using g2_in_so8 k)

theorem phaseLiftDelta_mem_so8LieSubalgebra :
    Hqiv.phaseLiftDelta ∈ so8LieSubalgebra := by
  rw [mem_so8LieSubalgebra_iff]
  exact eq_neg_iff_add_eq_zero.mpr (by simpa [add_comm] using phaseLiftDelta_antisymm)

theorem G2UnionDelta_subset_so8LieSubalgebra :
    G2UnionDelta ⊆ so8LieSubalgebra := by
  intro M hM
  rcases hM with (⟨k, rfl⟩ | rfl)
  · exact g2Generator_mem_so8LieSubalgebra k
  · exact phaseLiftDelta_mem_so8LieSubalgebra

/-- The Lie subalgebra generated by the physical seed set `G₂ ∪ {Δ}`. -/
def g2DeltaGeneratedLie : LieSubalgebra ℝ GaugeMatrix :=
  LieSubalgebra.lieSpan ℝ GaugeMatrix G2UnionDelta

theorem G2UnionDelta_subset_g2DeltaGeneratedLie :
    G2UnionDelta ⊆ g2DeltaGeneratedLie := by
  simpa [g2DeltaGeneratedLie] using
    (LieSubalgebra.subset_lieSpan (R := ℝ) (L := GaugeMatrix) (s := G2UnionDelta))

theorem g2Generator_mem_g2DeltaGeneratedLie (k : Fin 14) :
    g2Generator k ∈ g2DeltaGeneratedLie := by
  exact G2UnionDelta_subset_g2DeltaGeneratedLie (Or.inl ⟨k, rfl⟩)

theorem phaseLiftDelta_mem_g2DeltaGeneratedLie :
    Hqiv.phaseLiftDelta ∈ g2DeltaGeneratedLie := by
  exact G2UnionDelta_subset_g2DeltaGeneratedLie (Or.inr rfl)

theorem span_G2UnionDelta_le_g2DeltaGeneratedLie :
    Submodule.span ℝ G2UnionDelta ≤ (g2DeltaGeneratedLie : Submodule ℝ GaugeMatrix) := by
  simpa [g2DeltaGeneratedLie] using
    (LieSubalgebra.submodule_span_le_lieSpan (R := ℝ) (L := GaugeMatrix) (s := G2UnionDelta))

theorem g2DeltaGeneratedLie_le_iff {K : LieSubalgebra ℝ GaugeMatrix} :
    g2DeltaGeneratedLie ≤ K ↔ G2UnionDelta ⊆ K := by
  simpa [g2DeltaGeneratedLie] using
    (LieSubalgebra.lieSpan_le (R := ℝ) (L := GaugeMatrix) (s := G2UnionDelta) (K := K))

theorem g2DeltaGeneratedLie_le_so8LieSubalgebra :
    g2DeltaGeneratedLie ≤ so8LieSubalgebra := by
  rw [g2DeltaGeneratedLie_le_iff]
  exact G2UnionDelta_subset_so8LieSubalgebra

/-- The 15 physical seeds: the 14 `G₂` generators plus `Δ`. -/
def g2DeltaSeed (idx : Fin 15) : GaugeMatrix :=
  match idx.val with
  | 0 => g2Generator 0
  | 1 => g2Generator 1
  | 2 => g2Generator 2
  | 3 => g2Generator 3
  | 4 => g2Generator 4
  | 5 => g2Generator 5
  | 6 => g2Generator 6
  | 7 => g2Generator 7
  | 8 => g2Generator 8
  | 9 => g2Generator 9
  | 10 => g2Generator 10
  | 11 => g2Generator 11
  | 12 => g2Generator 12
  | 13 => g2Generator 13
  | 14 => Hqiv.phaseLiftDelta
  | _ => Hqiv.phaseLiftDelta

theorem g2DeltaSeed_mem_g2DeltaGeneratedLie (idx : Fin 15) :
    g2DeltaSeed idx ∈ g2DeltaGeneratedLie := by
  fin_cases idx
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 0
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 1
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 2
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 3
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 4
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 5
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 6
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 7
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 8
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 9
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 10
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 11
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 12
  · simpa [g2DeltaSeed] using g2Generator_mem_g2DeltaGeneratedLie 13
  · simpa [g2DeltaSeed] using phaseLiftDelta_mem_g2DeltaGeneratedLie

/--
An explicit 28-element witness family inside the generated Lie algebra.
It consists of 14 seeds (`G₂` except one redundant seed, plus `Δ`) and 14 seed-seed brackets.
-/
def g2DeltaWitness (idx : Fin 28) : GaugeMatrix :=
  match idx.val with
  | 0 => g2DeltaSeed 0
  | 1 => g2DeltaSeed 1
  | 2 => g2DeltaSeed 2
  | 3 => g2DeltaSeed 3
  | 4 => g2DeltaSeed 4
  | 5 => g2DeltaSeed 5
  | 6 => g2DeltaSeed 7
  | 7 => g2DeltaSeed 8
  | 8 => g2DeltaSeed 9
  | 9 => g2DeltaSeed 10
  | 10 => g2DeltaSeed 11
  | 11 => g2DeltaSeed 12
  | 12 => g2DeltaSeed 13
  | 13 => g2DeltaSeed 14
  | 14 => Hqiv.lieBracket (g2DeltaSeed 0) (g2DeltaSeed 3)
  | 15 => Hqiv.lieBracket (g2DeltaSeed 0) (g2DeltaSeed 4)
  | 16 => Hqiv.lieBracket (g2DeltaSeed 0) (g2DeltaSeed 8)
  | 17 => Hqiv.lieBracket (g2DeltaSeed 0) (g2DeltaSeed 9)
  | 18 => Hqiv.lieBracket (g2DeltaSeed 0) (g2DeltaSeed 11)
  | 19 => Hqiv.lieBracket (g2DeltaSeed 0) (g2DeltaSeed 12)
  | 20 => Hqiv.lieBracket (g2DeltaSeed 0) (g2DeltaSeed 13)
  | 21 => Hqiv.lieBracket (g2DeltaSeed 1) (g2DeltaSeed 2)
  | 22 => Hqiv.lieBracket (g2DeltaSeed 1) (g2DeltaSeed 3)
  | 23 => Hqiv.lieBracket (g2DeltaSeed 1) (g2DeltaSeed 4)
  | 24 => Hqiv.lieBracket (g2DeltaSeed 1) (g2DeltaSeed 8)
  | 25 => Hqiv.lieBracket (g2DeltaSeed 1) (g2DeltaSeed 9)
  | 26 => Hqiv.lieBracket (g2DeltaSeed 1) (g2DeltaSeed 13)
  | 27 => Hqiv.lieBracket (g2DeltaSeed 2) (g2DeltaSeed 3)
  | _ => Hqiv.lieBracket (g2DeltaSeed 2) (g2DeltaSeed 3)

theorem g2DeltaWitness_mem_g2DeltaGeneratedLie (idx : Fin 28) :
    g2DeltaWitness idx ∈ g2DeltaGeneratedLie := by
  fin_cases idx
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 0
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 1
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 2
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 3
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 4
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 5
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 7
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 8
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 9
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 10
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 11
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 12
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 13
  · simpa [g2DeltaWitness] using g2DeltaSeed_mem_g2DeltaGeneratedLie 14
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 0)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 3))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 0)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 4))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 0)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 8))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 0)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 9))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 0)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 11))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 0)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 12))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 0)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 13))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 1)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 2))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 1)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 3))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 1)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 4))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 1)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 8))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 1)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 9))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 1)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 13))
  ·
    simpa [g2DeltaWitness] using
      (LieSubalgebra.lie_mem g2DeltaGeneratedLie
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 2)
        (g2DeltaSeed_mem_g2DeltaGeneratedLie 3))

private def witnessCoordRows : Array (Array ℤ) := #[
  #[0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, -1, 0, 0, 0, -4, 0, 0, -4, 0, 0, -8, 0, 0, 0, 0, -4, 0],
  #[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, -4, 0, -4, 0, 0, -4, 0, 4, 0, 0, 0],
  #[0, 0, 0, -1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -4, 0, 0, -4, 0, 2, 0, -2],
  #[0, 0, 2, 0, 0, 0, -1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 0],
  #[0, -2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #[0, 0, 0, 0, 1, -1, 0, 1, 0, 0, -1, 0, 0, 0, 2, 0, 0, -2, 0, -2, 0, 0, 4, 0, -2, 0, 0, 0],
  #[-2, 0, 0, -1, 0, 0, 1, 0, 0, -2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2],
  #[-2, 0, 0, -1, 0, 0, 1, 0, 0, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2],
  #[0, 0, 0, 0, -1, -1, 0, 0, 1, 0, -1, 0, 0, 0, 2, 0, -2, 0, 0, 2, 0, 0, 4, 0, -2, 0, 0, 0],
  #[0, -2, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, 0, 0, 0, -2, 0, 2, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #[0, 0, -2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
  #[0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 4, 0, -2, 0, 2],
  #[0, 0, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0, 0, -1, 0, 0, 0, 4, 0, 2, 0, 0, -4, 0, 0, 0, 0, 0],
  #[0, 2, 0, -1, 0, -1, 0, 1, 0, 0, 0, -1, 0, 0, 0, -2, 0, 2, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  #[0, 0, 0, 0, 1, -1, 0, 0, -1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0],
  #[0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -4, 0, 2, 0, 2],
  #[0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, -2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
  #[0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, -4, 0, 0, -4, 0, 0, 0, 0, 0, -2, 0, -4, 0],
  #[0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 0, -2],
  #[0, 0, 0, 0, -1, 0, 0, 0, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, -2, 0, 0, 0],
  #[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 4, 0],
  #[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 2, 0, -2, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
  #[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, -8, 0, 0, -2, 0, -4, 0],
  #[0, 0, 0, 0, -1, 0, 0, 0, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -4, 0, 0, 0, 0, 0],
  #[0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, -2, 0, 0, 0, -4, 0, 0, -4, 0, 2, 0, 2],
  #[0, 0, 0, -1, 0, 0, 0, 1, 0, 2, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, -2],
  #[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, -2, 0, -2, 0, 0, -4, 0, 2, 0, 0, 0],
  #[0, -2, 0, 1, 0, 1, 0, -1, -1, 0, 0, -1, 0, 0, 0, -2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0]
]

private def g2DeltaWitnessCoordEntryZ (p k : Fin 28) : ℤ :=
  (witnessCoordRows[p.val]!)[k.val]!

private def g2DeltaWitnessCoordMatrixZ : Matrix (Fin 28) (Fin 28) ℤ :=
  Matrix.of (fun p k => g2DeltaWitnessCoordEntryZ p k)

private def g2DeltaWitnessCoordMatrix : Matrix (Fin 28) (Fin 28) ℝ :=
  (Int.castRingHom ℝ).mapMatrix g2DeltaWitnessCoordMatrixZ

theorem g2DeltaWitnessCoordMatrix_eq_coord (p k : Fin 28) :
    g2DeltaWitnessCoordMatrix p k = coordVec (g2DeltaWitness k) p := by
  fin_cases p <;> fin_cases k <;>
    simp only [g2DeltaWitnessCoordMatrix, g2DeltaWitnessCoordMatrixZ, g2DeltaWitnessCoordEntryZ,
      witnessCoordRows, g2DeltaWitness, g2DeltaSeed, coordVec, upperTriangleIdx,
      Matrix.of_apply, RingHom.mapMatrix_apply, Int.cast_zero, Int.cast_one, Int.cast_neg,
      Hqiv.lieBracket, g2Generator, Hqiv.phaseLiftDelta,
      Hqiv.g2_comm_12, Hqiv.g2_comm_13, Hqiv.g2_comm_14, Hqiv.g2_comm_15, Hqiv.g2_comm_16,
      Hqiv.g2_comm_17, Hqiv.g2_comm_23, Hqiv.g2_comm_24, Hqiv.g2_comm_25, Hqiv.g2_comm_26,
      Hqiv.g2_comm_27, Hqiv.g2_comm_34, Hqiv.g2_comm_35, Hqiv.g2_comm_36,
      Hqiv.octonionLeftMul_1, Hqiv.octonionLeftMul_2, Hqiv.octonionLeftMul_3,
      Hqiv.octonionLeftMul_4, Hqiv.octonionLeftMul_5, Hqiv.octonionLeftMul_6,
      Hqiv.octonionLeftMul_7, mul_apply, sub_apply, zero_apply] <;>
    norm_num [Finset.sum_fin_eq_sum_range, Finset.sum_range_succ]

private theorem g2DeltaWitnessCoordMatrixZ_det :
    g2DeltaWitnessCoordMatrixZ.det = (51539607552 : ℤ) := by
  native_decide

private theorem g2DeltaWitnessCoordMatrix_det_ne_zero :
    g2DeltaWitnessCoordMatrix.det ≠ 0 := by
  rw [show g2DeltaWitnessCoordMatrix.det = (51539607552 : ℝ) by
    simpa [g2DeltaWitnessCoordMatrix, g2DeltaWitnessCoordMatrixZ_det] using
      (RingHom.map_det (Int.castRingHom ℝ) g2DeltaWitnessCoordMatrixZ).symm]
  norm_num

private theorem g2DeltaWitness_coordVec_linearCombination (c : Fin 28 → ℝ) (p : Fin 28) :
    coordVec (∑ k : Fin 28, c k • g2DeltaWitness k) p =
      (g2DeltaWitnessCoordMatrix.mulVec c) p := by
  simpa [Matrix.mulVec, dotProduct, coordVec, g2DeltaWitnessCoordMatrix_eq_coord,
    Finset.sum_apply, Pi.smul_apply, mul_comm, mul_left_comm, mul_assoc]

private theorem g2DeltaWitnessCoordMatrix_mulVec_eq_zero_imp_eq_zero (c : Fin 28 → ℝ)
    (h : g2DeltaWitnessCoordMatrix.mulVec c = 0) : c = 0 := by
  have hdet : IsUnit g2DeltaWitnessCoordMatrix.det :=
    isUnit_iff_ne_zero.mpr g2DeltaWitnessCoordMatrix_det_ne_zero
  have key : g2DeltaWitnessCoordMatrix⁻¹.mulVec (g2DeltaWitnessCoordMatrix.mulVec c) = c := by
    rw [← Matrix.mulVec_mulVec g2DeltaWitnessCoordMatrix⁻¹ g2DeltaWitnessCoordMatrix c,
      Matrix.nonsing_inv_mul _ hdet, Matrix.one_mulVec]
  rw [h, Matrix.mulVec_zero] at key
  exact key.symm

theorem g2DeltaWitness_linearIndependent :
    LinearIndependent ℝ g2DeltaWitness := by
  rw [Fintype.linearIndependent_iffₛ]
  intro f g hfg
  intro i
  have hdiff : ∑ k : Fin 28, (f k - g k) • g2DeltaWitness k = 0 := by
    rw [← sub_eq_zero, Finset.sum_sub_distrib]
    simp_rw [sub_smul]
    exact sub_eq_zero.mpr hfg
  have hcoord : g2DeltaWitnessCoordMatrix.mulVec (fun k => f k - g k) = 0 := by
    ext p
    rw [← g2DeltaWitness_coordVec_linearCombination (fun k => f k - g k) p, hdiff]
    simp [coordVec]
  have hzero := g2DeltaWitnessCoordMatrix_mulVec_eq_zero_imp_eq_zero (fun k => f k - g k) hcoord
  exact sub_eq_zero.mp (congr_fun hzero i)

private theorem skew_diag_zero {M : GaugeMatrix} (hM : Mᵀ = -M) (i : Fin 8) : M i i = 0 := by
  have hii := congr_fun (congr_fun hM i) i
  simp only [Matrix.transpose_apply, neg_apply] at hii
  linarith

private theorem skew_entry_swap {M : GaugeMatrix} (hM : Mᵀ = -M) (i j : Fin 8) :
    M i j = -M j i := by
  have hij := congr_fun (congr_fun hM j) i
  simp only [Matrix.transpose_apply, neg_apply] at hij
  exact hij

/-- Pack a skew-adjoint 8×8 matrix by its 28 upper-triangle coordinates. -/
private def so8Pack : so8LieSubalgebra →ₗ[ℝ] (Fin 28 → ℝ) where
  toFun M := fun p => coordVec (M : GaugeMatrix) p
  map_add' M N := by ext p; simp [coordVec]
  map_smul' r M := by ext p; simp [coordVec]

/-- Unpack 28 coordinates into the standard skew-adjoint 8×8 matrix. -/
private def so8Unpack (v : Fin 28 → ℝ) : so8LieSubalgebra :=
  ⟨Matrix.of (fun i j =>
      match i, j with
      | 0, 1 => v 0 | 0, 2 => v 1 | 0, 3 => v 2 | 0, 4 => v 3 | 0, 5 => v 4 | 0, 6 => v 5
      | 0, 7 => v 6
      | 1, 0 => -v 0 | 1, 2 => v 7 | 1, 3 => v 8 | 1, 4 => v 9 | 1, 5 => v 10
      | 1, 6 => v 11 | 1, 7 => v 12
      | 2, 0 => -v 1 | 2, 1 => -v 7 | 2, 3 => v 13 | 2, 4 => v 14 | 2, 5 => v 15
      | 2, 6 => v 16 | 2, 7 => v 17
      | 3, 0 => -v 2 | 3, 1 => -v 8 | 3, 2 => -v 13 | 3, 4 => v 18 | 3, 5 => v 19
      | 3, 6 => v 20 | 3, 7 => v 21
      | 4, 0 => -v 3 | 4, 1 => -v 9 | 4, 2 => -v 14 | 4, 3 => -v 18 | 4, 5 => v 22
      | 4, 6 => v 23 | 4, 7 => v 24
      | 5, 0 => -v 4 | 5, 1 => -v 10 | 5, 2 => -v 15 | 5, 3 => -v 19 | 5, 4 => -v 22
      | 5, 6 => v 25 | 5, 7 => v 26
      | 6, 0 => -v 5 | 6, 1 => -v 11 | 6, 2 => -v 16 | 6, 3 => -v 20 | 6, 4 => -v 23
      | 6, 5 => -v 25 | 6, 7 => v 27
      | 7, 0 => -v 6 | 7, 1 => -v 12 | 7, 2 => -v 17 | 7, 3 => -v 21 | 7, 4 => -v 24
      | 7, 5 => -v 26 | 7, 6 => -v 27
      | _, _ => 0),
    by
      rw [mem_so8LieSubalgebra_iff]
      ext i j
      fin_cases i <;> fin_cases j <;> norm_num⟩

private theorem so8Pack_so8Unpack (v : Fin 28 → ℝ) :
    so8Pack (so8Unpack v) = v := by
  ext p
  fin_cases p <;> rfl

private theorem so8Unpack_so8Pack (M : so8LieSubalgebra) :
    so8Unpack (so8Pack M) = M := by
  have hM : ((M : GaugeMatrix)ᵀ = -(M : GaugeMatrix)) :=
    (mem_so8LieSubalgebra_iff (M := (M : GaugeMatrix))).1 M.property
  apply Subtype.ext
  ext i j
  fin_cases i <;> fin_cases j
  all_goals
    first
    | rfl
      simpa using skew_diag_zero hM 0
      simpa using skew_diag_zero hM 1
      simpa using skew_diag_zero hM 2
      simpa using skew_diag_zero hM 3
      simpa using skew_diag_zero hM 4
      simpa using skew_diag_zero hM 5
      simpa using skew_diag_zero hM 6
      simpa using skew_diag_zero hM 7
      simpa using skew_entry_swap hM 1 0
      simpa using skew_entry_swap hM 2 0
      simpa using skew_entry_swap hM 3 0
      simpa using skew_entry_swap hM 4 0
      simpa using skew_entry_swap hM 5 0
      simpa using skew_entry_swap hM 6 0
      simpa using skew_entry_swap hM 7 0
      simpa using skew_entry_swap hM 2 1
      simpa using skew_entry_swap hM 3 1
      simpa using skew_entry_swap hM 4 1
      simpa using skew_entry_swap hM 5 1
      simpa using skew_entry_swap hM 6 1
      simpa using skew_entry_swap hM 7 1
      simpa using skew_entry_swap hM 3 2
      simpa using skew_entry_swap hM 4 2
      simpa using skew_entry_swap hM 5 2
      simpa using skew_entry_swap hM 6 2
      simpa using skew_entry_swap hM 7 2
      simpa using skew_entry_swap hM 4 3
      simpa using skew_entry_swap hM 5 3
      simpa using skew_entry_swap hM 6 3
      simpa using skew_entry_swap hM 7 3
      simpa using skew_entry_swap hM 5 4
      simpa using skew_entry_swap hM 6 4
      simpa using skew_entry_swap hM 7 4
      simpa using skew_entry_swap hM 6 5
      simpa using skew_entry_swap hM 7 5
      simpa using skew_entry_swap hM 7 6
      simpa using skew_entry_swap hM 7 6

private noncomputable def so8PackEquiv : so8LieSubalgebra ≃ₗ[ℝ] (Fin 28 → ℝ) where
  toFun := so8Pack
  invFun := so8Unpack
  left_inv := so8Unpack_so8Pack
  right_inv := so8Pack_so8Unpack
  map_add' := so8Pack.map_add
  map_smul' := so8Pack.map_smul

theorem finrank_so8LieSubalgebra :
    Module.finrank ℝ so8LieSubalgebra = 28 := by
  have h := LinearEquiv.finrank_eq so8PackEquiv
  rw [Module.finrank_pi, Fintype.card_fin] at h
  exact h

theorem finrank_g2DeltaGeneratedLie_eq_28 :
    Module.finrank ℝ g2DeltaGeneratedLie = 28 := by
  have hspan : Module.finrank ℝ (Submodule.span ℝ (Set.range g2DeltaWitness)) = 28 := by
    rw [finrank_span_eq_card g2DeltaWitness_linearIndependent, Fintype.card_fin]
  have hsub : Submodule.span ℝ (Set.range g2DeltaWitness) ≤ (g2DeltaGeneratedLie : Submodule ℝ GaugeMatrix) := by
    rw [Submodule.span_le]
    intro M hM
    obtain ⟨k, rfl⟩ := hM
    exact g2DeltaWitness_mem_g2DeltaGeneratedLie k
  have hge : 28 ≤ Module.finrank ℝ g2DeltaGeneratedLie := by
    rw [← hspan]
    exact Submodule.finrank_mono hsub
  have hle : Module.finrank ℝ g2DeltaGeneratedLie ≤ 28 := by
    exact (Submodule.finrank_mono g2DeltaGeneratedLie_le_so8LieSubalgebra).trans_eq
      finrank_so8LieSubalgebra
  exact le_antisymm hle hge

theorem g2DeltaGeneratedLie_eq_so8LieSubalgebra :
    g2DeltaGeneratedLie = so8LieSubalgebra := by
  rw [← LieSubalgebra.toSubmodule_inj]
  exact Submodule.eq_of_le_of_finrank_eq g2DeltaGeneratedLie_le_so8LieSubalgebra
    (by
      simpa using (show Module.finrank ℝ g2DeltaGeneratedLie = Module.finrank ℝ so8LieSubalgebra by
        rw [finrank_g2DeltaGeneratedLie_eq_28, finrank_so8LieSubalgebra]))

theorem so8Generator_mem_g2DeltaGeneratedLie (k : Fin 28) :
    Hqiv.so8Generator k ∈ g2DeltaGeneratedLie := by
  have hso8 : Hqiv.so8Generator k ∈ so8LieSubalgebra := by
    rw [mem_so8LieSubalgebra_iff]
    exact eq_neg_iff_add_eq_zero.mpr (by simpa [add_comm] using Hqiv.so8Generator_antisymm k)
  rw [g2DeltaGeneratedLie_eq_so8LieSubalgebra]
  exact hso8

theorem span_so8Generators_le_g2DeltaGeneratedLie :
    Submodule.span ℝ (Set.range Hqiv.so8Generator) ≤ (g2DeltaGeneratedLie : Submodule ℝ GaugeMatrix) := by
  rw [Submodule.span_le]
  intro M hM
  obtain ⟨k, rfl⟩ := hM
  exact so8Generator_mem_g2DeltaGeneratedLie k

end Hqiv.Algebra
