import Mathlib.Algebra.Lie.SkewAdjoint
import Mathlib.Data.Fintype.BigOperators
import Mathlib.Data.Matrix.Basis
import Mathlib.Algebra.BigOperators.Finsupp.Basic
import Mathlib.Data.Matrix.Basic
import Mathlib.Data.Matrix.Mul
import Mathlib.LinearAlgebra.Matrix.Defs
import Mathlib.Data.Real.Basic
import Mathlib.Tactic.FinCases
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring

/-!
# Generic minimal `𝔰𝔬(N)` seed (`N ≥ 3`): embedded `𝔰𝔬(N-1)` + one plane connector

For `N ≥ 2`, embed `Fin (N-1)` into `Fin N` via `predEmbed` (first `N-1` coordinates) and write
`lastEmbed` for the final basis vector.

**Seed:** all `L_{ij} := E_{ij}-E_{ji}` with `i < j` strictly inside the embedded `(N-1)`-block, plus
one connector `L_{k,last}` for chosen `k : Fin (N-1)`.

For `N ≥ 3`, the Lie subalgebra generated by this finite set is the full matrix model
`skewAdjointMatricesLieSubalgebra (1 : Matrix (Fin N) (Fin N) ℝ)`.

The `N = 2` case is the one-dimensional abelian Lie algebra where the seed already equals the
unique skew direction; we do not re-prove that triviality here (the paper records it separately).
-/

open scoped Matrix BigOperators

namespace Hqiv.Algebra

variable {N : ℕ}

abbrev Mat (N : ℕ) := Matrix (Fin N) (Fin N) ℝ

lemma fin_succ_eq (h : 2 ≤ N) : (N - 1) + 1 = N := by omega

def predEmbed (N : ℕ) (h : 2 ≤ N) (i : Fin (N - 1)) : Fin N :=
  Fin.cast (fin_succ_eq h) (Fin.castSucc i)

def lastEmbed (N : ℕ) (h : 2 ≤ N) : Fin N :=
  Fin.cast (fin_succ_eq h) (Fin.last (N - 1))

theorem predEmbed_lt_last (h : 2 ≤ N) (i : Fin (N - 1)) :
    predEmbed N h i ≠ lastEmbed N h := by
  intro he
  apply_fun Fin.val at he
  simp [predEmbed, lastEmbed, fin_succ_eq, Fin.val_last, Fin.val_castSucc] at he
  omega

theorem predEmbed_injective (h : 2 ≤ N) : Function.Injective (predEmbed N h) := by
  intro i j hij
  apply Fin.ext
  simpa [predEmbed, fin_succ_eq, Fin.val_castSucc] using congrArg Fin.val hij

def planeGen {N : ℕ} (i j : Fin N) (hij : i ≠ j) : Mat N :=
  Matrix.single i j (1 : ℝ) - Matrix.single j i (1 : ℝ)

theorem planeGen_diag_eq_zero {a b : Fin N} (hab : a ≠ b) (k : Fin N) :
    planeGen a b hab k k = 0 := by
  have h1 : ¬(a = k ∧ b = k) := by rintro ⟨ha', hb'⟩; rw [ha', hb'] at hab; exact hab rfl
  have h2 : ¬(b = k ∧ a = k) := by rintro ⟨hb', ha'⟩; rw [hb', ha'] at hab; exact hab rfl
  simp [planeGen, Matrix.sub_apply, Matrix.single_apply, h1, h2, if_neg]

theorem planeGen_entry_eq_one_of_lt {i j : Fin N} (hlt : i < j) :
    planeGen i j (ne_of_lt hlt) i j = 1 := by
  simp [planeGen, Matrix.sub_apply, Matrix.single_apply, ne_of_lt hlt, Ne.symm (ne_of_lt hlt)]

theorem planeGen_entry_eq_neg_one_of_lt {j i : Fin N} (hlt : j < i) :
    planeGen j i (ne_of_lt hlt) i j = -1 := by
  simp [planeGen, Matrix.sub_apply, Matrix.single_apply, ne_of_lt hlt, Ne.symm (ne_of_lt hlt)]

theorem planeGen_entry_eq_zero_of_ne_mk_upper {p : Fin N × Fin N} {a b : Fin N}
    (hp : p.1 < p.2) (hab : a < b) (hne : p ≠ (a, b)) :
    planeGen p.1 p.2 (ne_of_lt hp) a b = 0 := by
  rw [planeGen, Matrix.sub_apply]
  by_cases h1 : p.1 = a ∧ p.2 = b
  · exact False.elim (hne (Prod.ext h1.1 h1.2))
  by_cases h2 : p.2 = a ∧ p.1 = b
  · rcases h2 with ⟨h2a, h2b⟩
    rw [h2b, h2a] at hp
    exact False.elim (lt_asymm hab hp)
  simp_rw [Matrix.single_apply]
  rw [if_neg h1, if_neg h2]
  ring

/-- Same situation as `planeGen_entry_eq_zero_of_ne_mk_upper`, but the distinguished upper pair is
`(b,a)` with `b < a` and we read the entry at `(a,b)` (e.g. `(i,j)` with `j < i` and pair `(j,i)`). -/
theorem planeGen_entry_eq_zero_of_ne_mk_lower {p : Fin N × Fin N} {a b : Fin N}
    (hp : p.1 < p.2) (hba : b < a) (hne : p ≠ (b, a)) :
    planeGen p.1 p.2 (ne_of_lt hp) a b = 0 := by
  rw [planeGen, Matrix.sub_apply]
  by_cases h1 : p.1 = a ∧ p.2 = b
  · rcases h1 with ⟨h1a, h1b⟩
    rw [h1a, h1b] at hp
    exact False.elim (lt_asymm hba hp)
  by_cases h2 : p.2 = a ∧ p.1 = b
  · exact False.elim (hne (Prod.ext h2.2 h2.1))
  simp_rw [Matrix.single_apply]
  rw [if_neg h1, if_neg h2]
  ring

theorem planeGen_congr {N : ℕ} {a b c d : Fin N} (ha : a = c) (hb : b = d)
    {hab : a ≠ b} {hcd : c ≠ d} : planeGen a b hab = planeGen c d hcd := by
  subst ha hb
  rfl

theorem planeGen_transpose {N : ℕ} (i j : Fin N) (hij : i ≠ j) :
    (planeGen i j hij)ᵀ = -planeGen i j hij := by
  rw [planeGen, Matrix.transpose_sub, Matrix.transpose_single, Matrix.transpose_single]
  simp [sub_eq_add_neg, add_comm, add_left_comm]

theorem planeGen_mem_skewOne {N : ℕ} (i j : Fin N) (hij : i ≠ j) :
    planeGen i j hij ∈ skewAdjointMatricesSubmodule (1 : Mat N) := by
  rw [mem_skewAdjointMatricesSubmodule, Matrix.IsSkewAdjoint, Matrix.IsAdjointPair]
  simpa [Matrix.mul_apply, Matrix.one_apply, planeGen_transpose, planeGen, Matrix.single_apply,
    mul_ite, mul_one, mul_zero, Finset.sum_ite_eq, Finset.sum_eq_single, hij] using
    (congrArg (fun M : Mat N => ∀ p q, M p q = (-planeGen i j hij) p q) (planeGen_transpose i j hij))

/-- Entry `(p,q)` of the product of two matrix units `E_{ij}` and `E_{kl}` (scaled by `c`, `d`). -/
theorem single_mul_single_entry {N : ℕ} (i j k l p q : Fin N) (c d : ℝ) :
    (Matrix.single i j c * Matrix.single k l d) p q =
      if _hjk : j = k then c * d * (if i = p ∧ l = q then (1 : ℝ) else 0) else 0 := by
  classical
  simp_rw [Matrix.mul_apply]
  by_cases h : j = k
  · rw [← h]
    rw [Finset.sum_eq_single j]
    · by_cases hp : i = p <;> by_cases hq : l = q <;> simp [Matrix.single_apply, hp, hq, mul_ite,
        mul_one, mul_zero, and_comm, and_left_comm, and_assoc]
    · intro t _ hne
      simp [Matrix.single_apply, Ne.symm hne, mul_zero]
    · simp
  · rw [dif_neg h]
    refine Finset.sum_eq_zero ?_
    intro t _
    by_cases htj : t = j
    · subst htj
      simp [Matrix.single_apply, Ne.symm h, mul_ite, mul_zero, mul_one, and_assoc, and_left_comm,
        and_comm]
    · refine mul_eq_zero.mpr (Or.inl ?_)
      simp [Matrix.single_apply, show j ≠ t from Ne.symm htj]

/-- `⁅L_{ab}, L_{bc}⁆ = L_{ac}` for pairwise distinct indices `a,b,c`. -/
theorem lie_planeGen_triple {N : ℕ} {a b c : Fin N}
    (hab : a ≠ b) (hbc : b ≠ c) (hac : a ≠ c) :
    ⁅planeGen a b hab, planeGen b c hbc⁆ = planeGen a c hac := by
  classical
  rw [LieRing.of_associative_ring_bracket]
  simp_rw [planeGen]
  have XY :
      (Matrix.single a b (1 : ℝ) - Matrix.single b a (1 : ℝ)) *
          (Matrix.single b c (1 : ℝ) - Matrix.single c b (1 : ℝ)) =
        Matrix.single a c (1 : ℝ) := by
    rw [Matrix.sub_mul, Matrix.mul_sub, Matrix.mul_sub]
    have t11 : Matrix.single a b (1 : ℝ) * Matrix.single b c (1 : ℝ) = Matrix.single a c (1 : ℝ) := by
      simp [Matrix.single_mul_single_same]
    have t12 : Matrix.single a b (1 : ℝ) * Matrix.single c b (1 : ℝ) = 0 := by
      rw [Matrix.single_mul_single_of_ne (1 : ℝ) a b c hbc (1 : ℝ)]
    have t21 : Matrix.single b a (1 : ℝ) * Matrix.single b c (1 : ℝ) = 0 := by
      rw [Matrix.single_mul_single_of_ne (1 : ℝ) b a b hab (1 : ℝ)]
    have t22 : Matrix.single b a (1 : ℝ) * Matrix.single c b (1 : ℝ) = 0 := by
      rw [Matrix.single_mul_single_of_ne (1 : ℝ) b a c hac (1 : ℝ)]
    rw [t11, t12, t21, t22]
    simp
  have YX :
      (Matrix.single b c (1 : ℝ) - Matrix.single c b (1 : ℝ)) *
          (Matrix.single a b (1 : ℝ) - Matrix.single b a (1 : ℝ)) =
        Matrix.single c a (1 : ℝ) := by
    rw [Matrix.sub_mul, Matrix.mul_sub, Matrix.mul_sub]
    have s11 : Matrix.single b c (1 : ℝ) * Matrix.single a b (1 : ℝ) = 0 := by
      rw [Matrix.single_mul_single_of_ne (1 : ℝ) b c a hac.symm (1 : ℝ)]
    have s12 : Matrix.single b c (1 : ℝ) * Matrix.single b a (1 : ℝ) = 0 := by
      rw [Matrix.single_mul_single_of_ne (1 : ℝ) b c b hbc.symm (1 : ℝ)]
    have s21 : Matrix.single c b (1 : ℝ) * Matrix.single a b (1 : ℝ) = 0 := by
      rw [Matrix.single_mul_single_of_ne (1 : ℝ) c b a hab.symm (1 : ℝ)]
    have s22 : Matrix.single c b (1 : ℝ) * Matrix.single b a (1 : ℝ) = Matrix.single c a (1 : ℝ) := by
      simp [Matrix.single_mul_single_same]
    rw [s11, s12, s21, s22]
    simp
  calc
    (Matrix.single a b (1 : ℝ) - Matrix.single b a (1 : ℝ)) *
            (Matrix.single b c (1 : ℝ) - Matrix.single c b (1 : ℝ)) -
        (Matrix.single b c (1 : ℝ) - Matrix.single c b (1 : ℝ)) *
            (Matrix.single a b (1 : ℝ) - Matrix.single b a (1 : ℝ)) =
        Matrix.single a c (1 : ℝ) -
          ((Matrix.single b c (1 : ℝ) - Matrix.single c b (1 : ℝ)) *
            (Matrix.single a b (1 : ℝ) - Matrix.single b a (1 : ℝ))) := by
      rw [XY]
    _ = Matrix.single a c (1 : ℝ) - Matrix.single c a (1 : ℝ) := by rw [YX]
    _ = planeGen a c hac := by simp [planeGen]

def minimalSoSeedSet (N : ℕ) (hN : 2 ≤ N) (k : Fin (N - 1)) : Set (Mat N) :=
  (Set.range fun ij : { p : Fin (N - 1) × Fin (N - 1) // p.1 < p.2} =>
      planeGen (predEmbed N hN ij.val.1) (predEmbed N hN ij.val.2)
        (by intro he; exact ne_of_lt ij.property (predEmbed_injective hN he))) ∪
    {planeGen (predEmbed N hN k) (lastEmbed N hN) (predEmbed_lt_last hN k)}

theorem mem_minimalSoSeedSet_of_pair {N : ℕ} (hN : 2 ≤ N) (k : Fin (N - 1))
    {i j : Fin (N - 1)} (hij : i < j) :
    planeGen (predEmbed N hN i) (predEmbed N hN j)
        (by intro he; exact ne_of_lt hij (predEmbed_injective hN he)) ∈ minimalSoSeedSet N hN k :=
  Set.mem_union_left _ ⟨⟨(i, j), hij⟩, rfl⟩

theorem mem_minimalSoSeedSet_delta {N : ℕ} (hN : 2 ≤ N) (k : Fin (N - 1)) :
    planeGen (predEmbed N hN k) (lastEmbed N hN) (predEmbed_lt_last hN k) ∈ minimalSoSeedSet N hN k :=
  Set.mem_union_right _ rfl

theorem minimalSoSeedSet_subset_skewAdjoint (N : ℕ) (hN : 2 ≤ N) (k : Fin (N - 1)) :
    minimalSoSeedSet N hN k ⊆ skewAdjointMatricesSubmodule (1 : Mat N) := by
  intro M hM
  rcases hM with ⟨ij, rfl⟩ | rfl
  · exact planeGen_mem_skewOne _ _ _
  · exact planeGen_mem_skewOne _ _ _

noncomputable def minimalSoSeedLie (N : ℕ) (hN : 2 ≤ N) (k : Fin (N - 1)) :
    LieSubalgebra ℝ (Mat N) :=
  LieSubalgebra.lieSpan ℝ (Mat N) (minimalSoSeedSet N hN k)

theorem minimalSoSeedLie_le_skew (N : ℕ) (hN : 2 ≤ N) (k : Fin (N - 1)) :
    minimalSoSeedLie N hN k ≤ skewAdjointMatricesLieSubalgebra (1 : Mat N) := by
  refine (LieSubalgebra.lieSpan_le (R := ℝ) (L := Mat N) (s := minimalSoSeedSet N hN k)
    (K := skewAdjointMatricesLieSubalgebra (1 : Mat N))).mpr ?_
  exact minimalSoSeedSet_subset_skewAdjoint N hN k

def upperPairs (N : ℕ) : Finset (Fin N × Fin N) :=
  Finset.univ.filter (fun p : Fin N × Fin N => p.1 < p.2)

theorem mem_upperPairs_iff {N : ℕ} (p : Fin N × Fin N) :
    p ∈ upperPairs N ↔ p.1 < p.2 := by simp [upperPairs]

theorem skew_eq_sum_planeGen (M : Mat N) (hM : Mᵀ = -M) :
    M = Finset.univ.sum fun p : Fin N × Fin N =>
        if h : p.1 < p.2 then M p.1 p.2 • planeGen p.1 p.2 (ne_of_lt h) else 0 := by
  classical
  ext i j
  rw [Matrix.sum_apply i j Finset.univ]
  simp_rw [Matrix.dite_apply, Matrix.smul_apply, smul_eq_mul]
  by_cases hij : i = j
  · subst hij
    have diag0 : M i i = 0 := by
      have := congrArg (fun X => X i i) hM
      simp [Matrix.transpose_apply] at this
      linarith
    rw [diag0, eq_comm]
    refine Finset.sum_eq_zero (M := ℝ) fun p _hp => ?_
    by_cases h : p.1 < p.2
    · simp [h, planeGen_diag_eq_zero (ne_of_lt h), mul_zero]
    · simp [dif_neg h]
  · by_cases hlt : i < j
    · rw [Finset.sum_eq_single (i, j)]
      · rw [dif_pos hlt, planeGen_entry_eq_one_of_lt hlt, mul_one]
      · intro p _ hp
        by_cases hl : p.1 < p.2
        · rw [dif_pos hl, planeGen_entry_eq_zero_of_ne_mk_upper hl hlt hp, mul_zero]
        · simp [dif_neg hl]
      · simp
    · push_neg at hlt
      have hlt' : j < i := by
        rcases lt_trichotomy i j with (h | h | h)
        · exact (not_lt_of_ge hlt h).elim
        · exact (hij h).elim
        · exact h
      have hskew : M i j = -M j i := by
        have := congrArg (fun X => X j i) hM
        simp [Matrix.transpose_apply] at this
        linarith
      rw [hskew, Finset.sum_eq_single (j, i)]
      · rw [dif_pos hlt', planeGen_entry_eq_neg_one_of_lt hlt', mul_neg, mul_one]
      · intro p _ hp
        by_cases hl : p.1 < p.2
        · rw [dif_pos hl, planeGen_entry_eq_zero_of_ne_mk_lower hl hlt' hp, mul_zero]
        · simp [dif_neg hl]
      · simp

theorem val_lt_last_iff {j : Fin N} (hN : 2 ≤ N) : j.val < N - 1 ↔ j ≠ lastEmbed N hN := by
  constructor
  · intro hj he
    apply_fun Fin.val at he
    simp [lastEmbed, fin_succ_eq, Fin.val_last] at he
    omega
  · intro hne
    by_contra h'
    push_neg at h'
    have hval : j.val = N - 1 := by omega
    have : j = lastEmbed N hN := by
      apply Fin.ext
      simp [lastEmbed, fin_succ_eq, Fin.val_last, hval]
    exact hne this

theorem exists_predEmbed_of_val_lt {h : 2 ≤ N} {j : Fin N} (hj : j.val < N - 1) :
    ∃ i : Fin (N - 1), predEmbed N h i = j := by
  refine ⟨⟨j.val, ?_⟩, ?_⟩
  · omega
  · apply Fin.ext
    simp [predEmbed, fin_succ_eq, Fin.val_castSucc]

theorem planeGen_castPred_last_mem_minimalSoSeedLie {N : ℕ} (hN : 3 ≤ N) (k i' : Fin (N - 1))
    (hi' : i' ≠ k) :
    planeGen (predEmbed N (Nat.le_trans (by decide : 2 ≤ 3) hN) i')
        (lastEmbed N (Nat.le_trans (by decide : 2 ≤ 3) hN))
        (predEmbed_lt_last (Nat.le_trans (by decide : 2 ≤ 3) hN) i') ∈
      minimalSoSeedLie N (Nat.le_trans (by decide : 2 ≤ 3) hN) k := by
  let h2 : 2 ≤ N := Nat.le_trans (by decide : 2 ≤ 3) hN
  let L := minimalSoSeedLie N h2 k
  have hk'i : predEmbed N h2 i' ≠ predEmbed N h2 k := fun h => hi' (predEmbed_injective h2 h)
  have hk_ik : predEmbed N h2 k ≠ predEmbed N h2 i' := hk'i.symm
  have hk_last : predEmbed N h2 k ≠ lastEmbed N h2 := predEmbed_lt_last h2 k
  have hi'_last : predEmbed N h2 i' ≠ lastEmbed N h2 := predEmbed_lt_last h2 i'
  have bracket' :
      ⁅planeGen (predEmbed N h2 i') (predEmbed N h2 k) hk'i,
          planeGen (predEmbed N h2 k) (lastEmbed N h2) hk_last⁆ =
        planeGen (predEmbed N h2 i') (lastEmbed N h2) hi'_last :=
    lie_planeGen_triple (a := predEmbed N h2 i') (b := predEmbed N h2 k) (c := lastEmbed N h2)
      hk'i hk_last hi'_last
  rw [← bracket']
  refine LieSubalgebra.lie_mem L ?_ ?_
  · by_cases h : k < i'
    · have hmem := mem_minimalSoSeedSet_of_pair h2 k h
      have flip :
          planeGen (predEmbed N h2 i') (predEmbed N h2 k) hk'i =
            -planeGen (predEmbed N h2 k) (predEmbed N h2 i') hk_ik := by
        ext p q
        simp [planeGen, sub_eq_add_neg, add_comm, add_left_comm]
      rw [flip]
      exact neg_mem (LieSubalgebra.subset_lieSpan (R := ℝ) (L := Mat N) (s := minimalSoSeedSet N h2 k) hmem)
    · push_neg at h
      have hlt : i' < k := lt_of_le_of_ne h hi'
      have hmem := mem_minimalSoSeedSet_of_pair h2 k hlt
      exact LieSubalgebra.subset_lieSpan (R := ℝ) (L := Mat N) (s := minimalSoSeedSet N h2 k) hmem
  · exact LieSubalgebra.subset_lieSpan (R := ℝ) (L := Mat N) (s := minimalSoSeedSet N h2 k)
      (mem_minimalSoSeedSet_delta h2 k)

theorem planeGen_lt_pair_mem_minimalSoSeedLie {N : ℕ} (hN : 3 ≤ N) (kIdx : Fin (N - 1))
    {i j : Fin N} (hij : i < j) :
    planeGen i j (ne_of_lt hij) ∈ minimalSoSeedLie N (Nat.le_trans (by decide : 2 ≤ 3) hN) kIdx := by
  let hij_ij := hij
  let h2 : 2 ≤ N := Nat.le_trans (by decide : 2 ≤ 3) hN
  let L := minimalSoSeedLie N h2 kIdx
  by_cases hjlast : j = lastEmbed N h2
  · subst hjlast
    have hi_lt : i.val < N - 1 := by
      have hij' := hij
      simp [lastEmbed, fin_succ_eq, Fin.lt_iff_val_lt_val, Fin.val_last] at hij' ⊢
      omega
    obtain ⟨i', rfl⟩ := exists_predEmbed_of_val_lt (h := h2) hi_lt
    by_cases he : i' = kIdx
    · have hpred : predEmbed N h2 i' = predEmbed N h2 kIdx := congrArg (predEmbed N h2) he
      simpa [hpred, planeGen, sub_eq_add_neg] using
        (LieSubalgebra.subset_lieSpan (R := ℝ) (L := Mat N) (s := minimalSoSeedSet N h2 kIdx)
          (mem_minimalSoSeedSet_delta h2 kIdx) :
          planeGen (predEmbed N h2 kIdx) (lastEmbed N h2) (predEmbed_lt_last h2 kIdx) ∈
            minimalSoSeedLie N h2 kIdx)
    · exact planeGen_castPred_last_mem_minimalSoSeedLie hN kIdx i' he
  · have hjlt : j.val < N - 1 := (val_lt_last_iff h2).mpr hjlast
    obtain ⟨j', hj'⟩ := exists_predEmbed_of_val_lt (h := h2) hjlt
    have hi_lt : i.val < N - 1 := by
      have hij' := hij
      rw [← hj'] at hij'
      simp [predEmbed, fin_succ_eq, Fin.lt_iff_val_lt_val, Fin.val_castSucc] at hij' ⊢
      omega
    obtain ⟨i', hi'⟩ := exists_predEmbed_of_val_lt (h := h2) hi_lt
    rw [← hi', ← hj'] at hij
    rcases lt_or_gt_of_ne (fun hii : i' = j' => (ne_of_lt hij) (by rw [hii])) with hlt | hgt
    · have sub :=
        LieSubalgebra.subset_lieSpan (R := ℝ) (L := Mat N) (s := minimalSoSeedSet N h2 kIdx)
          (mem_minimalSoSeedSet_of_pair h2 kIdx hlt)
      have eqv :=
        (planeGen_congr hi'.symm hj'.symm :
          planeGen i j (ne_of_lt hij_ij) =
            planeGen (predEmbed N h2 i') (predEmbed N h2 j') (ne_of_lt hij))
      rw [eqv]
      exact sub
    · have hmem := mem_minimalSoSeedSet_of_pair h2 kIdx hgt
      have flip :
          planeGen (predEmbed N h2 i') (predEmbed N h2 j') (ne_of_lt hij) =
            -planeGen (predEmbed N h2 j') (predEmbed N h2 i') (ne_of_lt hgt) := by
        ext p q
        simp [planeGen, sub_eq_add_neg, add_comm, add_left_comm]
      have sub :=
        neg_mem (LieSubalgebra.subset_lieSpan (R := ℝ) (L := Mat N) (s := minimalSoSeedSet N h2 kIdx) hmem)
      have eqv :=
        (planeGen_congr hi'.symm hj'.symm :
          planeGen i j (ne_of_lt hij_ij) =
            planeGen (predEmbed N h2 i') (predEmbed N h2 j') (ne_of_lt hij))
      rw [eqv, flip]
      exact sub

theorem skewAdjointSubmodule_le_minimalSoSeedLie (N : ℕ) (hN : 3 ≤ N) (k : Fin (N - 1)) :
    skewAdjointMatricesSubmodule (1 : Mat N) ≤ (minimalSoSeedLie N (Nat.le_trans (by decide : 2 ≤ 3) hN) k).toSubmodule := by
  intro M hM
  rw [mem_skewAdjointMatricesSubmodule, Matrix.IsSkewAdjoint, Matrix.IsAdjointPair] at hM
  have hMt : Mᵀ = -M := by
    ext i j
    simpa [Matrix.transpose_apply, Matrix.mul_apply, Matrix.one_apply] using congrArg (fun X => X i j) hM
  rw [skew_eq_sum_planeGen M hMt]
  refine Submodule.sum_mem _ fun p _ => ?_
  by_cases h : p.1 < p.2
  · simp [h]
    refine Submodule.smul_mem _ _ ?_
    exact planeGen_lt_pair_mem_minimalSoSeedLie hN k h
  · simp [h, Submodule.zero_mem]

theorem skewAdjointLieSubalgebra_le_minimalSoSeedLie (N : ℕ) (hN : 3 ≤ N) (k : Fin (N - 1)) :
    skewAdjointMatricesLieSubalgebra (1 : Mat N) ≤ minimalSoSeedLie N (Nat.le_trans (by decide : 2 ≤ 3) hN) k := by
  rw [LieSubalgebra.le_def]
  intro M hM
  have hM' : M ∈ skewAdjointMatricesSubmodule (1 : Mat N) := by
    simpa [SetLike.mem_coe, mem_skewAdjointMatricesLieSubalgebra] using hM
  have hmem := skewAdjointSubmodule_le_minimalSoSeedLie N hN k hM'
  exact (LieSubalgebra.mem_toSubmodule (L' := minimalSoSeedLie N (Nat.le_trans (by decide : 2 ≤ 3) hN) k)).2 hmem

/-- Lie closure of the minimal seed equals full `𝔰𝔬(N)` for every `N ≥ 3`. -/
theorem minimal_so_seed_lieSpan_eq_skewAdjoint (N : ℕ) (hN : 3 ≤ N) (k : Fin (N - 1)) :
    minimalSoSeedLie N (Nat.le_trans (by decide : 2 ≤ 3) hN) k =
      skewAdjointMatricesLieSubalgebra (1 : Mat N) :=
  le_antisymm (minimalSoSeedLie_le_skew N _ k) (skewAdjointLieSubalgebra_le_minimalSoSeedLie N hN k)

end Hqiv.Algebra
