#!/usr/bin/env python3
"""Emit Hqiv/Physics/StrongColorSu3LieChartLaw.lean: 64 small lemmas + one combining theorem."""

from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "Hqiv/Physics/StrongColorSu3LieChartLaw.lean"

HEADER = r'''/-
Auto-generated by `scripts/gen_strong_color_su3_lie_chart_law.py`.
Regenerate: `python3 scripts/gen_strong_color_su3_lie_chart_law.py`
-/

import Hqiv.Physics.StrongColorSu3LieCertificate
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.FinCases

/-!
# Strong color: global `su(3)` chart Lie law (certificate layer)

Proves `∀ a b : Fin 8, [T^a,T^b] = Complex.I • ∑_c f^{abc} T^c` for `T^a = λ^a/2` on the `3×3` chart.

Imports the optional `@[simp]` table `StrongColorSu3fStructureSimp` (via `StrongColorSu3LieCertificate`);
build with `lake build HQIVStrongColorSu3Certificate`.
-/

open scoped BigOperators
open Complex Finset Matrix
open Hqiv.Algebra Hqiv.Physics

namespace Hqiv.Physics

noncomputable section

set_option maxHeartbeats 8000000

theorem colorSu3fStructure_self_eq_zero (a c : Fin 8) : colorSu3fStructure a a c = (0 : ℝ) := by
  dsimp [colorSu3fStructure]
  simp

theorem colorHalfGellMannFull_f_sum_self (a : Fin 8) :
    (∑ c : Fin 8, (colorSu3fStructure a a c : ℂ) • colorHalfGellMannFull c) = 0 := by
  refine Finset.sum_eq_zero ?_
  intro c _
  rw [colorSu3fStructure_self_eq_zero]
  simp

'''

DIAG_LEMMA = """/-- Diagonal case ({ia},{ib}). -/
lemma colorLieChartBracket_{ia}_{ib} :
    lieBracketMat₃ (colorHalfGellMannFull ({ia} : Fin 8)) (colorHalfGellMannFull ({ib} : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure ({ia} : Fin 8) ({ib} : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  rw [colorHalfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat₃, smul_zero]

"""

OFF_LEMMA = """/-- Off-diagonal case ({ia},{ib}). -/
lemma colorLieChartBracket_{ia}_{ib} :
    lieBracketMat₃ (colorHalfGellMannFull ({ia} : Fin 8)) (colorHalfGellMannFull ({ib} : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure ({ia} : Fin 8) ({ib} : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {{
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }}

"""

MAIN = """
/-- Global chart Lie law for half–Gell–Mann generators (all 64 ordered pairs). -/
theorem colorHalfGellMannFull_lieBracket_eq_I_smul_f_sum (a b : Fin 8) :
    lieBracketMat₃ (colorHalfGellMannFull a) (colorHalfGellMannFull b) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure a b c : ℂ) • colorHalfGellMannFull c := by
  fin_cases a <;> fin_cases b
"""

FOOTER = r'''
end -- noncomputable section

end Hqiv.Physics
'''


def main() -> None:
    parts = [HEADER]
    exact_lines: list[str] = []
    for ia in range(8):
        for ib in range(8):
            if ia == ib:
                parts.append(DIAG_LEMMA.format(ia=ia, ib=ib))
            else:
                parts.append(OFF_LEMMA.format(ia=ia, ib=ib))
            exact_lines.append(f"  · exact colorLieChartBracket_{ia}_{ib}")
    parts.append(MAIN)
    parts.append("\n".join(exact_lines))
    parts.append("\n")
    parts.append(FOOTER)
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
