#!/usr/bin/env python3
"""Emit SU(3) Lie chart law: 64 small lemmas + one combining theorem (legacy or spine)."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CONFIGS = {
    "legacy": {
        "out": ROOT / "Hqiv/Physics/StrongColorSu3LieChartLaw.lean",
        "cert_import": "import Hqiv.Physics.StrongColorSu3LieCertificate",
        "namespace": "Hqiv.Physics",
        "open_extra": "open Hqiv.Algebra Hqiv.Physics",
        "title": "Strong color: global `su(3)` chart Lie law (certificate layer)",
        "build_note": "build with `lake build HQIVStrongColorSu3Certificate`.",
        "f_name": "colorSu3fStructure",
        "half": "colorHalfGellMannFull",
        "bracket": "lieBracketMat₃",
        "lambda_full": "colorGellMannLambdaFull",
        "lambdas": [
            "colorGellMannLambda1", "colorGellMannLambda2", "colorGellMannLambda3",
            "colorGellMannLambda4", "colorGellMannLambda5", "colorGellMannLambda6",
            "colorGellMannLambda7", "colorGellMannLambda8",
        ],
        "perm": "colorSu3PermSign",
        "sorted": "colorSu3fSorted",
        "lemma_prefix": "colorLieChartBracket",
        "main_theorem": "colorHalfGellMannFull_lieBracket_eq_I_smul_f_sum",
        "self_zero": "colorSu3fStructure_self_eq_zero",
        "f_sum_self": "colorHalfGellMannFull_f_sum_self",
    },
    "spine": {
        "out": ROOT / "HqivSpine/Algebra/StrongColorSu3LieLaw.lean",
        "cert_import": "import HqivSpine.Algebra.StrongColorSu3LieCertificate",
        "namespace": "HqivSpine.Algebra.StrongColor",
        "open_extra": "",
        "title": "StrongColorSu3: global `su(3)` chart Lie law",
        "build_note": "included in `lake build HQIVCleanSpine`.",
        "f_name": "su3fStructure",
        "half": "halfGellMannFull",
        "bracket": "lieBracketMat3",
        "lambda_full": "gellMannFull",
        "lambdas": [
            "gellMann1", "gellMann2", "gellMann3",
            "gellMann4", "gellMann5", "gellMann6",
            "gellMann7", "gellMann8",
        ],
        "perm": "su3PermSign",
        "sorted": "su3fSorted",
        "lemma_prefix": "su3LieChartBracket",
        "main_theorem": "halfGellMannFull_lieBracket_eq_I_smul_f_sum",
        "self_zero": "su3fStructure_self_eq_zero",
        "f_sum_self": "halfGellMannFull_f_sum_self",
    },
}


def header(cfg: dict) -> str:
    return f'''/-
Auto-generated by `scripts/gen_strong_color_su3_lie_chart_law.py`.
Regenerate: `python3 scripts/gen_strong_color_su3_lie_chart_law.py` [--spine]
-/

{cfg["cert_import"]}
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.FinCases

/-!
# {cfg["title"]}

Proves `∀ a b : Fin 8, [T^a,T^b] = Complex.I • ∑_c f^{{abc}} T^c` for `T^a = λ^a/2` on the `3×3` chart.
{cfg["build_note"]}
-/

open scoped BigOperators
open Complex Finset Matrix
{cfg["open_extra"]}

namespace {cfg["namespace"]}

noncomputable section

set_option maxHeartbeats 8000000

theorem {cfg["self_zero"]} (a c : Fin 8) : {cfg["f_name"]} a a c = (0 : ℝ) := by
  dsimp [{cfg["f_name"]}]
  simp

theorem {cfg["f_sum_self"]} (a : Fin 8) :
    (∑ c : Fin 8, ({cfg["f_name"]} a a c : ℂ) • {cfg["half"]} c) = 0 := by
  refine Finset.sum_eq_zero ?_
  intro c _
  rw [{cfg["self_zero"]}]
  simp

'''


def diag_lemma(cfg: dict, ia: int, ib: int) -> str:
    return f"""/-- Diagonal case ({ia},{ib}). -/
lemma {cfg["lemma_prefix"]}_{ia}_{ib} :
    {cfg["bracket"]} ({cfg["half"]} ({ia} : Fin 8)) ({cfg["half"]} ({ib} : Fin 8)) =
      Complex.I • ∑ c : Fin 8, ({cfg["f_name"]} ({ia} : Fin 8) ({ib} : Fin 8) c : ℂ) • {cfg["half"]} c := by
  rw [{cfg["f_sum_self"]}]
  ext i j
  simp [{cfg["bracket"]}, smul_zero]

"""


def off_lemma(cfg: dict, ia: int, ib: int) -> str:
    lambda_list = ", ".join(cfg["lambdas"])
    return f"""/-- Off-diagonal case ({ia},{ib}). -/
lemma {cfg["lemma_prefix"]}_{ia}_{ib} :
    {cfg["bracket"]} ({cfg["half"]} ({ia} : Fin 8)) ({cfg["half"]} ({ib} : Fin 8)) =
      Complex.I • ∑ c : Fin 8, ({cfg["f_name"]} ({ia} : Fin 8) ({ib} : Fin 8) c : ℂ) • {cfg["half"]} c := by
  unfold {cfg["bracket"]}
  ext i j
  fin_cases i <;> fin_cases j <;> {{
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      {cfg["half"]}, {cfg["lambda_full"]}, {lambda_list}]
    try simp [{cfg["f_name"]}, {cfg["perm"]}, min3, mid3, max3, {cfg["sorted"]}]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }}

"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spine", action="store_true")
    args = parser.parse_args()
    cfg = CONFIGS["spine" if args.spine else "legacy"]

    parts = [header(cfg)]
    exact_lines: list[str] = []
    for ia in range(8):
        for ib in range(8):
            if ia == ib:
                parts.append(diag_lemma(cfg, ia, ib))
            else:
                parts.append(off_lemma(cfg, ia, ib))
            exact_lines.append(f"  · exact {cfg['lemma_prefix']}_{ia}_{ib}")
    parts.append(f"""
/-- Global chart Lie law for half–Gell–Mann generators (all 64 ordered pairs). -/
theorem {cfg["main_theorem"]} (a b : Fin 8) :
    {cfg["bracket"]} ({cfg["half"]} a) ({cfg["half"]} b) =
      Complex.I • ∑ c : Fin 8, ({cfg["f_name"]} a b c : ℂ) • {cfg["half"]} c := by
  fin_cases a <;> fin_cases b
""")
    parts.append("\n".join(exact_lines))
    parts.append("\n")
    parts.append(f"end -- noncomputable section\n\nend {cfg['namespace']}\n")
    cfg["out"].write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {cfg['out']}")


if __name__ == "__main__":
    main()
