#!/usr/bin/env python3
"""Emit @[simp] lemmas for nonzero f^{abc} (legacy Hqiv or clean HqivSpine)."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

CONFIGS = {
    "legacy": {
        "out": ROOT / "Hqiv/Physics/StrongColorSu3fStructureSimp.lean",
        "import": "import Hqiv.Physics.StrongColorSu3ChartClosure",
        "namespace": "Hqiv.Physics",
        "f_name": "colorSu3fStructure",
        "perm": "colorSu3PermSign",
        "sorted": "colorSu3fSorted",
        "min3": "min3",
        "max3": "max3",
        "mid3": "mid3",
    },
    "spine": {
        "out": ROOT / "HqivSpine/Algebra/StrongColorSu3fSimp.lean",
        "import": "import HqivSpine.Algebra.StrongColorSu3",
        "namespace": "HqivSpine.Algebra.StrongColor",
        "f_name": "su3fStructure",
        "perm": "su3PermSign",
        "sorted": "su3fSorted",
        "min3": "min3",
        "max3": "max3",
        "mid3": "mid3",
    },
}


def min3(a: int, b: int, c: int) -> int:
    return min(min(a, b), c)


def max3(a: int, b: int, c: int) -> int:
    return max(max(a, b), c)


def mid3(a: int, b: int, c: int) -> int:
    i, k = min3(a, b, c), max3(a, b, c)
    if a != i and a != k:
        return a
    if b != i and b != k:
        return b
    return c


def perm_sign(a: int, b: int, c: int) -> int:
    if a == b or b == c or c == a:
        return 0
    i, j, k = min3(a, b, c), mid3(a, b, c), max3(a, b, c)
    tests = [
        (a == i and b == j and c == k, 1),
        (a == i and b == k and c == j, -1),
        (a == j and b == i and c == k, -1),
        (a == j and b == k and c == i, 1),
        (a == k and b == i and c == j, 1),
        (a == k and b == j and c == i, -1),
    ]
    for cond, s in tests:
        if cond:
            return s
    return 0


BASE_STR: dict[tuple[int, int, int], str] = {
    (0, 1, 2): "(1 : ℝ)",
    (0, 3, 6): "(1/2 : ℝ)",
    (0, 4, 5): "(-1/2 : ℝ)",
    (1, 3, 5): "(1/2 : ℝ)",
    (1, 4, 6): "(1/2 : ℝ)",
    (2, 3, 4): "(1/2 : ℝ)",
    (2, 5, 6): "(-1/2 : ℝ)",
    (3, 4, 7): "(Real.sqrt 3 / 2 : ℝ)",
    (5, 6, 7): "(Real.sqrt 3 / 2 : ℝ)",
}


def lean_rhs(a: int, b: int, c: int) -> str:
    if a == b or b == c or c == a:
        return "(0 : ℝ)"
    i, j, k = min3(a, b, c), mid3(a, b, c), max3(a, b, c)
    if not (i < j < k):
        return "(0 : ℝ)"
    s = perm_sign(a, b, c)
    if s == 0:
        return "(0 : ℝ)"
    base = BASE_STR.get((i, j, k), "(0 : ℝ)")
    if base == "(0 : ℝ)":
        return "(0 : ℝ)"
    if s == 1:
        return base
    return f"(- ({base}) : ℝ)"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spine", action="store_true", help="Emit HqivSpine/Algebra/StrongColorSu3fSimp.lean")
    args = parser.parse_args()
    cfg = CONFIGS["spine" if args.spine else "legacy"]
    f_name = cfg["f_name"]

    triples: list[tuple[int, int, int, str]] = []
    for a in range(8):
        for b in range(8):
            for c in range(8):
                rhs = lean_rhs(a, b, c)
                if rhs != "(0 : ℝ)":
                    triples.append((a, b, c, rhs))
    assert len(triples) == 54, len(triples)

    lines: list[str] = [
        "/-",
        "Auto-generated by `scripts/gen_strong_color_su3_f_simp.py`.",
        f"`@[simp]` lemmas for the **nonzero** values of `{f_name} a b c` (54 oriented triples).",
        "Zeros reduce from `simp [{f_name}]` alone. Regenerate:",
        "  python3 scripts/gen_strong_color_su3_f_simp.py [--spine]",
        "-/",
        "",
        cfg["import"],
        "",
        f"namespace {cfg['namespace']}",
        "",
    ]
    for a, b, c, rhs in triples:
        name = f"{f_name}_simp_{a}_{b}_{c}"
        lines.append(f"@[simp] theorem {name} : {f_name} ({a} : Fin 8) {b} {c} = {rhs} := by")
        lines.append(f"  have hneq : ¬(({a} : Fin 8) = {b} ∨ ({b} : Fin 8) = {c} ∨ ({c} : Fin 8) = {a}) := by decide")
        lines.append(f"  dsimp [{f_name}, hneq]")
        lines.append(f"  simp [{cfg['perm']}, {cfg['min3']}, {cfg['max3']}, {cfg['mid3']}]")
        lines.append(f"  simp [{cfg['sorted']}]")
        lines.append("")
    lines.append(f"end {cfg['namespace']}")
    lines.append("")
    cfg["out"].write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {cfg['out']} ({len(triples)} simp lemmas)")


if __name__ == "__main__":
    main()
