#!/usr/bin/env python3
"""Export consolidation-paper witness JSON and generated TeX (programme synthesis)."""

from __future__ import annotations

import argparse
import json
import math
import zipfile
from datetime import datetime, timezone
from pathlib import Path

ALPHA = 3 / 5
GAMMA = 2 / 5
REFERENCE_M = 4
P5_PRIME = 11 / 400
FB_ASYM = 8800 / 160121


def _repo_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / "lakefile.toml").exists() and (parent / "data").is_dir():
            return parent
    return Path(__file__).resolve().parents[1]


ROOT = _repo_root()
PAPER = ROOT / "papers" / "proof_spine_synthesis"
GENERATED = PAPER / "generated"


def shell_shape(m: int) -> float:
    x = m + 1
    return (1 / x) * (1 + ALPHA * math.log(x))


def curvature_integral(n: int) -> float:
    if n <= 0:
        return 0.0
    return sum(shell_shape(m) for m in range(n))


def phi_of_shell(m: int) -> float:
    return 2 * (m + 1)


def omega_k_partial(n: int) -> float:
    ref = curvature_integral(REFERENCE_M)
    return curvature_integral(n) / ref


def imprint_weighted_readout_phase(n: int) -> float:
    delta = omega_k_partial(n + 1) - omega_k_partial(n)
    return ALPHA * math.log(phi_of_shell(n) + 1) * delta


def jarlskog_phenomenology() -> dict:
    ckm_us2 = GAMMA / 8
    ckm_cb2 = GAMMA / 32
    j_ledger = ckm_us2 - ckm_cb2
    delta_cp = 3 * math.pi / 32
    t12 = math.asin(math.sqrt(ckm_us2))
    t23 = math.asin(math.sqrt(ckm_cb2))
    t13 = math.asin(math.sqrt(ckm_cb2))
    j_param = (
        math.sin(t12)
        * math.sin(t23)
        * math.sin(t13)
        * math.sin(delta_cp)
        * math.cos(t12)
        * math.cos(t23)
        * math.cos(t13)
    )
    ratio = j_param / j_ledger
    return {
        "J_ledger": j_ledger,
        "J_parameterization": j_param,
        "correction_ratio": ratio,
        "percent_of_ledger": 100 * ratio,
        "delta_cp_deg": math.degrees(delta_cp),
    }


def longitudinal_phenomenology() -> dict:
    phase = imprint_weighted_readout_phase(REFERENCE_M)
    corr = 1 + GAMMA * abs(phase)
    p5_shifted = P5_PRIME * corr
    fb_shifted = 2 * p5_shifted / (1 + p5_shifted**2)
    return {
        "referenceM": REFERENCE_M,
        "imprint_phase_at_referenceM": phase,
        "longitudinal_correction_factor": corr,
        "p5_prime_baseline": P5_PRIME,
        "p5_prime_longitudinal": p5_shifted,
        "p5_prime_relative_ppm": (p5_shifted / P5_PRIME - 1) * 1e6,
        "a_fb_baseline": FB_ASYM,
        "a_fb_longitudinal": fb_shifted,
        "a_fb_relative_ppm": (fb_shifted / FB_ASYM - 1) * 1e6,
    }


def build_witness() -> dict:
    return {
        "schema": "hqiv_proof_spine_synthesis_v1",
        "lean_capstone": "Hqiv.Physics.ProofSpineInventory.proofSpineInventory_holds",
        "python_module": "scripts/hqiv_proof_spine_synthesis_export.py",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "build_targets": [
            "lake build paper_flavor_mixing",
            "lake build HQIVPhysics",
        ],
        "tier_papers": {
            "flavor": "papers/flavor_mixing_readout/hqiv_flavor_mixing_readout.tex",
            "hep_decay": "papers/hep_decay_readout/hqiv_hep_decay_readout_from_multichannel.tex",
            "tuft_sm": "papers/tuft_sm_lagrangian/hqiv_tuft_sm_lagrangian_synthesis.tex",
            "gluon_curvature": "papers/gluon_curvature_artifact/",
            "baryogenesis": "papers/baryogenesis_lockin/",
        },
        "jarlskog_phenomenology": jarlskog_phenomenology(),
        "longitudinal_phenomenology": longitudinal_phenomenology(),
        "open_items": [
            "PMNS angle closure lighter than CKM (T10 wrapper; full Wolfenstein-style PMNS Jarlskog pending)",
            "Ledger Jarlskog vs PDG parameterization product differ by O(50×); correction ratio is a prediction",
            "Longitudinal correction is multiplicative scaffold; form-factor insertion in rare decays open",
            "ContinuumManyBodyQFTScaffold: renormalization/microcausality gaps flagged in PROOF_SPINE_MAP",
        ],
    }


def tex_phenomenology_table(w: dict) -> str:
    j = w["jarlskog_phenomenology"]
    l = w["longitudinal_phenomenology"]
    lines = [
        "% Auto-generated by scripts/hqiv_proof_spine_synthesis_export.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Illustrative phenomenology from the proved slots (comparison numerals outside Lean hypotheses).}",
        "\\begin{tabular}{lp{7.5cm}r}",
        "\\hline",
        "Quantity & Interpretation & Value \\\\",
        "\\hline",
        f"$J_{{\\rm ledger}}$ & CP-odd holonomy skew (proved) & ${j['J_ledger']:.5f}$ \\\\",
        f"$J_{{\\rm param}}$ & PDG $\\sin\\delta\\,\\sqrt{{|V_{{us}}|^2|V_{{cb}}|^4}}\\,\\prod\\cos\\theta$ & ${j['J_parameterization']:.2e}$ \\\\",
        f"$J_{{\\rm param}}/J_{{\\rm ledger}}$ & Proved positive correction ratio & ${j['correction_ratio']:.4f}$ ({j['percent_of_ledger']:.1f}\\%) \\\\",
        f"$\\Delta\\phi_{{\\rm imprint}}$ & $\\alpha\\log(\\phi+1)\\,\\Delta\\Omega$ at $m={REFERENCE_M}$ & ${l['imprint_phase_at_referenceM']:.4f}$ \\\\",
        f"$P_5'$ shift & Longitudinal factor $1+\\gamma|\\Delta\\phi|$ & ${l['p5_prime_relative_ppm']:.0f} ppm \\\\",
        f"$A_{{\\rm FB}}$ shift & Same factor on angular skeleton & ${l['a_fb_relative_ppm']:.0f} ppm \\\\",
        "\\hline",
        "\\end{tabular}",
        "\\label{tab:phenomenology-edges}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def tex_paper_map(w: dict) -> str:
    rows = [
        ("Flavor / CP / SMEFT", "Tier-3", "FlavorDifferentialReadout, ProofSpineInventory", "flavor\\_mixing\\_readout"),
        ("HEP decay multichannel", "Tier-2", "HepDecayReadout", "hep\\_decay\\_readout"),
        ("TUFT + SM Lagrangian", "Tier-1", "TuftShellChart, HopfShellBeltramiMassBridge", "tuft\\_sm\\_lagrangian"),
        ("Gluon curvature / glueball", "Strong", "GluonCurvatureArtifact, GluonSieversHopfBridge", "gluon\\_curvature\\_artifact"),
        ("Baryogenesis lock-in", "Cosmo", "BaryogenesisWitness", "baryogenesis\\_lockin"),
        ("This synthesis", "Overview", "proofSpineInventory\\_holds", "proof\\_spine\\_synthesis"),
    ]
    lines = [
        "% Auto-generated by scripts/hqiv_proof_spine_synthesis_export.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{HQIV targeted papers mapped to proof-spine phases.}",
        "\\begin{tabular}{llll}",
        "\\hline",
        "Domain & Tier & Lean spine & Paper folder \\\\",
        "\\hline",
    ]
    for r in rows:
        lines.append(" & ".join(r) + " \\\\")
    lines += ["\\hline", "\\end{tabular}", "\\label{tab:paper-map}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def write_generated(payload: dict) -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    (GENERATED / "phenomenology_edges.tex").write_text(tex_phenomenology_table(payload), encoding="utf-8")
    (GENERATED / "paper_map.tex").write_text(tex_paper_map(payload), encoding="utf-8")
    out_data = PAPER / "data" / "proof_spine_synthesis_witness.json"
    out_data.parent.mkdir(parents=True, exist_ok=True)
    out_data.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def bundle_scripts() -> Path:
    zip_path = PAPER / "scripts.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for name in ("hqiv_proof_spine_synthesis_export.py", "hqiv_flavor_mixing_export.py"):
            path = ROOT / "scripts" / name
            if path.exists():
                zf.write(path, arcname=name)
        zf.writestr(
            "README.md",
            "Run from repo root:\n\n  python3 scripts/hqiv_proof_spine_synthesis_export.py\n",
        )
    return zip_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=ROOT / "data" / "proof_spine_synthesis_witness.json")
    parser.add_argument("--no-tex", action="store_true")
    parser.add_argument("--no-zip", action="store_true")
    args = parser.parse_args()
    payload = build_witness()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {args.out}")
    if not args.no_tex:
        write_generated(payload)
        print(f"Wrote TeX under {GENERATED}")
    if not args.no_zip:
        print(f"Wrote {bundle_scripts()}")


if __name__ == "__main__":
    main()
