#!/usr/bin/env python3
"""Export flavor-mixing witness JSON and generated TeX tables (Lean-aligned slots)."""

from __future__ import annotations

import argparse
import json
import math
import zipfile
from datetime import datetime, timezone
from pathlib import Path

GAMMA = 2 / 5
CKM_US2 = GAMMA / 8
CKM_CD2 = GAMMA / 16
CKM_CB2 = GAMMA / 32
CP_SKEW = CKM_US2 - CKM_CB2
DELTA_CP = 3 * math.pi / 32
PMNS_DELTA_CP = math.pi / 5
P5_PRIME = 11 / 400
FB_ASYM = 8800 / 160121
BS_FLATNESS = 1 / (1 + CP_SKEW**2)
SIEVERS_DRAG = 3 / 2
SIEVERS_STIFFNESS = 6
SIEVERS_BACKREACTION = 1 / 4

# Reference comparison numerals (outside Lean proof hypotheses).
EXPERIMENTAL = {
    "delta_cp_ckm_deg": 68.5,
    "jarlskog_pdg": 3.08e-5,
    "bs_br_ppb": 2.8,
    "p5_prime_lfhcb": -0.047,
}

ALPHA = 3 / 5
REFERENCE_M = 4


def _shell_shape(m: int) -> float:
    x = m + 1
    return (1 / x) * (1 + ALPHA * math.log(x))


def _curvature_integral(n: int) -> float:
    if n <= 0:
        return 0.0
    return sum(_shell_shape(m) for m in range(n))


def _imprint_phase_at_reference_m() -> float:
    omega = lambda n: _curvature_integral(n) / _curvature_integral(REFERENCE_M)
    delta = omega(REFERENCE_M + 1) - omega(REFERENCE_M)
    phi = 2 * (REFERENCE_M + 1)
    return ALPHA * math.log(phi + 1) * delta


def _jarlskog_parameterization() -> float:
    t12 = math.asin(math.sqrt(CKM_US2))
    t23 = math.asin(math.sqrt(CKM_CB2))
    t13 = math.asin(math.sqrt(CKM_CB2))
    return (
        math.sin(t12) * math.sin(t23) * math.sin(t13) * math.sin(DELTA_CP)
        * math.cos(t12) * math.cos(t23) * math.cos(t13)
    )


def _jarlskog_phenomenology() -> dict:
    j_param = _jarlskog_parameterization()
    ratio = j_param / CP_SKEW
    return {
        "J_ledger": CP_SKEW,
        "J_parameterization": j_param,
        "correction_ratio": ratio,
        "percent_of_ledger": 100 * ratio,
    }


def _longitudinal_phenomenology() -> dict:
    phase = _imprint_phase_at_reference_m()
    corr = 1 + GAMMA * abs(phase)
    p5s = P5_PRIME * corr
    fbs = 2 * p5s / (1 + p5s**2)
    return {
        "imprint_phase_at_referenceM": phase,
        "correction_factor": corr,
        "p5_prime_ppm_shift": (p5s / P5_PRIME - 1) * 1e6,
        "a_fb_ppm_shift": (fbs / FB_ASYM - 1) * 1e6,
    }


def _repo_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / "lakefile.toml").exists() and (parent / "data").is_dir():
            return parent
    return Path(__file__).resolve().parents[1]


ROOT = _repo_root()
PAPER = ROOT / "papers" / "flavor_mixing_readout"
GENERATED = PAPER / "generated"


def build_witness() -> dict:
    j_phys = _jarlskog_phenomenology()
    l_phys = _longitudinal_phenomenology()
    return {
        "schema": "hqiv_flavor_mixing_witness_v2",
        "lean_module": "Hqiv.Physics.ProofSpineInventory",
        "python_module": "scripts/hqiv_flavor_mixing_export.py",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "ckm": {
            "V_us2": CKM_US2,
            "V_cd2": CKM_CD2,
            "V_cb2": CKM_CB2,
            "cp_odd_skew": CP_SKEW,
            "delta_cp": DELTA_CP,
            "delta_cp_deg": math.degrees(DELTA_CP),
            "jarlskog_ledger": CP_SKEW,
            "jarlskog_from_angles": j_phys["J_parameterization"],
            "jarlskog_correction_ratio": j_phys["correction_ratio"],
        },
        "pmns": {
            "sin2_theta12": 0.25,
            "sin2_theta23": 1 / 3,
            "delta_cp": PMNS_DELTA_CP,
            "normal_ordering": True,
        },
        "differential": {
            "p5_prime": P5_PRIME,
            "b_to_kstar_mumu_forward_backward": FB_ASYM,
            "bs_to_mumu_angular_flatness": BS_FLATNESS,
            "transverse_weight": 1 - FB_ASYM**2,
        },
        "sievers_bridge": {
            "fiber_drag_kappa7": SIEVERS_DRAG,
            "singlet_stiffness_kappa1": SIEVERS_STIFFNESS,
            "glueball_backreaction": SIEVERS_BACKREACTION,
            "cb_over_us": CKM_CB2 / CKM_US2,
        },
        "certificates": [
            "fanoHolonomyOverlapCertificate_holds",
            "assembleCkmHolonomyReadout",
            "ckmJarlskogFromAngles_eq_sin_delta_sin_cos_envelope",
            "assemblePMNSHolonomyReadout",
            "flavorDifferentialReadoutCertificate_holds",
            "flavorLongitudinalAmplitudeCertificate_holds",
            "gluonSieversHopfBridgeCertificate_holds",
            "proofSpineInventory_holds",
        ],
        "experimental_comparison": EXPERIMENTAL,
        "phenomenology": {
            "jarlskog": j_phys,
            "longitudinal_at_referenceM": l_phys,
        },
    }


def tex_ckm_table(w: dict) -> str:
    ckm = w["ckm"]
    lines = [
        "% Auto-generated by scripts/hqiv_flavor_mixing_export.py — do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{CKM holonomy ledger at lock-in ($\\gamma=2/5$, $\\delta_{\\rm CP}=3\\pi/32$).}",
        "\\begin{tabular}{lrr}",
        "\\hline",
        "Slot & HQIV value & PDG reference \\\\",
        "\\hline",
        f"$|V_{{us}}|^2$ & ${ckm['V_us2']:.6f}$ & $\\sim 0.05$ \\\\",
        f"$|V_{{cd}}|^2$ & ${ckm['V_cd2']:.6f}$ & $\\sim 0.025$ \\\\",
        f"$|V_{{cb}}|^2$ & ${ckm['V_cb2']:.6f}$ & $\\sim 0.012$ \\\\",
        f"$J_{{\\rm ledger}}$ & ${ckm['jarlskog_ledger']:.6f}$ & ${EXPERIMENTAL['jarlskog_pdg']:.2e}$ \\\\",
        f"$J_{{\\rm param}}/J_{{\\rm ledger}}$ & ${ckm['jarlskog_correction_ratio']:.4f}$ & --- \\\\",
        f"$\\delta_{{\\rm CP}}$ [deg] & ${ckm['delta_cp_deg']:.2f}$ & ${EXPERIMENTAL['delta_cp_ckm_deg']:.1f}$ \\\\",
        "\\hline",
        "\\end{tabular}",
        "\\label{tab:ckm-holonomy}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def tex_differential_table(w: dict) -> str:
    d = w["differential"]
    lines = [
        "% Auto-generated by scripts/hqiv_flavor_mixing_export.py — do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Rare-decay angular skeleton (Phase~4 differential readout).}",
        "\\begin{tabular}{lrr}",
        "\\hline",
        "Observable & HQIV slot & Experiment \\\\",
        "\\hline",
        f"$P_5'$ & ${d['p5_prime']:.5f}$ & ${EXPERIMENTAL['p5_prime_lfhcb']:.3f}$ \\\\",
        f"$A_{{\\rm FB}}(B\\to K^*\\mu\\mu)$ & ${d['b_to_kstar_mumu_forward_backward']:.6f}$ & --- \\\\",
        f"$\\mathcal{{F}}(B_s\\to\\mu\\mu)$ & ${d['bs_to_mumu_angular_flatness']:.6f}$ & --- \\\\",
        f"$\\mathcal{{BR}}(B_s\\to\\mu\\mu)$ [ppb] & slot & ${EXPERIMENTAL['bs_br_ppb']:.1f}$ \\\\",
        "\\hline",
        "\\end{tabular}",
        "\\label{tab:differential-readout}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def tex_phenomenology_table(w: dict) -> str:
    p = w["phenomenology"]
    j = p["jarlskog"]
    l = p["longitudinal_at_referenceM"]
    lines = [
        "% Auto-generated by scripts/hqiv_flavor_mixing_export.py — do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Illustrative phenomenology: Jarlskog correction ratio and longitudinal shifts at \\texttt{referenceM=4}.}",
        "\\begin{tabular}{lr}",
        "\\hline",
        "Quantity & Value \\\\",
        "\\hline",
        f"$J_{{\\rm param}}/J_{{\\rm ledger}}$ & ${j['correction_ratio']:.4f}$ ({j['percent_of_ledger']:.1f}\\% of ledger) \\\\",
        f"$1+\\gamma|\\Delta\\phi_{{\\rm imprint}}|$ & ${l['correction_factor']:.4f}$ \\\\",
        f"$P_5'$ longitudinal shift & ${l['p5_prime_ppm_shift']:.0f} ppm \\\\",
        f"$A_{{\\rm FB}}$ longitudinal shift & ${l['a_fb_ppm_shift']:.0f} ppm \\\\",
        "\\hline",
        "\\end{tabular}",
        "\\label{tab:phenomenology}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def tex_lean_module_map(w: dict) -> str:
    modules = [
        ("Phase 1", "FanoHolonomyOverlap", "Overlap weights, $\\delta_{\\rm CP}=3\\pi/32$"),
        ("Phase 2", "CkmHolonomyReadout", "CKM ledger, Jarlskog factorization"),
        ("Phase 3", "PMNSHolonomyReadout", "T10 PMNS, normal ordering"),
        ("Phase 4", "FlavorDifferentialReadout", "$P_5'$, $A_{\\rm FB}$, $B_s$ flatness"),
        ("Phase 4b", "FlavorLongitudinalAmplitudeBridge", "O-Maxwell phase-gradient correction"),
        ("Phase 5", "HiggsSelfCouplingReadout", "$\\lambda_3$, $\\kappa$ modifiers"),
        ("Phase 5b", "SMEFTDiscreteExporter", "Dimension-6 coefficient records"),
        ("Phase 6", "PartonCarrierEvolution", "PDF moments"),
        ("Phase 6b", "PatchScatteringUnitarity", "2$\\to$2 optical theorem"),
        ("Phase 7", "CosmologicalPerturbationReadout", "Friedmann witnesses"),
        ("Strong bridge", "GluonSieversHopfBridge", "Sievers $\\kappa_7/\\kappa_1$ $\\to$ $|V_{cb}|^2/|V_{us}|^2$"),
        ("Capstone", "ProofSpineInventory", "proofSpineInventory\\_holds"),
    ]
    lines = [
        "% Auto-generated by scripts/hqiv_flavor_mixing_export.py — do not edit by hand.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Self-reinforcing proof ladder: Lean module map.}",
        "\\begin{tabular}{llp{6.5cm}}",
        "\\hline",
        "Phase & Module & Content \\\\",
        "\\hline",
    ]
    for phase, mod, content in modules:
        lines.append(f"{phase} & \\texttt{{Hqiv.Physics.{mod}}} & {content} \\\\")
    lines += ["\\hline", "\\end{tabular}", "\\label{tab:lean-module-map}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def write_generated(payload: dict) -> None:
    GENERATED.mkdir(parents=True, exist_ok=True)
    tables = {
        "ckm_holonomy.tex": tex_ckm_table(payload),
        "differential_readout.tex": tex_differential_table(payload),
        "phenomenology_edges.tex": tex_phenomenology_table(payload),
        "lean_module_map.tex": tex_lean_module_map(payload),
    }
    for name, body in tables.items():
        (GENERATED / name).write_text(body, encoding="utf-8")
    (PAPER / "data" / "flavor_mixing_witness.json").parent.mkdir(parents=True, exist_ok=True)
    (PAPER / "data" / "flavor_mixing_witness.json").write_text(
        json.dumps(payload, indent=2) + "\n", encoding="utf-8"
    )


def bundle_scripts() -> Path:
    scripts_dir = ROOT / "scripts"
    export_script = scripts_dir / "hqiv_flavor_mixing_export.py"
    zip_path = PAPER / "scripts.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(export_script, arcname="hqiv_flavor_mixing_export.py")
        readme = (
            "# Flavor mixing export bundle\n\n"
            "Run from repo root:\n\n"
            "  python3 scripts/hqiv_flavor_mixing_export.py\n\n"
            "Build Lean spine:\n\n"
            "  lake build paper_flavor_mixing\n"
        )
        zf.writestr("README.md", readme)
    return zip_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Export HQIV flavor mixing witness + TeX tables")
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "data" / "flavor_mixing_witness.json",
        help="Output JSON path",
    )
    parser.add_argument("--no-tex", action="store_true", help="Skip TeX table generation")
    parser.add_argument("--no-zip", action="store_true", help="Skip scripts.zip bundle")
    args = parser.parse_args()
    payload = build_witness()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {args.out}")
    if not args.no_tex:
        write_generated(payload)
        print(f"Wrote TeX tables under {GENERATED}")
    if not args.no_zip:
        zp = bundle_scripts()
        print(f"Wrote {zp}")


if __name__ == "__main__":
    main()
