import Mathlib.Data.Real.Basic
import Mathlib.Data.Fin.Basic
import Mathlib.LinearAlgebra.Matrix.Defs
import Hqiv.Algebra.SO8ClosureAbstract
import Hqiv.Algebra.SMEmbedding
import Hqiv.Geometry.AlphaGammaForcedByLattice
import Hqiv.Physics.RapidityZetaPhaseBridge
import Hqiv.Physics.SM_GR_Unification

namespace Hqiv.Physics

abbrev GaugeMatrix := Matrix (Fin 8) (Fin 8) ℝ

/-- Canonical finite-dimensional HQIV gauge carrier: the span of the 28 `so(8)` generators. -/
def hqivGaugeCarrier : Submodule ℝ GaugeMatrix :=
  Submodule.span ℝ (Set.range Hqiv.so8Generator)

/--
Temporary package-level name for the carrier generated by the physical seed set `G₂ ∪ {Δ}`.

This is intentionally a lightweight alias to the already-built `so(8)` span package for now.
Once `Hqiv.Algebra.G2DeltaGeneratedLie` is promoted into the normal build graph, replace the body by
`(Hqiv.Algebra.g2DeltaGeneratedLie : Submodule ℝ GaugeMatrix)` and discharge the bridge theorem
against the heavy generated-Lie module directly.
-/
def hqivGeneratedGaugeCarrier : Submodule ℝ GaugeMatrix :=
  hqivGaugeCarrier

/--
Canonical package for the current finite-dimensional HQIV Yang-Mills-facing data.

This does not claim the analytic Yang-Mills existence/mass-gap theorem. It packages
the strongest algebraic and shell-dynamical objects already proved in the repo so
later theorems can target one stable object instead of many disconnected lemmas.
-/
structure HQIVYangMillsPackage where
  carrier : Submodule ℝ GaugeMatrix
  finrank_eq_28 : Module.finrank ℝ carrier = 28
  basisGenerator : Fin 28 → GaugeMatrix
  basis_mem_carrier : ∀ k : Fin 28, basisGenerator k ∈ carrier
  basis_linearIndependent : LinearIndependent ℝ basisGenerator
  basis_bracket_expansion :
    ∀ i j : Fin 28, ∃ f : Fin 28 → ℝ,
      Hqiv.lieBracket (basisGenerator i) (basisGenerator j) = ∑ k : Fin 28, f k • basisGenerator k
  g2_mem_carrier : ∀ k : Fin 14, Hqiv.Algebra.g2Generator k ∈ carrier
  phaseLift_mem_carrier : Hqiv.phaseLiftDelta ∈ carrier
  su2_gen_1_mem_carrier : Hqiv.Algebra.su2_L_gen_1 ∈ carrier
  su2_gen_2_mem_carrier : Hqiv.Algebra.su2_L_gen_2 ∈ carrier
  su2_gen_3_mem_carrier : Hqiv.Algebra.su2_L_gen_3 ∈ carrier
  hypercharge_mem_carrier : Hqiv.Algebra.hyperchargeGenerator ∈ carrier
  triality_rep_count_eq_three : Fintype.card Hqiv.Algebra.So8RepIndex = 3
  alpha_gamma_forced :
    Hqiv.alpha = (3 / 5 : ℝ) ∧ Hqiv.gamma_HQIV = (2 / 5 : ℝ) ∧ Hqiv.alpha + Hqiv.gamma_HQIV = 1
  rapidity_phase_alignment :
    ∀ φ t : ℝ, ∀ m : ℕ,
      Complex.I * φ * t * Hqiv.delta_theta_prime (m : ℝ) =
        Complex.I * (Hqiv.Geometry.polarAngleFromRapidity φ t m : Complex)
  unification_statement : Hqiv.YangMills_SM_GR_Unification_statement

theorem hqivGaugeCarrier_finrank_eq_28 :
    Module.finrank ℝ hqivGaugeCarrier = 28 := by
  simpa [hqivGaugeCarrier] using Hqiv.Algebra.so8_span_dim_eq_28

theorem hqivGeneratedGaugeCarrier_finrank_eq_28 :
    Module.finrank ℝ hqivGeneratedGaugeCarrier = 28 := by
  simpa [hqivGeneratedGaugeCarrier] using hqivGaugeCarrier_finrank_eq_28

theorem hqivGeneratedGaugeCarrier_eq_hqivGaugeCarrier :
    hqivGeneratedGaugeCarrier = hqivGaugeCarrier := by
  rfl

theorem su2_L_gen_1_mem_hqivGaugeCarrier :
    Hqiv.Algebra.su2_L_gen_1 ∈ hqivGaugeCarrier := by
  simpa [hqivGaugeCarrier, Hqiv.Algebra.su2_L_gen_1] using
    (Hqiv.Algebra.g2Generator_mem_span_so8 0)

theorem su2_L_gen_2_mem_hqivGaugeCarrier :
    Hqiv.Algebra.su2_L_gen_2 ∈ hqivGaugeCarrier := by
  simpa [hqivGaugeCarrier, Hqiv.Algebra.su2_L_gen_2] using
    (Hqiv.Algebra.g2Generator_mem_span_so8 1)

private theorem su2_L_gen_3_transpose_eq_neg :
    Hqiv.Algebra.su2_L_gen_3ᵀ = -Hqiv.Algebra.su2_L_gen_3 := by
  have h : Hqiv.Algebra.su2_L_gen_3ᵀ + Hqiv.Algebra.su2_L_gen_3 = 0 := by
    simpa [add_comm] using Hqiv.Algebra.su2_generators_in_so8.2.2
  exact eq_neg_iff_add_eq_zero.mpr h

theorem su2_L_gen_3_mem_hqivGaugeCarrier :
    Hqiv.Algebra.su2_L_gen_3 ∈ hqivGaugeCarrier := by
  rw [hqivGaugeCarrier, Hqiv.Algebra.span_so8Generators_eq_skewAdjointOne]
  rw [Hqiv.Algebra.mem_skewAdjointOne_iff]
  exact su2_L_gen_3_transpose_eq_neg

private theorem hyperchargeGenerator_transpose_eq_neg :
    Hqiv.Algebra.hyperchargeGeneratorᵀ = -Hqiv.Algebra.hyperchargeGenerator := by
  have h : Hqiv.Algebra.hyperchargeGeneratorᵀ + Hqiv.Algebra.hyperchargeGenerator = 0 := by
    simpa [add_comm] using Hqiv.Algebra.hyperchargeGenerator_antisymm
  exact eq_neg_iff_add_eq_zero.mpr h

theorem hyperchargeGenerator_mem_hqivGaugeCarrier :
    Hqiv.Algebra.hyperchargeGenerator ∈ hqivGaugeCarrier := by
  rw [hqivGaugeCarrier, Hqiv.Algebra.span_so8Generators_eq_skewAdjointOne]
  rw [Hqiv.Algebra.mem_skewAdjointOne_iff]
  exact hyperchargeGenerator_transpose_eq_neg

theorem su2_L_gen_1_mem_hqivGeneratedGaugeCarrier :
    Hqiv.Algebra.su2_L_gen_1 ∈ hqivGeneratedGaugeCarrier := by
  rw [hqivGeneratedGaugeCarrier_eq_hqivGaugeCarrier]
  exact su2_L_gen_1_mem_hqivGaugeCarrier

theorem su2_L_gen_2_mem_hqivGeneratedGaugeCarrier :
    Hqiv.Algebra.su2_L_gen_2 ∈ hqivGeneratedGaugeCarrier := by
  rw [hqivGeneratedGaugeCarrier_eq_hqivGaugeCarrier]
  exact su2_L_gen_2_mem_hqivGaugeCarrier

theorem su2_L_gen_3_mem_hqivGeneratedGaugeCarrier :
    Hqiv.Algebra.su2_L_gen_3 ∈ hqivGeneratedGaugeCarrier := by
  rw [hqivGeneratedGaugeCarrier_eq_hqivGaugeCarrier]
  exact su2_L_gen_3_mem_hqivGaugeCarrier

theorem hyperchargeGenerator_mem_hqivGeneratedGaugeCarrier :
    Hqiv.Algebra.hyperchargeGenerator ∈ hqivGeneratedGaugeCarrier := by
  rw [hqivGeneratedGaugeCarrier_eq_hqivGaugeCarrier]
  exact hyperchargeGenerator_mem_hqivGaugeCarrier

theorem so8Generator_mem_hqivGeneratedGaugeCarrier (k : Fin 28) :
    Hqiv.so8Generator k ∈ hqivGeneratedGaugeCarrier := by
  rw [hqivGeneratedGaugeCarrier_eq_hqivGaugeCarrier]
  exact Submodule.subset_span (Set.mem_range_self k)

noncomputable def hqivYangMillsPackage : HQIVYangMillsPackage where
  carrier := hqivGeneratedGaugeCarrier
  finrank_eq_28 := hqivGeneratedGaugeCarrier_finrank_eq_28
  basisGenerator := Hqiv.so8Generator
  basis_mem_carrier := by
    intro k
    exact so8Generator_mem_hqivGeneratedGaugeCarrier k
  basis_linearIndependent := Hqiv.so8_generators_linear_independent
  basis_bracket_expansion := by
    intro i j
    exact ⟨Hqiv.lieBracketCoeff i j, Hqiv.lieBracket_in_span i j⟩
  g2_mem_carrier := by
    intro k
    rw [hqivGeneratedGaugeCarrier_eq_hqivGaugeCarrier]
    simpa [hqivGaugeCarrier] using Hqiv.Algebra.g2Generator_mem_span_so8 k
  phaseLift_mem_carrier := by
    rw [hqivGeneratedGaugeCarrier_eq_hqivGaugeCarrier]
    simpa [hqivGaugeCarrier] using Hqiv.Algebra.phaseLiftDelta_mem_span_so8
  su2_gen_1_mem_carrier := su2_L_gen_1_mem_hqivGeneratedGaugeCarrier
  su2_gen_2_mem_carrier := su2_L_gen_2_mem_hqivGeneratedGaugeCarrier
  su2_gen_3_mem_carrier := su2_L_gen_3_mem_hqivGeneratedGaugeCarrier
  hypercharge_mem_carrier := hyperchargeGenerator_mem_hqivGeneratedGaugeCarrier
  triality_rep_count_eq_three := Hqiv.Algebra.three_generations_from_triality_reps
  alpha_gamma_forced := Hqiv.alpha_gamma_forced_pair
  rapidity_phase_alignment := by
    intro φ t m
    simpa using Hqiv.Physics.zetaHQIVTerm_phase_arg_eq_polarAngleFromRapidity φ t m
  unification_statement := Hqiv.HQIV_satisfies_YangMills_SM_GR_Unification

theorem hqivYangMillsPackage_carrier_eq_generated :
    hqivYangMillsPackage.carrier = hqivGeneratedGaugeCarrier := rfl

theorem hqivYangMillsPackage_nonempty : Nonempty HQIVYangMillsPackage :=
  ⟨hqivYangMillsPackage⟩

theorem hqivYangMillsPackage_basis_bracket
    (i j : Fin 28) :
    Hqiv.lieBracket (hqivYangMillsPackage.basisGenerator i) (hqivYangMillsPackage.basisGenerator j) =
      ∑ k : Fin 28, Hqiv.lieBracketCoeff i j k • hqivYangMillsPackage.basisGenerator k := by
  simpa [hqivYangMillsPackage]
    using (Hqiv.lieBracket_in_span i j)

theorem hqivYangMillsPackage_rapid_phase
    (φ t : ℝ) (m : ℕ) :
    Complex.I * φ * t * Hqiv.delta_theta_prime (m : ℝ) =
      Complex.I * (Hqiv.Geometry.polarAngleFromRapidity φ t m : Complex) :=
  hqivYangMillsPackage.rapidity_phase_alignment φ t m

end Hqiv.Physics
