import Mathlib.Data.List.Range
import Mathlib.Data.Rat.Defs
import Hqiv.Geometry.OctonionicLightCone

/-!
# Computable trapped inside ratio (formula-derived audit spine)

The semantic `ℝ` readout `metaHorizonTrappedInsideRatio` factorizes (proved in
`MetaHorizonTrappedPlanckMass`) as

```text
R_in(m) = V_cur(m) / V_cur(m_ref) · (m + 1) / (m_ref + 1)
```

where the Planck budget contributes **exactly** the linear shell-index ratio
(`trappedPlanckCumulativeBudget_eq_four_mul`).  The curvature volume
`V_cur(m) = Σ_{k≤m} shellShapeComputational k` uses the discrete imprint
`(1/(k+1)) · (1 + α log(k+1))` with `α = 3/5` and certified `ℚ` witnesses for
`log` at integer sample points (regenerated by
`scripts/hqiv_meta_horizon_inside_ratio_witness.py`).

This module is the **canonical computable definition** for nuclear drum argmin
(`AtomNucleusCurvatureShell`).  It replaces a pasted ratio lookup table.
-/

namespace Hqiv.Physics

open Hqiv

/-- Forced HQIV curvature ratio `α = 3/5` as exact `ℚ`. -/
def hqivAlphaQ : ℚ := (3 : ℚ) / 5

/-- Certified `ℚ` witness for `Real.log n` at integer shells `n = 1, …, 14`. -/
def realLogAtIntegerWitness : ℕ → ℚ
  | 0 => 0
  | 1 => 0
  | 2 => 532649477 / 768450759
  | 3 => 933118286 / 849360867
  | 4 => 1065298954 / 768450759
  | 5 => 959019984 / 595872619
  | 6 => 1438498102 / 802841077
  | 7 => 1705106794 / 876251555
  | 8 => 1614620653 / 776468403
  | 9 => 1866236572 / 849360867
  | 10 => 261763243 / 113682332
  | 11 => 2247838207 / 937421343
  | 12 => 2381851483 / 958527550
  | 13 => 2482788815 / 967967967
  | 14 => 2404513701 / 911125982
  | _ => 0

/-- Discrete curvature-imprint shell slice `(1/(m+1)) · (1 + α log(m+1))`. -/
def shellShapeComputational (m : ℕ) : ℚ :=
  (1 : ℚ) / (m + 1) * (1 + hqivAlphaQ * realLogAtIntegerWitness (m + 1))

/-- Cumulative curvature volume through shell `m` (inclusive). -/
def metaHorizonCurvatureVolumeComputational (m : ℕ) : ℚ :=
  (List.range (m + 1)).foldl (fun acc k => acc + shellShapeComputational k) 0

/-- Trapped inside ratio at `m_exc` relative to `m_ref` (computable spine).

Planck budget ratio `(m_exc+1)/(m_ref+1)` is folded in exactly (not pasted). -/
def metaHorizonInsideRatioComputational (m_exc m_ref : ℕ) : ℚ :=
  metaHorizonCurvatureVolumeComputational m_exc / metaHorizonCurvatureVolumeComputational m_ref *
    (m_exc + 1) / (m_ref + 1)

theorem realLogAtIntegerWitness_nonneg (n : ℕ) : 0 ≤ realLogAtIntegerWitness n := by
  unfold realLogAtIntegerWitness
  split <;> norm_num

theorem shellShapeComputational_pos (m : ℕ) : 0 < shellShapeComputational m := by
  unfold shellShapeComputational hqivAlphaQ
  have hx : 0 < (m + 1 : ℚ) := by exact_mod_cast show 0 < m + 1 from Nat.succ_pos m
  have hinner : 0 < 1 + hqivAlphaQ * realLogAtIntegerWitness (m + 1) := by
    have hmul : 0 ≤ hqivAlphaQ * realLogAtIntegerWitness (m + 1) :=
      mul_nonneg (by norm_num [hqivAlphaQ]) (realLogAtIntegerWitness_nonneg (m + 1))
    linarith
  exact mul_pos (one_div_pos.mpr hx) hinner

private theorem metaHorizonCurvatureVolumeComputational_succ (m : ℕ) :
    metaHorizonCurvatureVolumeComputational (m + 1) =
      metaHorizonCurvatureVolumeComputational m + shellShapeComputational (m + 1) := by
  simp [metaHorizonCurvatureVolumeComputational, List.range_succ, List.foldl]

theorem metaHorizonCurvatureVolumeComputational_pos (m : ℕ) :
    0 < metaHorizonCurvatureVolumeComputational m := by
  induction m with
  | zero =>
      simp [metaHorizonCurvatureVolumeComputational]
      exact shellShapeComputational_pos 0
  | succ m ih =>
      rw [metaHorizonCurvatureVolumeComputational_succ]
      exact add_pos ih (shellShapeComputational_pos (m + 1))

theorem metaHorizonInsideRatioComputational_self (m : ℕ) :
    metaHorizonInsideRatioComputational m m = 1 := by
  unfold metaHorizonInsideRatioComputational
  have hvol : metaHorizonCurvatureVolumeComputational m ≠ 0 :=
    ne_of_gt (metaHorizonCurvatureVolumeComputational_pos m)
  have hm : (m + 1 : ℚ) ≠ 0 := ne_of_gt (by exact_mod_cast Nat.succ_pos m)
  field_simp [hvol, hm]

theorem metaHorizonInsideRatioComputational_referenceM_self :
    metaHorizonInsideRatioComputational referenceM referenceM = 1 :=
  metaHorizonInsideRatioComputational_self referenceM

end Hqiv.Physics
