/-
Auto-generated by `scripts/gen_strong_color_su3_f_simp.py`.
`@[simp]` lemmas for the **nonzero** values of `colorSu3fStructure a b c` (54 oriented triples).
Zeros reduce from `simp [colorSu3fStructure]` alone. Regenerate:
  python3 scripts/gen_strong_color_su3_f_simp.py
-/

import Hqiv.Physics.StrongColorSu3ChartClosure

namespace Hqiv.Physics

@[simp] theorem colorSu3fStructure_simp_0_1_2 : colorSu3fStructure (0 : Fin 8) 1 2 = (1 : ℝ) := by
  have hneq : ¬((0 : Fin 8) = 1 ∨ (1 : Fin 8) = 2 ∨ (2 : Fin 8) = 0) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_0_2_1 : colorSu3fStructure (0 : Fin 8) 2 1 = (- ((1 : ℝ)) : ℝ) := by
  have hneq : ¬((0 : Fin 8) = 2 ∨ (2 : Fin 8) = 1 ∨ (1 : Fin 8) = 0) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_0_3_6 : colorSu3fStructure (0 : Fin 8) 3 6 = (1/2 : ℝ) := by
  have hneq : ¬((0 : Fin 8) = 3 ∨ (3 : Fin 8) = 6 ∨ (6 : Fin 8) = 0) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_0_4_5 : colorSu3fStructure (0 : Fin 8) 4 5 = (-1/2 : ℝ) := by
  have hneq : ¬((0 : Fin 8) = 4 ∨ (4 : Fin 8) = 5 ∨ (5 : Fin 8) = 0) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_0_5_4 : colorSu3fStructure (0 : Fin 8) 5 4 = (- ((-1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((0 : Fin 8) = 5 ∨ (5 : Fin 8) = 4 ∨ (4 : Fin 8) = 0) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_0_6_3 : colorSu3fStructure (0 : Fin 8) 6 3 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((0 : Fin 8) = 6 ∨ (6 : Fin 8) = 3 ∨ (3 : Fin 8) = 0) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_1_0_2 : colorSu3fStructure (1 : Fin 8) 0 2 = (- ((1 : ℝ)) : ℝ) := by
  have hneq : ¬((1 : Fin 8) = 0 ∨ (0 : Fin 8) = 2 ∨ (2 : Fin 8) = 1) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_1_2_0 : colorSu3fStructure (1 : Fin 8) 2 0 = (1 : ℝ) := by
  have hneq : ¬((1 : Fin 8) = 2 ∨ (2 : Fin 8) = 0 ∨ (0 : Fin 8) = 1) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_1_3_5 : colorSu3fStructure (1 : Fin 8) 3 5 = (1/2 : ℝ) := by
  have hneq : ¬((1 : Fin 8) = 3 ∨ (3 : Fin 8) = 5 ∨ (5 : Fin 8) = 1) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_1_4_6 : colorSu3fStructure (1 : Fin 8) 4 6 = (1/2 : ℝ) := by
  have hneq : ¬((1 : Fin 8) = 4 ∨ (4 : Fin 8) = 6 ∨ (6 : Fin 8) = 1) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_1_5_3 : colorSu3fStructure (1 : Fin 8) 5 3 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((1 : Fin 8) = 5 ∨ (5 : Fin 8) = 3 ∨ (3 : Fin 8) = 1) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_1_6_4 : colorSu3fStructure (1 : Fin 8) 6 4 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((1 : Fin 8) = 6 ∨ (6 : Fin 8) = 4 ∨ (4 : Fin 8) = 1) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_2_0_1 : colorSu3fStructure (2 : Fin 8) 0 1 = (1 : ℝ) := by
  have hneq : ¬((2 : Fin 8) = 0 ∨ (0 : Fin 8) = 1 ∨ (1 : Fin 8) = 2) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_2_1_0 : colorSu3fStructure (2 : Fin 8) 1 0 = (- ((1 : ℝ)) : ℝ) := by
  have hneq : ¬((2 : Fin 8) = 1 ∨ (1 : Fin 8) = 0 ∨ (0 : Fin 8) = 2) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_2_3_4 : colorSu3fStructure (2 : Fin 8) 3 4 = (1/2 : ℝ) := by
  have hneq : ¬((2 : Fin 8) = 3 ∨ (3 : Fin 8) = 4 ∨ (4 : Fin 8) = 2) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_2_4_3 : colorSu3fStructure (2 : Fin 8) 4 3 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((2 : Fin 8) = 4 ∨ (4 : Fin 8) = 3 ∨ (3 : Fin 8) = 2) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_2_5_6 : colorSu3fStructure (2 : Fin 8) 5 6 = (-1/2 : ℝ) := by
  have hneq : ¬((2 : Fin 8) = 5 ∨ (5 : Fin 8) = 6 ∨ (6 : Fin 8) = 2) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_2_6_5 : colorSu3fStructure (2 : Fin 8) 6 5 = (- ((-1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((2 : Fin 8) = 6 ∨ (6 : Fin 8) = 5 ∨ (5 : Fin 8) = 2) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_3_0_6 : colorSu3fStructure (3 : Fin 8) 0 6 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((3 : Fin 8) = 0 ∨ (0 : Fin 8) = 6 ∨ (6 : Fin 8) = 3) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_3_1_5 : colorSu3fStructure (3 : Fin 8) 1 5 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((3 : Fin 8) = 1 ∨ (1 : Fin 8) = 5 ∨ (5 : Fin 8) = 3) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_3_2_4 : colorSu3fStructure (3 : Fin 8) 2 4 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((3 : Fin 8) = 2 ∨ (2 : Fin 8) = 4 ∨ (4 : Fin 8) = 3) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_3_4_2 : colorSu3fStructure (3 : Fin 8) 4 2 = (1/2 : ℝ) := by
  have hneq : ¬((3 : Fin 8) = 4 ∨ (4 : Fin 8) = 2 ∨ (2 : Fin 8) = 3) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_3_4_7 : colorSu3fStructure (3 : Fin 8) 4 7 = (Real.sqrt 3 / 2 : ℝ) := by
  have hneq : ¬((3 : Fin 8) = 4 ∨ (4 : Fin 8) = 7 ∨ (7 : Fin 8) = 3) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_3_5_1 : colorSu3fStructure (3 : Fin 8) 5 1 = (1/2 : ℝ) := by
  have hneq : ¬((3 : Fin 8) = 5 ∨ (5 : Fin 8) = 1 ∨ (1 : Fin 8) = 3) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_3_6_0 : colorSu3fStructure (3 : Fin 8) 6 0 = (1/2 : ℝ) := by
  have hneq : ¬((3 : Fin 8) = 6 ∨ (6 : Fin 8) = 0 ∨ (0 : Fin 8) = 3) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_3_7_4 : colorSu3fStructure (3 : Fin 8) 7 4 = (- ((Real.sqrt 3 / 2 : ℝ)) : ℝ) := by
  have hneq : ¬((3 : Fin 8) = 7 ∨ (7 : Fin 8) = 4 ∨ (4 : Fin 8) = 3) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_4_0_5 : colorSu3fStructure (4 : Fin 8) 0 5 = (- ((-1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((4 : Fin 8) = 0 ∨ (0 : Fin 8) = 5 ∨ (5 : Fin 8) = 4) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_4_1_6 : colorSu3fStructure (4 : Fin 8) 1 6 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((4 : Fin 8) = 1 ∨ (1 : Fin 8) = 6 ∨ (6 : Fin 8) = 4) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_4_2_3 : colorSu3fStructure (4 : Fin 8) 2 3 = (1/2 : ℝ) := by
  have hneq : ¬((4 : Fin 8) = 2 ∨ (2 : Fin 8) = 3 ∨ (3 : Fin 8) = 4) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_4_3_2 : colorSu3fStructure (4 : Fin 8) 3 2 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((4 : Fin 8) = 3 ∨ (3 : Fin 8) = 2 ∨ (2 : Fin 8) = 4) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_4_3_7 : colorSu3fStructure (4 : Fin 8) 3 7 = (- ((Real.sqrt 3 / 2 : ℝ)) : ℝ) := by
  have hneq : ¬((4 : Fin 8) = 3 ∨ (3 : Fin 8) = 7 ∨ (7 : Fin 8) = 4) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_4_5_0 : colorSu3fStructure (4 : Fin 8) 5 0 = (-1/2 : ℝ) := by
  have hneq : ¬((4 : Fin 8) = 5 ∨ (5 : Fin 8) = 0 ∨ (0 : Fin 8) = 4) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_4_6_1 : colorSu3fStructure (4 : Fin 8) 6 1 = (1/2 : ℝ) := by
  have hneq : ¬((4 : Fin 8) = 6 ∨ (6 : Fin 8) = 1 ∨ (1 : Fin 8) = 4) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_4_7_3 : colorSu3fStructure (4 : Fin 8) 7 3 = (Real.sqrt 3 / 2 : ℝ) := by
  have hneq : ¬((4 : Fin 8) = 7 ∨ (7 : Fin 8) = 3 ∨ (3 : Fin 8) = 4) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_5_0_4 : colorSu3fStructure (5 : Fin 8) 0 4 = (-1/2 : ℝ) := by
  have hneq : ¬((5 : Fin 8) = 0 ∨ (0 : Fin 8) = 4 ∨ (4 : Fin 8) = 5) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_5_1_3 : colorSu3fStructure (5 : Fin 8) 1 3 = (1/2 : ℝ) := by
  have hneq : ¬((5 : Fin 8) = 1 ∨ (1 : Fin 8) = 3 ∨ (3 : Fin 8) = 5) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_5_2_6 : colorSu3fStructure (5 : Fin 8) 2 6 = (- ((-1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((5 : Fin 8) = 2 ∨ (2 : Fin 8) = 6 ∨ (6 : Fin 8) = 5) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_5_3_1 : colorSu3fStructure (5 : Fin 8) 3 1 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((5 : Fin 8) = 3 ∨ (3 : Fin 8) = 1 ∨ (1 : Fin 8) = 5) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_5_4_0 : colorSu3fStructure (5 : Fin 8) 4 0 = (- ((-1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((5 : Fin 8) = 4 ∨ (4 : Fin 8) = 0 ∨ (0 : Fin 8) = 5) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_5_6_2 : colorSu3fStructure (5 : Fin 8) 6 2 = (-1/2 : ℝ) := by
  have hneq : ¬((5 : Fin 8) = 6 ∨ (6 : Fin 8) = 2 ∨ (2 : Fin 8) = 5) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_5_6_7 : colorSu3fStructure (5 : Fin 8) 6 7 = (Real.sqrt 3 / 2 : ℝ) := by
  have hneq : ¬((5 : Fin 8) = 6 ∨ (6 : Fin 8) = 7 ∨ (7 : Fin 8) = 5) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_5_7_6 : colorSu3fStructure (5 : Fin 8) 7 6 = (- ((Real.sqrt 3 / 2 : ℝ)) : ℝ) := by
  have hneq : ¬((5 : Fin 8) = 7 ∨ (7 : Fin 8) = 6 ∨ (6 : Fin 8) = 5) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_6_0_3 : colorSu3fStructure (6 : Fin 8) 0 3 = (1/2 : ℝ) := by
  have hneq : ¬((6 : Fin 8) = 0 ∨ (0 : Fin 8) = 3 ∨ (3 : Fin 8) = 6) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_6_1_4 : colorSu3fStructure (6 : Fin 8) 1 4 = (1/2 : ℝ) := by
  have hneq : ¬((6 : Fin 8) = 1 ∨ (1 : Fin 8) = 4 ∨ (4 : Fin 8) = 6) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_6_2_5 : colorSu3fStructure (6 : Fin 8) 2 5 = (-1/2 : ℝ) := by
  have hneq : ¬((6 : Fin 8) = 2 ∨ (2 : Fin 8) = 5 ∨ (5 : Fin 8) = 6) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_6_3_0 : colorSu3fStructure (6 : Fin 8) 3 0 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((6 : Fin 8) = 3 ∨ (3 : Fin 8) = 0 ∨ (0 : Fin 8) = 6) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_6_4_1 : colorSu3fStructure (6 : Fin 8) 4 1 = (- ((1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((6 : Fin 8) = 4 ∨ (4 : Fin 8) = 1 ∨ (1 : Fin 8) = 6) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_6_5_2 : colorSu3fStructure (6 : Fin 8) 5 2 = (- ((-1/2 : ℝ)) : ℝ) := by
  have hneq : ¬((6 : Fin 8) = 5 ∨ (5 : Fin 8) = 2 ∨ (2 : Fin 8) = 6) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_6_5_7 : colorSu3fStructure (6 : Fin 8) 5 7 = (- ((Real.sqrt 3 / 2 : ℝ)) : ℝ) := by
  have hneq : ¬((6 : Fin 8) = 5 ∨ (5 : Fin 8) = 7 ∨ (7 : Fin 8) = 6) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_6_7_5 : colorSu3fStructure (6 : Fin 8) 7 5 = (Real.sqrt 3 / 2 : ℝ) := by
  have hneq : ¬((6 : Fin 8) = 7 ∨ (7 : Fin 8) = 5 ∨ (5 : Fin 8) = 6) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_7_3_4 : colorSu3fStructure (7 : Fin 8) 3 4 = (Real.sqrt 3 / 2 : ℝ) := by
  have hneq : ¬((7 : Fin 8) = 3 ∨ (3 : Fin 8) = 4 ∨ (4 : Fin 8) = 7) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_7_4_3 : colorSu3fStructure (7 : Fin 8) 4 3 = (- ((Real.sqrt 3 / 2 : ℝ)) : ℝ) := by
  have hneq : ¬((7 : Fin 8) = 4 ∨ (4 : Fin 8) = 3 ∨ (3 : Fin 8) = 7) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_7_5_6 : colorSu3fStructure (7 : Fin 8) 5 6 = (Real.sqrt 3 / 2 : ℝ) := by
  have hneq : ¬((7 : Fin 8) = 5 ∨ (5 : Fin 8) = 6 ∨ (6 : Fin 8) = 7) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

@[simp] theorem colorSu3fStructure_simp_7_6_5 : colorSu3fStructure (7 : Fin 8) 6 5 = (- ((Real.sqrt 3 / 2 : ℝ)) : ℝ) := by
  have hneq : ¬((7 : Fin 8) = 6 ∨ (6 : Fin 8) = 5 ∨ (5 : Fin 8) = 7) := by decide
  dsimp [colorSu3fStructure, hneq]
  simp [colorSu3PermSign, min3, max3, mid3]
  simp [colorSu3fSorted]

end Hqiv.Physics
