/-
Auto-generated by `scripts/gen_strong_color_su3_lie_chart_law.py`.
Regenerate: `python3 scripts/gen_strong_color_su3_lie_chart_law.py`
-/

import Hqiv.Physics.StrongColorSu3LieCertificate
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.Tactic.Ring
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.FinCases

/-!
# Strong color: global `su(3)` chart Lie law (certificate layer)

Proves `∀ a b : Fin 8, [T^a,T^b] = Complex.I • ∑_c f^{abc} T^c` for `T^a = λ^a/2` on the `3×3` chart.

Imports the optional `@[simp]` table `StrongColorSu3fStructureSimp` (via `StrongColorSu3LieCertificate`);
build with `lake build HQIVStrongColorSu3Certificate`.
-/

open scoped BigOperators
open Complex Finset Matrix
open Hqiv.Algebra Hqiv.Physics

namespace Hqiv.Physics

noncomputable section

set_option maxHeartbeats 8000000

theorem colorSu3fStructure_self_eq_zero (a c : Fin 8) : colorSu3fStructure a a c = (0 : ℝ) := by
  dsimp [colorSu3fStructure]
  simp

theorem colorHalfGellMannFull_f_sum_self (a : Fin 8) :
    (∑ c : Fin 8, (colorSu3fStructure a a c : ℂ) • colorHalfGellMannFull c) = 0 := by
  refine Finset.sum_eq_zero ?_
  intro c _
  rw [colorSu3fStructure_self_eq_zero]
  simp

/-- Diagonal case (0,0). -/
lemma colorLieChartBracket_0_0 :
    lieBracketMat₃ (colorHalfGellMannFull (0 : Fin 8)) (colorHalfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (0 : Fin 8) (0 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  rw [colorHalfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat₃, smul_zero]

/-- Off-diagonal case (0,1). -/
lemma colorLieChartBracket_0_1 :
    lieBracketMat₃ (colorHalfGellMannFull (0 : Fin 8)) (colorHalfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (0 : Fin 8) (1 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,2). -/
lemma colorLieChartBracket_0_2 :
    lieBracketMat₃ (colorHalfGellMannFull (0 : Fin 8)) (colorHalfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (0 : Fin 8) (2 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,3). -/
lemma colorLieChartBracket_0_3 :
    lieBracketMat₃ (colorHalfGellMannFull (0 : Fin 8)) (colorHalfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (0 : Fin 8) (3 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,4). -/
lemma colorLieChartBracket_0_4 :
    lieBracketMat₃ (colorHalfGellMannFull (0 : Fin 8)) (colorHalfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (0 : Fin 8) (4 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,5). -/
lemma colorLieChartBracket_0_5 :
    lieBracketMat₃ (colorHalfGellMannFull (0 : Fin 8)) (colorHalfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (0 : Fin 8) (5 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,6). -/
lemma colorLieChartBracket_0_6 :
    lieBracketMat₃ (colorHalfGellMannFull (0 : Fin 8)) (colorHalfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (0 : Fin 8) (6 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (0,7). -/
lemma colorLieChartBracket_0_7 :
    lieBracketMat₃ (colorHalfGellMannFull (0 : Fin 8)) (colorHalfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (0 : Fin 8) (7 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,0). -/
lemma colorLieChartBracket_1_0 :
    lieBracketMat₃ (colorHalfGellMannFull (1 : Fin 8)) (colorHalfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (1 : Fin 8) (0 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (1,1). -/
lemma colorLieChartBracket_1_1 :
    lieBracketMat₃ (colorHalfGellMannFull (1 : Fin 8)) (colorHalfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (1 : Fin 8) (1 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  rw [colorHalfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat₃, smul_zero]

/-- Off-diagonal case (1,2). -/
lemma colorLieChartBracket_1_2 :
    lieBracketMat₃ (colorHalfGellMannFull (1 : Fin 8)) (colorHalfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (1 : Fin 8) (2 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,3). -/
lemma colorLieChartBracket_1_3 :
    lieBracketMat₃ (colorHalfGellMannFull (1 : Fin 8)) (colorHalfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (1 : Fin 8) (3 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,4). -/
lemma colorLieChartBracket_1_4 :
    lieBracketMat₃ (colorHalfGellMannFull (1 : Fin 8)) (colorHalfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (1 : Fin 8) (4 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,5). -/
lemma colorLieChartBracket_1_5 :
    lieBracketMat₃ (colorHalfGellMannFull (1 : Fin 8)) (colorHalfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (1 : Fin 8) (5 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,6). -/
lemma colorLieChartBracket_1_6 :
    lieBracketMat₃ (colorHalfGellMannFull (1 : Fin 8)) (colorHalfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (1 : Fin 8) (6 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (1,7). -/
lemma colorLieChartBracket_1_7 :
    lieBracketMat₃ (colorHalfGellMannFull (1 : Fin 8)) (colorHalfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (1 : Fin 8) (7 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,0). -/
lemma colorLieChartBracket_2_0 :
    lieBracketMat₃ (colorHalfGellMannFull (2 : Fin 8)) (colorHalfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (2 : Fin 8) (0 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,1). -/
lemma colorLieChartBracket_2_1 :
    lieBracketMat₃ (colorHalfGellMannFull (2 : Fin 8)) (colorHalfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (2 : Fin 8) (1 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (2,2). -/
lemma colorLieChartBracket_2_2 :
    lieBracketMat₃ (colorHalfGellMannFull (2 : Fin 8)) (colorHalfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (2 : Fin 8) (2 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  rw [colorHalfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat₃, smul_zero]

/-- Off-diagonal case (2,3). -/
lemma colorLieChartBracket_2_3 :
    lieBracketMat₃ (colorHalfGellMannFull (2 : Fin 8)) (colorHalfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (2 : Fin 8) (3 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,4). -/
lemma colorLieChartBracket_2_4 :
    lieBracketMat₃ (colorHalfGellMannFull (2 : Fin 8)) (colorHalfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (2 : Fin 8) (4 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,5). -/
lemma colorLieChartBracket_2_5 :
    lieBracketMat₃ (colorHalfGellMannFull (2 : Fin 8)) (colorHalfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (2 : Fin 8) (5 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,6). -/
lemma colorLieChartBracket_2_6 :
    lieBracketMat₃ (colorHalfGellMannFull (2 : Fin 8)) (colorHalfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (2 : Fin 8) (6 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (2,7). -/
lemma colorLieChartBracket_2_7 :
    lieBracketMat₃ (colorHalfGellMannFull (2 : Fin 8)) (colorHalfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (2 : Fin 8) (7 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,0). -/
lemma colorLieChartBracket_3_0 :
    lieBracketMat₃ (colorHalfGellMannFull (3 : Fin 8)) (colorHalfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (3 : Fin 8) (0 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,1). -/
lemma colorLieChartBracket_3_1 :
    lieBracketMat₃ (colorHalfGellMannFull (3 : Fin 8)) (colorHalfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (3 : Fin 8) (1 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,2). -/
lemma colorLieChartBracket_3_2 :
    lieBracketMat₃ (colorHalfGellMannFull (3 : Fin 8)) (colorHalfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (3 : Fin 8) (2 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (3,3). -/
lemma colorLieChartBracket_3_3 :
    lieBracketMat₃ (colorHalfGellMannFull (3 : Fin 8)) (colorHalfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (3 : Fin 8) (3 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  rw [colorHalfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat₃, smul_zero]

/-- Off-diagonal case (3,4). -/
lemma colorLieChartBracket_3_4 :
    lieBracketMat₃ (colorHalfGellMannFull (3 : Fin 8)) (colorHalfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (3 : Fin 8) (4 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,5). -/
lemma colorLieChartBracket_3_5 :
    lieBracketMat₃ (colorHalfGellMannFull (3 : Fin 8)) (colorHalfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (3 : Fin 8) (5 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,6). -/
lemma colorLieChartBracket_3_6 :
    lieBracketMat₃ (colorHalfGellMannFull (3 : Fin 8)) (colorHalfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (3 : Fin 8) (6 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (3,7). -/
lemma colorLieChartBracket_3_7 :
    lieBracketMat₃ (colorHalfGellMannFull (3 : Fin 8)) (colorHalfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (3 : Fin 8) (7 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,0). -/
lemma colorLieChartBracket_4_0 :
    lieBracketMat₃ (colorHalfGellMannFull (4 : Fin 8)) (colorHalfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (4 : Fin 8) (0 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,1). -/
lemma colorLieChartBracket_4_1 :
    lieBracketMat₃ (colorHalfGellMannFull (4 : Fin 8)) (colorHalfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (4 : Fin 8) (1 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,2). -/
lemma colorLieChartBracket_4_2 :
    lieBracketMat₃ (colorHalfGellMannFull (4 : Fin 8)) (colorHalfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (4 : Fin 8) (2 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,3). -/
lemma colorLieChartBracket_4_3 :
    lieBracketMat₃ (colorHalfGellMannFull (4 : Fin 8)) (colorHalfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (4 : Fin 8) (3 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (4,4). -/
lemma colorLieChartBracket_4_4 :
    lieBracketMat₃ (colorHalfGellMannFull (4 : Fin 8)) (colorHalfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (4 : Fin 8) (4 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  rw [colorHalfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat₃, smul_zero]

/-- Off-diagonal case (4,5). -/
lemma colorLieChartBracket_4_5 :
    lieBracketMat₃ (colorHalfGellMannFull (4 : Fin 8)) (colorHalfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (4 : Fin 8) (5 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,6). -/
lemma colorLieChartBracket_4_6 :
    lieBracketMat₃ (colorHalfGellMannFull (4 : Fin 8)) (colorHalfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (4 : Fin 8) (6 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (4,7). -/
lemma colorLieChartBracket_4_7 :
    lieBracketMat₃ (colorHalfGellMannFull (4 : Fin 8)) (colorHalfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (4 : Fin 8) (7 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,0). -/
lemma colorLieChartBracket_5_0 :
    lieBracketMat₃ (colorHalfGellMannFull (5 : Fin 8)) (colorHalfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (5 : Fin 8) (0 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,1). -/
lemma colorLieChartBracket_5_1 :
    lieBracketMat₃ (colorHalfGellMannFull (5 : Fin 8)) (colorHalfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (5 : Fin 8) (1 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,2). -/
lemma colorLieChartBracket_5_2 :
    lieBracketMat₃ (colorHalfGellMannFull (5 : Fin 8)) (colorHalfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (5 : Fin 8) (2 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,3). -/
lemma colorLieChartBracket_5_3 :
    lieBracketMat₃ (colorHalfGellMannFull (5 : Fin 8)) (colorHalfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (5 : Fin 8) (3 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,4). -/
lemma colorLieChartBracket_5_4 :
    lieBracketMat₃ (colorHalfGellMannFull (5 : Fin 8)) (colorHalfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (5 : Fin 8) (4 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (5,5). -/
lemma colorLieChartBracket_5_5 :
    lieBracketMat₃ (colorHalfGellMannFull (5 : Fin 8)) (colorHalfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (5 : Fin 8) (5 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  rw [colorHalfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat₃, smul_zero]

/-- Off-diagonal case (5,6). -/
lemma colorLieChartBracket_5_6 :
    lieBracketMat₃ (colorHalfGellMannFull (5 : Fin 8)) (colorHalfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (5 : Fin 8) (6 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (5,7). -/
lemma colorLieChartBracket_5_7 :
    lieBracketMat₃ (colorHalfGellMannFull (5 : Fin 8)) (colorHalfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (5 : Fin 8) (7 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,0). -/
lemma colorLieChartBracket_6_0 :
    lieBracketMat₃ (colorHalfGellMannFull (6 : Fin 8)) (colorHalfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (6 : Fin 8) (0 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,1). -/
lemma colorLieChartBracket_6_1 :
    lieBracketMat₃ (colorHalfGellMannFull (6 : Fin 8)) (colorHalfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (6 : Fin 8) (1 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,2). -/
lemma colorLieChartBracket_6_2 :
    lieBracketMat₃ (colorHalfGellMannFull (6 : Fin 8)) (colorHalfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (6 : Fin 8) (2 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,3). -/
lemma colorLieChartBracket_6_3 :
    lieBracketMat₃ (colorHalfGellMannFull (6 : Fin 8)) (colorHalfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (6 : Fin 8) (3 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,4). -/
lemma colorLieChartBracket_6_4 :
    lieBracketMat₃ (colorHalfGellMannFull (6 : Fin 8)) (colorHalfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (6 : Fin 8) (4 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (6,5). -/
lemma colorLieChartBracket_6_5 :
    lieBracketMat₃ (colorHalfGellMannFull (6 : Fin 8)) (colorHalfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (6 : Fin 8) (5 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (6,6). -/
lemma colorLieChartBracket_6_6 :
    lieBracketMat₃ (colorHalfGellMannFull (6 : Fin 8)) (colorHalfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (6 : Fin 8) (6 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  rw [colorHalfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat₃, smul_zero]

/-- Off-diagonal case (6,7). -/
lemma colorLieChartBracket_6_7 :
    lieBracketMat₃ (colorHalfGellMannFull (6 : Fin 8)) (colorHalfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (6 : Fin 8) (7 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,0). -/
lemma colorLieChartBracket_7_0 :
    lieBracketMat₃ (colorHalfGellMannFull (7 : Fin 8)) (colorHalfGellMannFull (0 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (7 : Fin 8) (0 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,1). -/
lemma colorLieChartBracket_7_1 :
    lieBracketMat₃ (colorHalfGellMannFull (7 : Fin 8)) (colorHalfGellMannFull (1 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (7 : Fin 8) (1 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,2). -/
lemma colorLieChartBracket_7_2 :
    lieBracketMat₃ (colorHalfGellMannFull (7 : Fin 8)) (colorHalfGellMannFull (2 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (7 : Fin 8) (2 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,3). -/
lemma colorLieChartBracket_7_3 :
    lieBracketMat₃ (colorHalfGellMannFull (7 : Fin 8)) (colorHalfGellMannFull (3 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (7 : Fin 8) (3 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,4). -/
lemma colorLieChartBracket_7_4 :
    lieBracketMat₃ (colorHalfGellMannFull (7 : Fin 8)) (colorHalfGellMannFull (4 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (7 : Fin 8) (4 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,5). -/
lemma colorLieChartBracket_7_5 :
    lieBracketMat₃ (colorHalfGellMannFull (7 : Fin 8)) (colorHalfGellMannFull (5 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (7 : Fin 8) (5 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Off-diagonal case (7,6). -/
lemma colorLieChartBracket_7_6 :
    lieBracketMat₃ (colorHalfGellMannFull (7 : Fin 8)) (colorHalfGellMannFull (6 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (7 : Fin 8) (6 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  unfold lieBracketMat₃
  ext i j
  fin_cases i <;> fin_cases j <;> {
    simp [Matrix.mul_apply, Fin.sum_univ_three, Fin.sum_univ_eight, Matrix.of_apply,
      colorHalfGellMannFull, colorGellMannLambdaFull, colorGellMannLambda1, colorGellMannLambda2,
      colorGellMannLambda3, colorGellMannLambda4, colorGellMannLambda5, colorGellMannLambda6,
      colorGellMannLambda7, colorGellMannLambda8]
    try simp [colorSu3fStructure, colorSu3PermSign, min3, mid3, max3, colorSu3fSorted]
    try simp_rw [Real.sq_sqrt (show (0 : ℝ) ≤ (3 : ℝ) by norm_num)]
    try simp only [Complex.ext_iff, pow_two, Complex.mul_re, Complex.mul_im, Complex.I_re, Complex.I_im,
      sub_eq_add_neg]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring_nf
    all_goals try simp (disch := norm_num) [Real.sq_sqrt]
    all_goals try ring
  }

/-- Diagonal case (7,7). -/
lemma colorLieChartBracket_7_7 :
    lieBracketMat₃ (colorHalfGellMannFull (7 : Fin 8)) (colorHalfGellMannFull (7 : Fin 8)) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure (7 : Fin 8) (7 : Fin 8) c : ℂ) • colorHalfGellMannFull c := by
  rw [colorHalfGellMannFull_f_sum_self]
  ext i j
  simp [lieBracketMat₃, smul_zero]


/-- Global chart Lie law for half–Gell–Mann generators (all 64 ordered pairs). -/
theorem colorHalfGellMannFull_lieBracket_eq_I_smul_f_sum (a b : Fin 8) :
    lieBracketMat₃ (colorHalfGellMannFull a) (colorHalfGellMannFull b) =
      Complex.I • ∑ c : Fin 8, (colorSu3fStructure a b c : ℂ) • colorHalfGellMannFull c := by
  fin_cases a <;> fin_cases b
  · exact colorLieChartBracket_0_0
  · exact colorLieChartBracket_0_1
  · exact colorLieChartBracket_0_2
  · exact colorLieChartBracket_0_3
  · exact colorLieChartBracket_0_4
  · exact colorLieChartBracket_0_5
  · exact colorLieChartBracket_0_6
  · exact colorLieChartBracket_0_7
  · exact colorLieChartBracket_1_0
  · exact colorLieChartBracket_1_1
  · exact colorLieChartBracket_1_2
  · exact colorLieChartBracket_1_3
  · exact colorLieChartBracket_1_4
  · exact colorLieChartBracket_1_5
  · exact colorLieChartBracket_1_6
  · exact colorLieChartBracket_1_7
  · exact colorLieChartBracket_2_0
  · exact colorLieChartBracket_2_1
  · exact colorLieChartBracket_2_2
  · exact colorLieChartBracket_2_3
  · exact colorLieChartBracket_2_4
  · exact colorLieChartBracket_2_5
  · exact colorLieChartBracket_2_6
  · exact colorLieChartBracket_2_7
  · exact colorLieChartBracket_3_0
  · exact colorLieChartBracket_3_1
  · exact colorLieChartBracket_3_2
  · exact colorLieChartBracket_3_3
  · exact colorLieChartBracket_3_4
  · exact colorLieChartBracket_3_5
  · exact colorLieChartBracket_3_6
  · exact colorLieChartBracket_3_7
  · exact colorLieChartBracket_4_0
  · exact colorLieChartBracket_4_1
  · exact colorLieChartBracket_4_2
  · exact colorLieChartBracket_4_3
  · exact colorLieChartBracket_4_4
  · exact colorLieChartBracket_4_5
  · exact colorLieChartBracket_4_6
  · exact colorLieChartBracket_4_7
  · exact colorLieChartBracket_5_0
  · exact colorLieChartBracket_5_1
  · exact colorLieChartBracket_5_2
  · exact colorLieChartBracket_5_3
  · exact colorLieChartBracket_5_4
  · exact colorLieChartBracket_5_5
  · exact colorLieChartBracket_5_6
  · exact colorLieChartBracket_5_7
  · exact colorLieChartBracket_6_0
  · exact colorLieChartBracket_6_1
  · exact colorLieChartBracket_6_2
  · exact colorLieChartBracket_6_3
  · exact colorLieChartBracket_6_4
  · exact colorLieChartBracket_6_5
  · exact colorLieChartBracket_6_6
  · exact colorLieChartBracket_6_7
  · exact colorLieChartBracket_7_0
  · exact colorLieChartBracket_7_1
  · exact colorLieChartBracket_7_2
  · exact colorLieChartBracket_7_3
  · exact colorLieChartBracket_7_4
  · exact colorLieChartBracket_7_5
  · exact colorLieChartBracket_7_6
  · exact colorLieChartBracket_7_7

end -- noncomputable section

end Hqiv.Physics
