import Hqiv.Foundation.PhaseLiftForcing
import Mathlib.Tactic

/-!
# ClosureConstraint — the abstract closure requirement on the carrier

The last structural requirement of the spine: adjoining the phase-lift `Δ` to the
derivation algebra `𝔤₂` of the imaginary directions must **close**, under the Lie
bracket, to the full skew-symmetric algebra `𝔰𝔬(8)` of the carrier. We capture this
as a small typed interface plus its dimension bookkeeping, so that the concrete
`G₂ ∪ {Δ} ⇒ 𝔰𝔬(8)` certificate downstream is exhibited as **one witness** of the
abstract requirement rather than a free-standing premise.

No `sorry`, no `axiom`: the dimension counts are `ℕ` facts and the interface is a
plain structure.
-/

namespace Hqiv.Foundation

/-- **Abstract carrier-closure data.**

A bundle asserting that a derivation seed (dimension `derivationSeedDim`) together with
a phase-lift generator, all living in the skew-symmetric algebra of an `carrierDim`-channel
carrier, Lie-generates a space of dimension `generatedDim` equal to the full
`soDim carrierDim`. The concrete realization is `Hqiv.G2_plus_Delta_closes_to_so8`. -/
structure CarrierClosure where
  /-- Number of channels of the carrier. -/
  carrierDim : ℕ
  /-- Dimension of the imaginary-direction derivation seed (`𝔤₂`). -/
  derivationSeedDim : ℕ
  /-- The phase-lift contributes one distinguished 2-plane generator. -/
  phaseLiftDim : ℕ
  /-- Dimension of the Lie algebra generated by seed `∪` phase-lift. -/
  generatedDim : ℕ
  /-- The closure requirement: the generated algebra is all of `𝔰𝔬(carrierDim)`. -/
  closes : generatedDim = soDim carrierDim

/-- **The HQIV instance** of the closure requirement: an 8-channel carrier, a
14-dimensional `𝔤₂` seed, a single phase-lift, closing to the 28-dimensional `𝔰𝔬(8)`. -/
def hqivCarrierClosure : CarrierClosure where
  carrierDim := carrierMultiplicity
  derivationSeedDim := g2Dim
  phaseLiftDim := 1
  generatedDim := soDim carrierMultiplicity
  closes := rfl

theorem hqivCarrierClosure_carrierDim : hqivCarrierClosure.carrierDim = 8 :=
  carrierMultiplicity_eq_eight

theorem hqivCarrierClosure_generatedDim : hqivCarrierClosure.generatedDim = 28 :=
  soDim_carrier

theorem hqivCarrierClosure_seedDim : hqivCarrierClosure.derivationSeedDim = 14 :=
  g2Dim_eq_fourteen

/-- **The closure is dimension-consistent with the branching** `28 = 14 + 7 + 7`:
the seed (14) plus the two imaginary 7-reps fill the generated algebra exactly. -/
theorem hqivCarrierClosure_branch :
    hqivCarrierClosure.generatedDim
      = hqivCarrierClosure.derivationSeedDim + imaginaryDim + imaginaryDim := by
  simp only [hqivCarrierClosure]
  exact so8_branch_g2

/-! ## Witness-bearing closure interface

`CarrierClosure` above is dimension bookkeeping only: it asserts `generatedDim = soDim carrierDim`
but says nothing about *which* concrete Lie algebra realizes the closure. The certificate that
actually proves the closure — `G₂ ∪ {Δ}` Lie-generating all of `𝔰𝔬(8)` — lives in the matrix
layer (`Hqiv.Algebra.g2DeltaGeneratedLie_eq_so8LieSubalgebra`) and must not be pulled into this
lightweight, matrix-free file.

We therefore expose an abstract **witness-bearing** interface here: a `CarrierClosure` together with
an opaque `LieCertificate : Prop` and a proof of it. The concrete HQIV instance
(`Hqiv.Algebra.hqivCarrierClosureWitness`) instantiates `LieCertificate` with the genuine Lie-closure
theorem, turning the previous "a comment says this is the witness" relationship into an actual formal
dependency, while keeping the foundation layer free of matrices and `native_decide`. -/

/-- **Carrier closure certified by an explicit Lie-closure proposition.**

The dimension bookkeeping (`toCarrierClosure`) plus an opaque proposition `LieCertificate` that
certifies the closure is realized by a concrete Lie algebra, together with a proof that it holds. -/
structure CarrierClosureWitness where
  /-- The underlying dimension bookkeeping. -/
  toCarrierClosure : CarrierClosure
  /-- The concrete closure proposition (e.g. `g2DeltaGeneratedLie = so8LieSubalgebra`). -/
  LieCertificate : Prop
  /-- A proof that the closure proposition holds. -/
  lie_certified : LieCertificate

namespace CarrierClosureWitness

/-- The dimension closure still holds for any witness. -/
theorem closes (W : CarrierClosureWitness) :
    W.toCarrierClosure.generatedDim = soDim W.toCarrierClosure.carrierDim :=
  W.toCarrierClosure.closes

/-- Carrier-channel count of the witness. -/
def carrierDim (W : CarrierClosureWitness) : ℕ := W.toCarrierClosure.carrierDim

/-- Generated-algebra dimension of the witness. -/
def generatedDim (W : CarrierClosureWitness) : ℕ := W.toCarrierClosure.generatedDim

end CarrierClosureWitness

end Hqiv.Foundation
