--| End-to-end narrative spine: light cone → … → Dojo YM/NS problem wiring.
--| Build: `lake build HQIVStory` — see `AGENTS/REFACTOR_END_TO_END_PLAN.md`
--| Octonion Lie DOF (28 = dim so(8), backbone `sorry` in Story; proof: `HQIVSO8Closure` / `Hqiv.SO8Closure`)
--| Gap inventory: `MassGapWiring`; completion `MassGapCompletionBundle`; partial QFT builder `MassGapCompletionScaffold`
--| O-Maxwell + patch QM ↔ Dojo slot hub: `Hqiv.Story.OMaxwellQMToDojoSlot` (`OMaxwellQMToDojo` names); continuum hub `Hqiv.Physics.LightConeMaxwellQFTBridge`
--| Millennium bridge patch slot: `MillenniumBridgePatchVacuum` (`MillenniumG`, `PatchHilbert`, `patchVacuum`, `patchHilbertPatchBridge`); patch↔toy Hilbert bridge `PatchToWightmanToyHilbertBridge`; patch Wightman+ladder Hamiltonian scaffold `MillenniumBridgePatchPoincareWightman`
--| `FiniteMassSpectrum` vs zero Hamiltonian: `MillenniumFiniteMassObstruction`, `MillenniumBridgeToyWitness.not_FiniteMassSpectrum_of_wightman_hamiltonian_eq_zero`
--| Dojo YM interface witness: `QuantumYangMillsHQIVInterface` / `QuantumYangMillsFromPatchHQIV` (patch jet `hqivPatchJetOperatorValuedDistribution`); obligations `hqiv_promotion_obligations_hqivInterfaceQFT` in `YMRemainingObligations`; ladder scale decoupled via `LadderGapCandidateWell` so `Chapter08` can import PatchHQIV (`MassGap.nonempty_hqivInterface_quantumYangMills`)
--| Dynamic-well theorem shell: `WellShapeFromDynamics`
import Hqiv.Story.MassGapWiring
import Hqiv.Story.MassGapCompletionBundle
import Hqiv.Story.MassGapCompletionScaffold
import Hqiv.Story.WellShapeFromDynamics
import Hqiv.Story.YMInputsFromWellDynamics
import Hqiv.Story.DiscreteOMaxwellToYMInputs
import Hqiv.Story.DiscreteOMaxwellHQIVInstance
import Hqiv.Story.OMaxwellQMToDojoSlot
import Hqiv.Story.SketchesConsumedLadderWell
import Hqiv.Story.YMBridgeProvedHelpers
import Hqiv.Story.MillenniumBridgePatchVacuum
import Hqiv.Story.PatchToWightmanToyHilbertBridge
import Hqiv.Story.MillenniumBridgePatchPoincareWightman
import Hqiv.Story.NonabelianSO8SmearedPatchField
--| HQIV-facing Dojo `QuantumYangMillsTheory` interface witness (not mass gap)
import Hqiv.Story.QuantumYangMillsHQIVInterface
import Hqiv.Story.MillenniumBridgeToyWitness
import Hqiv.Story.MillenniumFiniteMassObstruction
import Hqiv.Story.GaugeGroupFromHQIVSketch
import Hqiv.Story.HQIVGaugeConstructionBlueprint
import Hqiv.Story.YMRemainingObligations
import Hqiv.Story.NSRemainingObligations
import Hqiv.Story.HQIVDissipativeBridge
import Hqiv.Story.PlasticSpiralInterceptCoverage
import Hqiv.Story.HigherOrderArityDiagonalSymmetry
import Hqiv.Story.ArityMirrorCancellationBridge
import Hqiv.Story.ArityFTADecomposition
import Hqiv.Story.PlasticTwistedEulerCharacter
import Hqiv.Story.S3PrimeAxisCancellation
import Hqiv.Story.S3DiscretePrimeAxisSampling
import Hqiv.Story.S3EulerSO4PrimeAxisBridge
import Hqiv.Story.PlasticCriticalLineBridge
import Hqiv.Story.PlasticPhaseBalanceImpliesReHalf
import Hqiv.Story.NearDiagonalThreeCubes
import Hqiv.Story.PlasticLatticePhaseImpliesZetaZero
import Hqiv.Story.PlasticRHBridgeFinal
import Hqiv.Story.S3ToZetaBridge
import Hqiv.Story.S3RHZeroSetBridge
import Hqiv.Story.S3SurvivorsForcePhase
import Hqiv.Story.S3RHObligationEquivalence
import Hqiv.Story.S3QuaternionOrientation
import Hqiv.Story.S3ZeroEquationEquivalence
import Hqiv.Story.S3ZetaAlgebraicLock
import Hqiv.Story.S3ZetaResidualModel
import Hqiv.Story.S3CenteredResidualModel
import Hqiv.Story.S3FortyFiveProjection
import Hqiv.Story.S3AlphaDimUnitSplitProjection
import Hqiv.Story.S3PoleZeroChannel
import Hqiv.Story.S3ComplexResidualModel
import Hqiv.Story.S3RotationRigidity
import Hqiv.Story.S3MirroredTwiddlePair
import Hqiv.Story.S3CubicPlasticTwiddle
import Hqiv.Story.S3HigherTwiddleFactorizationProbe
import Hqiv.Story.S3SemiprimeExplicitFormulaMediation
import Hqiv.Story.S3TwiddleFrameCrossTalkLaw
import Hqiv.Story.S3TwiddleChannelPresentation
import Hqiv.Story.S3StripMirrorPeakWitness
import Hqiv.Story.S3TwiddleRigidityForcesLine
import Hqiv.Story.S3DeltaOrbitOffStrip
import Hqiv.Story.S3ZetaClosedForm
import Hqiv.Story.S3RHDischarge
import Hqiv.Story.S3SO4InteriorWitness
import Hqiv.Story.S3SO4ZetaProjectionClosedForm
import Hqiv.Story.S3HarmonicDeltaEvenOrbit
import Hqiv.Story.S3ZetaAxisRotationProjection
import Hqiv.Story.S3InteriorStripHClosedForm
import Hqiv.Story.S3InteriorPathA
import Hqiv.Story.S3ZeroProducingOrbits
import Hqiv.Story.S3InteriorPathE
import Hqiv.Story.S3InteriorAssemblyNonvanishingAttack
import Hqiv.Story.S3ZeroOrbitPathE
import Hqiv.Story.S3PathCHolonomy
import Hqiv.Story.S3StripRollingProjection
import Hqiv.Story.S3AnalyticStripLift
import Hqiv.Story.S3AnalyticStripClassification
import Hqiv.Story.S3CriticalLineCarrierBundle
import Hqiv.Story.S3HarmonicShellZeroCounting
import Hqiv.Story.S3HopfJKUnitCircleZeroReadout
import Hqiv.Story.S3CriticalCirclePhaseCancellation
import Hqiv.Story.S3CumulativeHarmonicPhase
import Hqiv.Story.S3GoldbachAnnulusPairCountPiBudget
import Hqiv.Story.S3GoldbachAnnulusAssociatorCap
import Hqiv.Story.S3GoldbachAnnulusAssociatorGlobalBudget
import Hqiv.Story.S3ModelGuidedZeroLocator
import Hqiv.Story.S3ModelGuidedLocationBound
import Hqiv.Story.S3GoldbachHolomorphicWeightBridge
import Hqiv.Story.S3GoldbachPartitionGeneratingFunction
import Hqiv.Story.S3GoldbachPerronContourRemainder
import Hqiv.Story.S3ExplicitFormulaLocationBridge
import Hqiv.Story.S3HopfJKEulerPrimeCircleCounting
import Hqiv.Story.S3CountableCircleFill
import Hqiv.Story.S3FareyRayInterpolation
import Hqiv.Story.S3FareyTwiddleLanding
import Hqiv.Story.S3ExplicitFormulaPrimePhaseCoincidence
import Hqiv.Story.S3ExplicitFormulaPrimeLatticeTruncation
import Hqiv.Story.S3ThetaPartitionTwiddleAddress
import Hqiv.Story.S3DiagonalZeroAddressCapstone
import Hqiv.Story.S3TwiddleAddressConstructiveZero
import Hqiv.Story.S3EscapingDiagonalTwiddleComplexification
import Hqiv.Story.S3ComplexifiedTwiddleHalfSlopeBridge
import Hqiv.Story.S3DeepTwiddlePoleLadder
import Hqiv.Story.S3DiagonalSphereTwiddlePermutations
import Hqiv.Story.S3QuaternionZetaTwiddleMultisetInvariance
import Hqiv.Story.S3HopfShellHolonomy
import Hqiv.Story.S3OrbitVsPointwiseGap
import Hqiv.Story.S3SigmaReadoutScope
import Hqiv.Story.S3ZeroQuadrupletOrbit
import Hqiv.Story.S3HeatFlowArrowNoBackprojection
import Hqiv.Story.S3DBNLatticeInheritance
import Hqiv.Story.S3DBNDiscreteContinuumComparison
import Hqiv.Story.S3DBNConstantPort
import Hqiv.Story.S3DiscreteContinuumOffLineWeightBridge
import Hqiv.Story.S3ZetaGoldbachTailBandCrossChannelBridge
import Hqiv.Story.S3TangentOrbitCriticalLine
import Hqiv.Story.S3EulerSpectralCancellation
import Hqiv.Story.S3SpectralResonanceChanneling
import Hqiv.Story.S3VerticalAxisRigidity
import Hqiv.Story.S3SameHeightOrbitCollapse
import Hqiv.Story.S3PolarProjectionCollapse
import Hqiv.Story.S3ZeroHolonomyGoldbachChain
import Hqiv.Story.S3HolonomyLadderNoSkip
import Hqiv.Story.S3SO4FrameZetaThreePinch
import Hqiv.Story.S3RHGoldbachGeometricBridgeCapstone
import Hqiv.Story.S3DeltaHarmonicDischargeBridge
import Hqiv.Story.S3PhysicsInvarianceDischargeBridge
import Hqiv.Story.S3StripRapidityEquatorIdentification
import Hqiv.Story.S3ScaleOrbitMulModHolonomy
import Hqiv.Story.S3HarmonicMulModHolonomy
import Hqiv.Story.S3HopfMulModTransport
import Hqiv.Story.S3MulModSO4LiePromotion
import Hqiv.Story.S3HarmonicCascadeZetaRegularization
import Hqiv.Story.S3HarmonicMulModCubeTriangulationBridge
import Hqiv.Story.S3HarmonicMulModCubeLieTransportBridge
--| Mul-mod BSD channel: coefficient/L-series fit + prefix Hecke; 45°/90° rotation dual (FE line vs convergence wall)
import Hqiv.Story.S3MulModBSDCoefficientBridge
import Hqiv.Story.S3MulModBSDConvergenceRotationBridge
import Hqiv.Story.S3HarmonicHolonomyCriticalLineFrontier
import Hqiv.Story.S3MulModBSDRotationDualCapstone
import Hqiv.Story.S3MulModHodgeRotationBridge
import Hqiv.Story.S3RotationAdjointHeightPhaseBSDBridge
import Hqiv.Story.S3SigmaTRotationVectorBridge
import Hqiv.Story.S3OnLineSpectralProductHeightPhaseLadder
import Hqiv.Story.S3OnLineZeroHeightPhaseCouplingBridge
import Hqiv.Story.S3OnLineZeroHeightPhaseSlotBudgetAttack
import Hqiv.Story.S3OnLineSharedSlotFiveDischarge
import Hqiv.Story.S3OnLineTripletSixGapSpectralAttack
import Hqiv.Story.S3OnLineTripletSixRollingGapSpectralBridge
import Hqiv.Story.S3OnLineCascadeTripletHeightPhaseBridge
import Hqiv.Story.S3OffLineAssociatorAdjointAttack
import Hqiv.Story.S3HarmonicHolonomyAssociatorPerturb
import Hqiv.Story.S3HarmonicHolonomyAssociatorAdjointAttack
import Hqiv.Story.S3TwinMulModTwiddleBridge
import Hqiv.Story.S3DeltaHolonomyMulModAnchorBridge
import Hqiv.Story.S3PlasticRatioTwinTwiddleAnchor
import Hqiv.Story.S3MidpointEulerSoeBridge
import Hqiv.Story.S3MidpointConstructiveSpectralSlope
import Hqiv.Story.S3SoeSpectralBuild
import Hqiv.Story.S3MidpointEckmannHiltonSoe
import Hqiv.Story.S3MidpointSO4DeltaOrbit
import Hqiv.Story.S3SO4SquareOrbitCollision
import Hqiv.Story.S3OrbitEnergyNonExtinctionBridge
import Hqiv.Story.S3TuftNestedFrameTower
import Hqiv.Story.S3DiophantineTransformer
import Hqiv.Story.S3OctonionicAssociatorChannel
import Hqiv.Story.S3OctonionS7TorsionCancellation
import Hqiv.Story.S3SpecFrameFunctorSieve
import Hqiv.Story.S3HyperanalyticContinuationRoutes
import Hqiv.Story.S3HypercomplexResidualModel
import Hqiv.Story.S3OffLineOrbitMisalignmentDischarge
import Hqiv.Story.S3LogPhaseEdge
import Hqiv.Story.S3LogPhaseGoldbachHalfSlopeComparison
import Hqiv.Story.S3LogPhaseZetaCouplingFrontier
import Hqiv.Story.S3LogPhaseInteriorAssemblyBridge
import Hqiv.Story.S3LogPhaseGoldbachCouplingParity
import Hqiv.Story.S3LogPhaseProbeCertified
import Hqiv.Story.S3GoldbachSlotPhaseCouplingBridge
import Hqiv.Story.S3GoldbachSlotPhaseOffLineHarmonicBridge
import Hqiv.Story.S3GoldbachAnnulusTwinPrimeSweep
import Hqiv.Story.S3GoldbachGapOneActivationBudget
import Hqiv.Story.S3SquareOrbitGapOneBridge
import Hqiv.Story.S3InscribedSquareOrbitBridge
import Hqiv.Story.S3InscribedSquareBridgeIdentity
import Hqiv.Story.S3StructuredCascadeGlobalExistence
import Hqiv.Story.S3GoldbachGapOneDensityPressure
import Hqiv.Story.S3LogPhaseAssociatorCoupling
import Hqiv.Story.S3PrimalitySlotDecoupling
import Hqiv.Story.S3DivisorPairingSelectsSquares
import Hqiv.Story.S3TwiddleResidualMoebius
import Hqiv.Story.S3FiniteSymmetryCannotIsolatePrimes
import Hqiv.Story.S3SixPolesResidual
import Hqiv.Story.S3EulerCircleLatticePoints
import Hqiv.Story.S3ExplicitFormulaDualitySlot
import Hqiv.Story.S3WeilPositivityCriterion
import Hqiv.Story.S3ExplicitFormulaIdentity
import Hqiv.Story.S3ClosureDeltaLiftBridge
import Hqiv.Story.S3HarmonicPrimeZetaPath
import Hqiv.Story.S3LogExpTrigReadoutBridge
import Hqiv.Story.S3EulerExplicitFormulaLocalization
import Hqiv.Story.S3ConstructionsEquivalent
