import Hqiv.Story.S3SO4InteriorWitness
import Hqiv.Story.S3TangentOrbitCriticalLine
import Hqiv.Story.S3EulerSpectralCancellation

/-!
# Resonance channeling and the SO(4) spectral-line transformer

This module combines the three proven layers --- tangency
(`S3TangentOrbitCriticalLine`), the twiddle/equator factorization
(`S3ZetaClosedForm` / `S3SO4InteriorWitness`), and spectral cancellation
(`S3EulerSpectralCancellation`) --- into the sharpest *forcing* statements
available without assuming RH.

## 1. The cancellation is collective: no single prime, no finite truncation

Each Euler factor `1 − p^{−s}` is nonvanishing on the **entire** right
half-plane `Re s > 0` (`euler_factor_base_ne_zero_right_half`): a single
prime line can only vanish at `Re s = 0` (where `p^{−s}` is unimodular).
Hence every finite spectral truncation `∏_{p∈F}(1 − p^{−s})` is nonzero on
the strip (`finite_spectral_truncation_ne_zero`).  A zeta zero is a
*collective* cancellation: it needs all primes at once.

## 2. The two-channel dichotomy: where the cancellation is absorbed

On the strip, `ζ = h · (2σ−1)/√2` off the line.  At any nontrivial zero the
collective cancellation must be absorbed by exactly one of two channels
(`resonance_channeling_dichotomy`):

* **on the line** (`Re ρ = 1/2`): the geometric equator factor vanishes and
  the tangent is unimodular --- the fixed SO(4) channel absorbs it;
* **off the line** (`Re ρ ≠ 1/2`): the equator factor is *nonzero*, so the
  factorization forces the free assembly to vanish,
  `interiorStripH ρ = 0` (`offline_zero_forces_assembly_vanish`).

RH is exactly the statement that the second channel never fires:
`geometric_channel_absorption_iff_RH` proves
`InteriorAssemblyNonzeroAtNontrivialZerosOffLine interiorStripH ↔ RH`.

## 3. The SO(4) spectral-line transformer

"For a given `n`, locate the zero": the transformer is the spectral line
`so4SpectralLine n s = n^{−s}`.  Its provable laws:

* modulus law `‖n^{−s}‖ = n^{−Re s}` (`so4SpectralLine_norm`);
* **FE pairing**: `‖n^{−s}‖·‖n^{−(1−s)}‖ = 1/n` for *all* `s`
  (`so4SpectralLine_fe_product`) --- every FE pair of lines multiplies to
  exactly `1/n`, unconditionally;
* **geometric-mean locator**: the two paired lines are *equal* iff
  `Re s = 1/2` (`so4SpectralLine_geometric_mean_iff`) --- the critical line
  is where each spectral line sits at the geometric mean of its FE pair;
* **square-root-weight locator**: `‖n^{−s}‖² = 1/n ↔ Re s = 1/2`
  (`so4SpectralLine_sq_weight`);
* multiplicativity `(ab)^{−s} = a^{−s}·b^{−s}` (`so4SpectralLine_mul`) and
  prime factorization of every line: every `n ≥ 2` is a multiple of a prime
  and its line factors through that prime's line
  (`spectral_line_prime_factorization`) --- the transformer is generated by
  the prime lines.

## 4. The forcing capstone (honest form)

`RH_iff_zero_spectral_weights`: **RH is equivalent to the statement that at
every nontrivial zero, every spectral line carries exactly square-root
weight** `‖n^{−ρ}‖² = 1/n`.  And `zero_line_characterizations` shows the
three locators agree at every zero: vanishing equator twiddle ⇔ unimodular
tangent ⇔ all lines at square-root weight ⇔ `Re ρ = 1/2`.

**Honest scope.**  The dichotomy and the locators are unconditional.  What
they jointly prove is that RH has been *reduced to a single channel
statement*: the free assembly `interiorStripH` never absorbs a collective
cancellation.  Forcing the zeros onto `Re = 1/2` outright would require
showing the off-line channel cannot fire --- that is the named frontier
`InteriorAssemblyNonzeroAtNontrivialZerosOffLine`, now proved *equivalent*
to RH, not merely sufficient for it.
-/

namespace Hqiv.Story

open Complex Filter

noncomputable section

/-! ## 1. The cancellation is collective -/

/-- A single prime line never cancels on the right half-plane: for
`Re s > 0` (in particular on the whole critical strip),
`1 − p^{−s} ≠ 0`, since `‖p^{−s}‖ = p^{−Re s} < 1`. -/
theorem euler_factor_base_ne_zero_right_half {s : ℂ} (hs : 0 < s.re)
    (p : Nat.Primes) : (1 : ℂ) - (p : ℂ) ^ (-s) ≠ 0 := by
  have hp2 : (2 : ℝ) ≤ (p : ℕ) := by exact_mod_cast p.prop.two_le
  have hppos : (0 : ℝ) < ((p : ℕ) : ℝ) := by linarith
  have hnorm : ‖(p : ℂ) ^ (-s)‖ = ((p : ℕ) : ℝ) ^ (-s).re := by
    rw [show ((p : ℂ)) = ((((p : ℕ) : ℝ)) : ℂ) by push_cast; rfl]
    exact Complex.norm_cpow_eq_rpow_re_of_pos hppos (-s)
  have hlt : ‖(p : ℂ) ^ (-s)‖ < 1 := by
    rw [hnorm, Complex.neg_re]
    exact Real.rpow_lt_one_of_one_lt_of_neg (by linarith) (by linarith)
  intro h
  have : (p : ℂ) ^ (-s) = 1 := by linear_combination -h
  rw [this] at hlt
  simp at hlt

/-- No finite spectral truncation can produce the cancellation: every finite
partial product of prime-phase factors is nonzero for `Re s > 0`.  The zero
needs all primes at once. -/
theorem finite_spectral_truncation_ne_zero {s : ℂ} (hs : 0 < s.re)
    (F : Finset Nat.Primes) :
    ∏ p ∈ F, ((1 : ℂ) - (p : ℂ) ^ (-s)) ≠ 0 :=
  Finset.prod_ne_zero_iff.mpr fun p _ => euler_factor_base_ne_zero_right_half hs p

/-! ## 2. The two-channel dichotomy -/

/-- **Off-line zeros force the free channel to vanish.**  At a nontrivial
zero with `Re ρ ≠ 1/2`, the equator factor is nonzero, so the strip
factorization `ζ = h · (2σ−1)/√2` forces `interiorStripH ρ = 0`: the free
assembly must absorb the full collective cancellation. -/
theorem offline_zero_forces_assembly_vanish {ρ : ℂ}
    (h : IsNontrivialZetaZero ρ) (hσ : ρ.re ≠ (1 / 2 : ℝ)) :
    interiorStripH ρ = 0 := by
  obtain ⟨h0, h1⟩ := nontrivial_zero_open_strip ρ h
  rw [interiorStripH_eq_zeta_div_critical_off_line h0 h1 hσ
    evenOddSO4Assembly_of_odd_channel, h.1, zero_div]

/-- **Resonance channeling dichotomy.**  At every nontrivial zero the
collective cancellation is absorbed by exactly one of two channels: on the
line the geometric equator factor vanishes (with unimodular tangent); off
the line the equator factor survives and the free assembly is forced to
zero. -/
theorem resonance_channeling_dichotomy (ρ : ℂ) (h : IsNontrivialZetaZero ρ) :
    (ρ.re = (1 / 2 : ℝ) ∧ so4CriticalFactor ρ = 0 ∧
      Complex.normSq (projTangent ρ) = 1) ∨
    (ρ.re ≠ (1 / 2 : ℝ) ∧ so4CriticalFactor ρ ≠ 0 ∧ interiorStripH ρ = 0) := by
  obtain ⟨h0, h1⟩ := nontrivial_zero_open_strip ρ h
  by_cases hσ : ρ.re = (1 / 2 : ℝ)
  · exact Or.inl ⟨hσ, (so4CriticalFactor_zero_iff ρ).mpr hσ,
      (normSq_projTangent_eq_one_iff h0 h1).mpr hσ⟩
  · exact Or.inr ⟨hσ, so4CriticalFactor_ne_zero_off_line hσ,
      offline_zero_forces_assembly_vanish h hσ⟩

/-- **RH = the geometric channel always absorbs.**  The named frontier is
not merely sufficient for RH; it is *equivalent* to it. -/
theorem geometric_channel_absorption_iff_RH :
    InteriorAssemblyNonzeroAtNontrivialZerosOffLine interiorStripH ↔
      RiemannHypothesis := by
  constructor
  · exact RiemannHypothesis_of_SO4_interior_witness
  · intro hRH s hz hσ
    exact absurd (hRH s hz.1 hz.2.1 hz.2.2) hσ

/-! ## 3. The SO(4) spectral-line transformer -/

/-- The spectral line of `n`: the `n`-th term of the Dirichlet spectrum,
`n^{−s}`.  Every `n` rides the SO(4) projection through this line. -/
noncomputable def so4SpectralLine (n : ℕ) (s : ℂ) : ℂ := (n : ℂ) ^ (-s)

/-- Modulus law: `‖n^{−s}‖ = n^{−Re s}`.  The line's weight reads only the
projection coordinate `Re s` — σ-blindness again, at the spectrum level. -/
theorem so4SpectralLine_norm {n : ℕ} (hn : 0 < n) (s : ℂ) :
    ‖so4SpectralLine n s‖ = (n : ℝ) ^ (-s.re) := by
  unfold so4SpectralLine
  rw [show ((n : ℂ)) = (((n : ℝ)) : ℂ) by push_cast; rfl,
    Complex.norm_cpow_eq_rpow_re_of_pos (by exact_mod_cast hn) (-s),
    Complex.neg_re]

/-- **FE pairing of spectral lines**: for every `s` (unconditionally),
`‖n^{−s}‖ · ‖n^{−(1−s)}‖ = 1/n`.  Each functional-equation pair of lines
multiplies to exactly the reciprocal. -/
theorem so4SpectralLine_fe_product {n : ℕ} (hn : 0 < n) (s : ℂ) :
    ‖so4SpectralLine n s‖ * ‖so4SpectralLine n (1 - s)‖ = (n : ℝ)⁻¹ := by
  have hpos : (0 : ℝ) < n := by exact_mod_cast hn
  rw [so4SpectralLine_norm hn, so4SpectralLine_norm hn, ← Real.rpow_add hpos,
    show -s.re + -(1 - s).re = -1 by
      simp [Complex.sub_re, Complex.one_re]; ring,
    Real.rpow_neg_one]

/-- Injectivity of `b ^ ·` for base `b > 1` (helper). -/
theorem rpow_left_inj_of_one_lt {b x y : ℝ} (hb : 1 < b)
    (h : b ^ x = b ^ y) : x = y :=
  le_antisymm ((Real.rpow_le_rpow_left_iff hb).mp h.le)
    ((Real.rpow_le_rpow_left_iff hb).mp h.ge)

/-- **Geometric-mean locator**: the two FE-paired lines of `n` are *equal*
exactly on the critical line.  `Re s = 1/2` is where every spectral line
sits at the geometric mean `1/√n` of its FE pair. -/
theorem so4SpectralLine_geometric_mean_iff {n : ℕ} (hn : 2 ≤ n) (s : ℂ) :
    ‖so4SpectralLine n s‖ = ‖so4SpectralLine n (1 - s)‖ ↔
      s.re = (1 / 2 : ℝ) := by
  have hpos : 0 < n := by omega
  have hb : (1 : ℝ) < n := by exact_mod_cast hn
  have h2 : (1 - s).re = 1 - s.re := by simp [Complex.sub_re, Complex.one_re]
  rw [so4SpectralLine_norm hpos, so4SpectralLine_norm hpos, h2]
  constructor
  · intro h
    have := rpow_left_inj_of_one_lt hb h
    linarith
  · intro h
    rw [h]
    norm_num

/-- **Square-root-weight locator**: `‖n^{−s}‖² = 1/n` exactly on the
critical line.  Given `n`, the transformer locates the unique vertical line
where `n`'s spectral weight is its square root. -/
theorem so4SpectralLine_sq_weight {n : ℕ} (hn : 2 ≤ n) {s : ℂ} :
    ‖so4SpectralLine n s‖ ^ 2 = (n : ℝ)⁻¹ ↔ s.re = (1 / 2 : ℝ) := by
  have hpos : (0 : ℝ) < n := by positivity
  have hb : (1 : ℝ) < n := by exact_mod_cast hn
  rw [so4SpectralLine_norm (by omega), pow_two, ← Real.rpow_add hpos,
    show -s.re + -s.re = -(2 * s.re) by ring, ← Real.rpow_neg_one (n : ℝ)]
  constructor
  · intro h
    have := rpow_left_inj_of_one_lt hb h
    linarith
  · intro h
    rw [h]
    norm_num

/-- The transformer is multiplicative: `(ab)^{−s} = a^{−s} · b^{−s}`. -/
theorem so4SpectralLine_mul (a b : ℕ) (s : ℂ) :
    so4SpectralLine (a * b) s = so4SpectralLine a s * so4SpectralLine b s := by
  unfold so4SpectralLine
  rw [show ((a * b : ℕ) : ℂ) = (((a : ℝ) : ℂ)) * (((b : ℝ) : ℂ)) by
      push_cast; ring,
    mul_cpow_ofReal_nonneg (Nat.cast_nonneg a) (Nat.cast_nonneg b)]
  norm_num

/-- **Every line is generated by a prime line**: every `n ≥ 2` is a multiple
of a prime, and its spectral line factors through that prime's line. -/
theorem spectral_line_prime_factorization (n : ℕ) (hn : 2 ≤ n) :
    ∃ p m : ℕ, p.Prime ∧ n = p * m ∧
      ∀ s : ℂ, so4SpectralLine n s = so4SpectralLine p s * so4SpectralLine m s := by
  obtain ⟨p, hp, m, hm⟩ := Nat.exists_prime_and_dvd (by omega : n ≠ 1)
  exact ⟨p, m, hp, hm, fun s => by rw [hm, so4SpectralLine_mul]⟩

/-! ## 4. The forcing capstone -/

/--
**RH ⇔ square-root spectral weights at every zero.**  The Riemann Hypothesis
is equivalent to: at every nontrivial zero, every spectral line carries
exactly square-root weight, `‖n^{−ρ}‖² = 1/n` for all `n ≥ 2`.  "For every
prime, the zero sits at its square-root pole weight" — made exact, and
proved equivalent to RH.
-/
theorem RH_iff_zero_spectral_weights :
    RiemannHypothesis ↔
      ∀ ρ : ℂ, IsNontrivialZetaZero ρ → ∀ n : ℕ, 2 ≤ n →
        ‖so4SpectralLine n ρ‖ ^ 2 = (n : ℝ)⁻¹ := by
  constructor
  · intro hRH ρ hz n hn
    exact (so4SpectralLine_sq_weight hn).mpr (hRH ρ hz.1 hz.2.1 hz.2.2)
  · intro hW ρ hz hnt h1
    exact (so4SpectralLine_sq_weight (le_refl 2)).mp
      (hW ρ ⟨hz, hnt, h1⟩ 2 (le_refl 2))

/--
**The three locators agree at every zero.**  At any nontrivial zero `ρ`, the
following are all equivalent to `Re ρ = 1/2`: vanishing equator twiddle,
unimodular factorization tangent, and all spectral lines at square-root
weight.  Tangency, twiddle, and spectral cancellation point at the same
locus — and RH is the statement that every zero lands there.
-/
theorem zero_line_characterizations (ρ : ℂ) (h : IsNontrivialZetaZero ρ) :
    (ρ.re = (1 / 2 : ℝ) ↔ so4CriticalFactor ρ = 0) ∧
    (ρ.re = (1 / 2 : ℝ) ↔ Complex.normSq (projTangent ρ) = 1) ∧
    (ρ.re = (1 / 2 : ℝ) ↔
      ∀ n : ℕ, 2 ≤ n → ‖so4SpectralLine n ρ‖ ^ 2 = (n : ℝ)⁻¹) := by
  obtain ⟨h0, h1⟩ := nontrivial_zero_open_strip ρ h
  refine ⟨(so4CriticalFactor_zero_iff ρ).symm,
    (normSq_projTangent_eq_one_iff h0 h1).symm, ?_, ?_⟩
  · intro hσ n hn
    exact (so4SpectralLine_sq_weight hn).mpr hσ
  · intro hW
    exact (so4SpectralLine_sq_weight (le_refl 2)).mp (hW 2 (le_refl 2))

end

end Hqiv.Story
